import type { ReactElement } from 'react';

/**
 * Server Component that emits a `<script type="application/ld+json">` tag
 * carrying the per-request CSP nonce.
 *
 * # CSP contract
 *
 * Inline scripts on MyConciergeHotel.com live under a strict CSP3 policy:
 *
 *     script-src 'self' 'nonce-{nonce}' 'strict-dynamic'
 *
 * Any inline `<script>` (including `type="application/ld+json"`) must carry
 * the per-request nonce or it is blocked by the browser — there is no
 * `'unsafe-inline'` fallback in production. The nonce is generated by
 * `proxy.ts` (see `lib/security/csp.ts`) and exposed both as the
 * `x-nonce` request header and as the `Content-Security-Policy` nonce-source.
 *
 * # Why nonce is a required prop (vs reading `headers()` here)
 *
 * Earlier versions of this component called `headers()` internally. That had
 * two problems:
 *
 *   1. The dynamic-API call was hidden inside a leaf RSC, so pages declaring
 *      `revalidate = N` *looked* ISR-cached while in fact triggering opaque
 *      Next.js fall-throughs — `DYNAMIC_SERVER_USAGE` 500s on the hotel
 *      detail (resolved in PR #56), or — worse — silently-cached HTML with
 *      `nonce=""` that the browser then refused to execute (resolved on
 *      the home in PR #57).
 *   2. Each `<JsonLdScript>` re-resolved the same request headers, which
 *      Next.js logs as a perf warning when many of them ship on a single
 *      page.
 *
 * Requiring callers to read the nonce once at the page boundary and forward
 * it explicitly makes the request-scoped dependency visible in the page
 * file. Pages that emit JSON-LD therefore *must* be dynamic (the
 * `headers()` call at the top is what marks them as such).
 *
 * Skill: structured-data-schema-org §JSON-LD + security-engineering §CSP.
 */
interface JsonLdScriptProps {
  readonly data: unknown;
  /**
   * Per-request CSP nonce read from the `x-nonce` header set by the proxy.
   * Pages typically build it as:
   *
   * ```ts
   * const nonce = (await headers()).get('x-nonce') ?? undefined;
   * ```
   *
   * `undefined` is accepted to keep callers tolerant of routes where the
   * proxy matcher excludes the request (e.g. dev tooling, internal
   * smoke endpoints). In production every page-route hits the proxy
   * so this is always a real value.
   */
  readonly nonce: string | undefined;
}

export function JsonLdScript({ data, nonce }: JsonLdScriptProps): ReactElement {
  return (
    <script
      type="application/ld+json"
      nonce={nonce}
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

/** A single Schema.org node — the typed objects returned by the `@mch/seo` builders. */
export type SeoJsonLdNode = object;

interface SeoJsonLdProps {
  /**
   * One node, or an array of nodes. `null` / `undefined` entries are skipped,
   * so callers can pass conditional blocks inline (e.g. an optional video
   * node) without pre-filtering:
   *
   * ```tsx
   * <SeoJsonLd nonce={nonce} nodes={[hotelJsonLd, faqJsonLd, videoJsonLd, ...eventNodes]} />
   * ```
   */
  readonly nodes: SeoJsonLdNode | ReadonlyArray<SeoJsonLdNode | null | undefined>;
  /** Per-request CSP nonce, read once at the page boundary (see {@link JsonLdScript}). */
  readonly nonce: string | undefined;
}

/**
 * Dedicated, SSR-only component that emits every JSON-LD block of a page
 * through a single, strongly-typed entry point. It renders one
 * `<script type="application/ld+json">` per node (each self-contained with its
 * own `@context`), forwarding the CSP nonce so the markup ships in the initial
 * server HTML — present from the very first crawl/index.
 *
 * Common root nodes (Organization, WebSite) are factored into
 * `components/seo/site-json-ld.tsx` + `lib/jsonld/brand-organization.ts`;
 * page-specific nodes (Hotel/LocalBusiness, Event, FAQPage, ItemList, …) are
 * passed in by the page that owns them.
 */
export function SeoJsonLd({ nodes, nonce }: SeoJsonLdProps): ReactElement {
  const list = (Array.isArray(nodes) ? nodes : [nodes]).filter(
    (node): node is SeoJsonLdNode => node !== null && node !== undefined,
  );
  return (
    <>
      {list.map((data, index) => (
        <JsonLdScript key={index} data={data} nonce={nonce} />
      ))}
    </>
  );
}
