// AUTO-GENERATED by scripts/editorial-pilot/src/rankings/tmp-dedupe-hotels.ts
// Twin-fiche dedupe (2026-06-29). Each dropped (unpublished) duplicate hotel
// slug 301s to the canonical (richest live) fiche. FR is served bare; EN under
// /en. Consumed by apps/web/next.config.ts redirects().
export interface HotelDedupeRedirect {
  readonly fromFr: string;
  readonly toFr: string;
  readonly fromEn: string;
  readonly toEn: string;
}

export const HOTEL_DEDUPE_REDIRECTS: readonly HotelDedupeRedirect[] = [
  {
    fromFr: 'akelarre-restaurant-hotel',
    toFr: 'akelarre',
    fromEn: 'akelarre-restaurant-hotel',
    toEn: 'akelarre',
  },
  {
    fromFr: 'aman-venice',
    toFr: 'aman-venice-venise',
    fromEn: 'aman-venice',
    toEn: 'aman-venice-venise',
  },
  {
    fromFr: 'belmond-palacio-nazarenas',
    toFr: 'palacio-nazarenas',
    fromEn: 'belmond-palacio-nazarenas',
    toEn: 'palacio-nazarenas',
  },
  {
    fromFr: 'bulgari-hotel-london',
    toFr: 'bvlgari-hotel-london',
    fromEn: 'bulgari-hotel-london',
    toEn: 'bvlgari-hotel-london',
  },
  {
    fromFr: 'bvlgari-hotel-and-resort',
    toFr: 'bulgari-hotel',
    fromEn: 'bvlgari-hotel-and-resort',
    toEn: 'bulgari-hotel',
  },
  {
    fromFr: 'bvlgari-hotel-paris',
    toFr: 'bulgari-hotel-paris',
    fromEn: 'bvlgari-hotel-paris',
    toEn: 'bulgari-hotel-paris',
  },
  {
    fromFr: 'bvlgari-hotel-roma',
    toFr: 'bulgari-roma',
    fromEn: 'bvlgari-hotel-roma',
    toEn: 'bulgari-roma',
  },
  {
    fromFr: 'bvlgari-resort-bali',
    toFr: 'bulgari-hotel-bali',
    fromEn: 'bvlgari-resort-bali',
    toEn: 'bulgari-hotel-bali',
  },
  {
    fromFr: 'caruso-a-belmond-hotel',
    toFr: 'belmond-caruso',
    fromEn: 'caruso-a-belmond-hotel',
    toEn: 'belmond-caruso',
  },
  {
    fromFr: 'casa-pestagua',
    toFr: 'relais-and-chateaux-hotel-casa-pestagua',
    fromEn: 'casa-pestagua',
    toEn: 'relais-and-chateaux-hotel-casa-pestagua',
  },
  {
    fromFr: 'castelfalfi',
    toFr: 'castelfalfi-florence',
    fromEn: 'castelfalfi',
    toEn: 'castelfalfi-florence',
  },
  {
    fromFr: 'castello-di-casole-a-belmond-hotel',
    toFr: 'castello-di-casole',
    fromEn: 'castello-di-casole-a-belmond-hotel',
    toEn: 'castello-di-casole',
  },
  {
    fromFr: 'chateau-de-collias',
    toFr: 'le-chateau-collias',
    fromEn: 'chateau-de-collias',
    toEn: 'le-chateau-collias',
  },
  {
    fromFr: 'chateau-la-commaraine',
    toFr: 'chateau-de-la-commaraine',
    fromEn: 'chateau-la-commaraine',
    toEn: 'chateau-de-la-commaraine',
  },
  {
    fromFr: 'claridge-s',
    toFr: 'claridge-s-londres',
    fromEn: 'claridge-s',
    toEn: 'claridge-s-londres',
  },
  {
    fromFr: 'claridges',
    toFr: 'claridge-s-londres',
    fromEn: 'claridges',
    toEn: 'claridge-s-londres',
  },
  {
    fromFr: 'coworth-park-dorchester-collection',
    toFr: 'coworth-park',
    fromEn: 'coworth-park-dorchester-collection',
    toEn: 'coworth-park',
  },
  {
    fromFr: 'domaine-des-andeols',
    toFr: 'le-domaine-des-andeols',
    fromEn: 'domaine-des-andeols',
    toEn: 'le-domaine-des-andeols',
  },
  {
    fromFr: 'faustino-gran',
    toFr: 'faustino-gran-relais-and-chateaux',
    fromEn: 'faustino-gran',
    toEn: 'faustino-gran-relais-and-chateaux',
  },
  {
    fromFr: 'fouquet-s-paris',
    toFr: 'hotel-fouquet-s-paris',
    fromEn: 'fouquet-s-paris',
    toEn: 'hotel-fouquet-s-paris',
  },
  {
    fromFr: 'four-seasons-georges-v',
    toFr: 'four-seasons-hotel-george-v',
    fromEn: 'four-seasons-georges-v',
    toEn: 'four-seasons-hotel-george-v',
  },
  {
    fromFr: 'four-seasons-resort-dubai-at-jumeirah-beach',
    toFr: 'four-seasons-jumeirah',
    fromEn: 'four-seasons-resort-dubai-at-jumeirah-beach',
    toEn: 'four-seasons-jumeirah',
  },
  {
    fromFr: 'hotel-altapura',
    toFr: 'altapura',
    fromEn: 'hotel-altapura',
    toEn: 'altapura',
  },
  {
    fromFr: 'hotel-cipriani',
    toFr: 'belmond-hotel-cipriani',
    fromEn: 'hotel-cipriani',
    toEn: 'belmond-hotel-cipriani',
  },
  {
    fromFr: 'hotel-das-cataratas',
    toFr: 'belmond-hotel-das-cataratas',
    fromEn: 'hotel-das-cataratas',
    toEn: 'belmond-hotel-das-cataratas',
  },
  {
    fromFr: 'hotel-fouquet-s-saint-barth',
    toFr: 'fouquet-s-saint-barth',
    fromEn: 'hotel-fouquet-s-saint-barth',
    toEn: 'fouquet-s-saint-barth',
  },
  {
    fromFr: 'hotel-la-cheneaudiere',
    toFr: 'la-cheneaudiere-hotel-and-spa',
    fromEn: 'hotel-la-cheneaudiere',
    toEn: 'la-cheneaudiere-hotel-and-spa',
  },
  {
    fromFr: 'hotel-la-ponche',
    toFr: 'la-ponche',
    fromEn: 'hotel-la-ponche',
    toEn: 'la-ponche',
  },
  {
    fromFr: 'hotel-restaurant-la-maison-zugno',
    toFr: 'maison-zugno-hotel-and-spa',
    fromEn: 'hotel-restaurant-la-maison-zugno',
    toEn: 'maison-zugno-hotel-and-spa',
  },
  {
    fromFr: 'hotel-saint-james-paris',
    toFr: 'saint-james-paris',
    fromEn: 'hotel-saint-james-paris',
    toEn: 'saint-james-paris',
  },
  {
    fromFr: 'hotel-voulez-vous',
    toFr: 'hotel-voulezvous',
    fromEn: 'hotel-voulez-vous',
    toEn: 'hotel-voulezvous',
  },
  {
    fromFr: 'la-cheneaudiere',
    toFr: 'la-cheneaudiere-hotel-and-spa',
    fromEn: 'la-cheneaudiere',
    toEn: 'la-cheneaudiere-hotel-and-spa',
  },
  {
    fromFr: 'la-cheneaudiere-and-spa',
    toFr: 'la-cheneaudiere-hotel-and-spa',
    fromEn: 'la-cheneaudiere-and-spa',
    toEn: 'la-cheneaudiere-hotel-and-spa',
  },
  {
    fromFr: 'la-ferme-du-vent',
    toFr: 'ferme-du-vent',
    fromEn: 'la-ferme-du-vent',
    toEn: 'ferme-du-vent',
  },
  {
    fromFr: 'le-castel-marie-louise',
    toFr: 'castel-marie-louise',
    fromEn: 'le-castel-marie-louise',
    toEn: 'castel-marie-louise',
  },
  {
    fromFr: 'le-chateau-de-montcaud',
    toFr: 'chateau-de-montcaud',
    fromEn: 'le-chateau-de-montcaud',
    toEn: 'chateau-de-montcaud',
  },
  {
    fromFr: 'le-fouquet-s-paris',
    toFr: 'hotel-fouquet-s-paris',
    fromEn: 'le-fouquet-s-paris',
    toEn: 'hotel-fouquet-s-paris',
  },
  {
    fromFr: 'le-norman',
    toFr: 'norman-hotel-and-spa',
    fromEn: 'le-norman',
    toEn: 'norman-hotel-and-spa',
  },
  {
    fromFr: 'maison-zugno',
    toFr: 'maison-zugno-hotel-and-spa',
    fromEn: 'maison-zugno',
    toEn: 'maison-zugno-hotel-and-spa',
  },
  {
    fromFr: 'manapany',
    toFr: 'hotel-manapany',
    fromEn: 'manapany',
    toEn: 'hotel-manapany',
  },
  {
    fromFr: 'mandarin-oriental-jumeira',
    toFr: 'mandarin-oriental-jumeirah',
    fromEn: 'mandarin-oriental-jumeira',
    toEn: 'mandarin-oriental-jumeirah',
  },
  {
    fromFr: 'maroma',
    toFr: 'maroma-a-belmond-hotel',
    fromEn: 'maroma',
    toEn: 'maroma-a-belmond-hotel',
  },
  {
    fromFr: 'monsieur-george-hotel-and-spa',
    toFr: 'monsieur-george',
    fromEn: 'monsieur-george-hotel-and-spa',
    toEn: 'monsieur-george',
  },
  {
    fromFr: 'riad-fes',
    toFr: 'riad-fes-relais-and-chateaux',
    fromEn: 'riad-fes',
    toEn: 'riad-fes-relais-and-chateaux',
  },
  {
    fromFr: 'ritz-carlton-philadelphia',
    toFr: 'the-ritz-carlton-philadelphia',
    fromEn: 'ritz-carlton-philadelphia',
    toEn: 'the-ritz-carlton-philadelphia',
  },
  {
    fromFr: 'san-ysidro-ranch',
    toFr: 'san-ysidro-ranch-santa-barbara',
    fromEn: 'san-ysidro-ranch',
    toEn: 'san-ysidro-ranch-santa-barbara',
  },
  {
    fromFr: 'son-bunyola',
    toFr: 'son-bunyola-hotel',
    fromEn: 'son-bunyola',
    toEn: 'son-bunyola-hotel',
  },
  {
    fromFr: 'southern-ocean-lodge-kingscote',
    toFr: 'southern-ocean-lodge',
    fromEn: 'southern-ocean-lodge-kingscote',
    toEn: 'southern-ocean-lodge',
  },
  {
    fromFr: 'st-regis-venice',
    toFr: 'the-st-regis-venice',
    fromEn: 'st-regis-venice',
    toEn: 'the-st-regis-venice',
  },
  {
    fromFr: 'the-connaught',
    toFr: 'the-connaught-londres',
    fromEn: 'the-connaught',
    toEn: 'the-connaught-londres',
  },
  {
    fromFr: 'the-lana',
    toFr: 'the-lana-by-dorchester-collection',
    fromEn: 'the-lana',
    toEn: 'the-lana-by-dorchester-collection',
  },
  {
    fromFr: 'the-lana-dorchester-collection',
    toFr: 'the-lana-by-dorchester-collection',
    fromEn: 'the-lana-dorchester-collection',
    toEn: 'the-lana-by-dorchester-collection',
  },
  {
    fromFr: 'the-silo',
    toFr: 'the-silo-hotel',
    fromEn: 'the-silo',
    toEn: 'the-silo-hotel',
  },
  {
    fromFr: 'tiara-miramar-beach-hotel-and-spa',
    toFr: 'tiara-miramar-beach-resort',
    fromEn: 'tiara-miramar-beach-hotel-and-spa',
    toEn: 'tiara-miramar-beach-resort',
  },
  {
    fromFr: 'voulezvous-hotel',
    toFr: 'hotel-voulezvous',
    fromEn: 'voulezvous-hotel',
    toEn: 'hotel-voulezvous',
  },
];
