/**
 * report-completeness.ts — C2 (2026-06-24) catalogue-wide completeness audit.
 *
 * Reads (PostgREST, service-role) every `editorial_rankings` row + its entry
 * count, joins to the combinator `targetLength` per seed, and writes the gaps
 * report to `docs/audits/rankings-completeness-gaps-2026-06-24.md`.
 *
 * Read-only — it NEVER generates or republishes anything (that's Phase E).
 * `--strict` exits non-zero when at least one published, seed-matched ranking
 * is below its target.
 *
 * Run (PowerShell):
 *   pnpm --filter @mch/editorial-pilot exec tsx src/rankings/report-completeness.ts [--strict]
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { completenessStatus, summarizeCompleteness } from './completeness.js';
import { loadRankingsV2 } from './rankings-catalog-v2.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PILOT_ROOT = path.resolve(__dirname, '../..');
const REPO_ROOT = path.resolve(PILOT_ROOT, '../..');
const REPORT_PATH = path.resolve(REPO_ROOT, 'docs/audits/rankings-completeness-gaps-2026-06-24.md');

const ENV_CACHE: Record<string, string> = {};

async function loadEnvFile(relPath: string): Promise<void> {
  try {
    const txt = await fs.readFile(path.resolve(REPO_ROOT, relPath), 'utf8');
    for (const line of txt.split(/\r?\n/u)) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/u);
      const k = m?.[1];
      const v = m?.[2];
      if (k !== undefined && v !== undefined && ENV_CACHE[k] === undefined) {
        ENV_CACHE[k] = v.trim().replace(/^['"]|['"]$/gu, '');
      }
    }
  } catch {
    /* missing env file → ignore */
  }
}

function readEnv(name: string): string {
  return ENV_CACHE[name] ?? process.env[name] ?? '';
}

interface RankingRow {
  readonly id: string;
  readonly slug: string;
  readonly is_published: boolean;
}

async function fetchAll<T>(url: string, key: string, select: string): Promise<T[]> {
  const pageSize = 1000;
  const out: T[] = [];
  for (let offset = 0; ; offset += pageSize) {
    const q = `${url}${url.includes('?') ? '&' : '?'}select=${select}&limit=${pageSize}&offset=${offset}`;
    const res = await fetch(q, { headers: { apikey: key, Authorization: `Bearer ${key}` } });
    if (!res.ok) throw new Error(`PostgREST ${res.status}: ${await res.text()}`);
    const json: unknown = await res.json();
    if (!Array.isArray(json)) throw new Error('SELECT did not return an array.');
    for (const r of json) out.push(r as T);
    if (json.length < pageSize) break;
  }
  return out;
}

async function main(): Promise<void> {
  const strict = process.argv.slice(2).includes('--strict');

  await loadEnvFile('apps/web/.env.local');
  await loadEnvFile('.env.local');
  const url = readEnv('NEXT_PUBLIC_SUPABASE_URL').replace(/\/$/u, '');
  const key = readEnv('SUPABASE_SERVICE_ROLE_KEY');
  if (url.length === 0 || key.length === 0) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY.');
  }

  console.log('Loading combinator matrix (targets)…');
  const loaded = await loadRankingsV2({ skipUnderfilled: false });
  const targetBySlug = new Map<string, number>();
  for (const seed of loaded.matrix.seeds) targetBySlug.set(seed.slug, seed.targetLength);

  console.log('Fetching editorial_rankings…');
  const rankings = await fetchAll<RankingRow>(
    `${url}/rest/v1/editorial_rankings`,
    key,
    'id,slug,is_published',
  );

  console.log('Fetching editorial_ranking_entries…');
  const entries = await fetchAll<{ ranking_id: string }>(
    `${url}/rest/v1/editorial_ranking_entries`,
    key,
    'ranking_id',
  );
  const countByRankingId = new Map<string, number>();
  for (const e of entries) {
    countByRankingId.set(e.ranking_id, (countByRankingId.get(e.ranking_id) ?? 0) + 1);
  }

  const matched = [] as ReturnType<typeof completenessStatus>[];
  const matchedPublished = [] as ReturnType<typeof completenessStatus>[];
  let unmatched = 0;
  for (const r of rankings) {
    const target = targetBySlug.get(r.slug);
    const n = countByRankingId.get(r.id) ?? 0;
    if (target === undefined) {
      unmatched += 1;
      continue;
    }
    const s = completenessStatus(r.slug, n, target);
    matched.push(s);
    if (r.is_published) matchedPublished.push(s);
  }

  const sumAll = summarizeCompleteness(matched, 100);
  const sumPub = summarizeCompleteness(matchedPublished, 100);

  const now = new Date().toISOString();
  const lines: string[] = [];
  lines.push('# Rankings completeness gaps — 2026-06-24 (C2)');
  lines.push('');
  lines.push(
    `> Generated by \`scripts/editorial-pilot/src/rankings/report-completeness.ts\` at ${now}.`,
  );
  lines.push('> Read-only audit. **No ranking was generated or republished** (that is Phase E).');
  lines.push('');
  lines.push('## Method');
  lines.push('');
  lines.push(
    'A ranking is **complete** when its persisted `editorial_ranking_entries` count reaches the ',
  );
  lines.push(
    'combinator `targetLength` for the matching seed (shared helper `completeness.ts`). Rankings ',
  );
  lines.push(
    'with no combinator seed (curated/pillar rows, chain rankings, legacy slugs) are reported ',
  );
  lines.push('separately and are **out of scope** for the target gate.');
  lines.push('');
  lines.push('## Headline figures');
  lines.push('');
  lines.push('| Scope | Total | Complete | Underfilled | Empty |');
  lines.push('| --- | ---: | ---: | ---: | ---: |');
  lines.push(
    `| Seed-matched (all) | ${sumAll.total} | ${sumAll.complete} | ${sumAll.underfilled} | ${sumAll.empty} |`,
  );
  lines.push(
    `| Seed-matched (published) | ${sumPub.total} | ${sumPub.complete} | ${sumPub.underfilled} | ${sumPub.empty} |`,
  );
  lines.push(`| Unmatched (no seed — out of scope) | ${unmatched} | — | — | — |`);
  lines.push('');
  lines.push('## Underfilled published rankings (largest gap first)');
  lines.push('');
  if (sumPub.worstGaps.length === 0) {
    lines.push('_None — every published seed-matched ranking meets its target._');
  } else {
    lines.push('| Slug | Entries | Target | Gap |');
    lines.push('| --- | ---: | ---: | ---: |');
    for (const g of sumPub.worstGaps) {
      lines.push(`| \`${g.slug}\` | ${g.entries} | ${g.target} | ${g.gap} |`);
    }
  }
  lines.push('');
  lines.push('## Pillar / combinator reconciliation');
  lines.push('');
  lines.push(
    '- **Combinator seeds** derive `targetLength` from scope (city/cluster/country/theme). The ',
  );
  lines.push(
    '  `--strict` gate in `run-rankings-v2-bulk.ts` now refuses to push a freshly-generated seed ',
  );
  lines.push('  whose `entries.length` is below that target.');
  lines.push(
    '- **Pillar / curated rankings** (chain rankings, Travel+Leisure World\u2019s Best, hand-built ',
  );
  lines.push(
    '  allow-lists) are pushed by dedicated runners with an explicit entry list; their "target" is ',
  );
  lines.push(
    '  the allow-list size. They have no combinator seed, so they appear in the *unmatched* bucket ',
  );
  lines.push(
    '  above and are intentionally exempt from the combinator target gate \u2014 the runner that ',
  );
  lines.push('  owns the allow-list is the source of truth for their completeness.');
  lines.push('- The shared `completeness.ts` helper (`isComplete` / `completenessStatus` / ');
  lines.push(
    '  `summarizeCompleteness`) is the single contract used by the bulk gate, `verify-rankings.ts` ',
  );
  lines.push('  and this report, removing the historic per-script drift.');
  lines.push('');

  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true });
  await fs.writeFile(REPORT_PATH, lines.join('\n'), 'utf8');

  console.log(`\nWrote ${path.relative(REPO_ROOT, REPORT_PATH)}`);
  console.log(
    `Seed-matched: ${sumAll.total} (complete=${sumAll.complete}, underfilled=${sumAll.underfilled}, empty=${sumAll.empty})`,
  );
  console.log(
    `Published seed-matched: ${sumPub.total} (complete=${sumPub.complete}, underfilled=${sumPub.underfilled}, empty=${sumPub.empty})`,
  );
  console.log(`Unmatched (no seed): ${unmatched}`);

  if (strict && sumPub.underfilled > 0) {
    console.error(`\n✗ strict: ${sumPub.underfilled} published ranking(s) below target.`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
