-- 0036 — Publish the 10 Tier 1 country guides (Phase 2 international).
--
-- These were generated by run-guides-v2 --draft on 2026-05-19 (Japan,
-- USA, Italy, UK, Spain, UAE, Turkey, Germany, China, Mexico). Each
-- holds 4500-5000 words FR, 11-12 sections, 20-25 FAQ, 4 comparison
-- tables, 5-12 external sources from the editorial allowlist.
--
-- Quality gates below are stricter than the per-row Zod validation
-- and act as a hard floor for production indexability:
--   * scope = 'country' (not city/region/cluster)
--   * summary_fr 80-200 chars (must be present, not stub)
--   * >= 10 sections
--   * >= 20 FAQ Q&A
--   * >= 3 tables (comparison surfaces)
--   * >= 5 external sources (EEAT signal)
--   * hero_image populated (Wikimedia Commons curated by
--     seed-country-hero-images.ts)
--   * meta_title_fr 30-80 chars, meta_desc_fr 100-180 chars
--
-- Forward-only — to depublish a single guide, write a separate
-- migration that targets its slug.

update public.editorial_guides
set is_published = true,
    reviewed_at = current_date
where scope = 'country'
  and country_code <> 'FR'
  and not is_published
  and length(coalesce(summary_fr, '')) between 80 and 200
  and jsonb_array_length(coalesce(sections, '[]'::jsonb)) >= 10
  and jsonb_array_length(coalesce(faq, '[]'::jsonb)) >= 20
  and jsonb_array_length(coalesce(tables, '[]'::jsonb)) >= 3
  and jsonb_array_length(coalesce(external_sources, '[]'::jsonb)) >= 5
  and hero_image is not null
  and length(coalesce(meta_title_fr, '')) between 30 and 80
  and length(coalesce(meta_desc_fr, '')) between 100 and 180;

insert into public._cct_sql_migrations (filename)
values ('0036_publish_country_guides_v2.sql')
on conflict do nothing;
