-- 0039 — Editorial guides: long-form Concierge lead-in + Concierge sections.
--
-- Context (overnight FR Concierge production, 2026-05-20)
-- --------------------------------------------------------
-- The existing `editorial_guides.summary_fr` (60-220 chars CHECK) covers the
-- AEO / meta-description surface — a compact 130-200 char "carte de visite"
-- generated by `overnight-guides-summary-fr.ts` (Phase 5 quick win).
--
-- The existing `editorial_guides.sections` jsonb (~12 entries per guide on
-- the 50 legacy guides) was produced by `run-guides-v2` (gpt-4o, pre-ADR-0011
-- voice). Those sections are kept for backward compatibility on the public
-- `/guide/[slug]` route.
--
-- This migration adds two NEW columns that hold the **Concierge-voice**
-- rewrite (≤ 25-word sentences strict, sourced facts, no banned superlatives):
--
--   1. `summary_long_fr text` — magazine-style lead-in (~ 2500-5500 chars,
--      400-700 words). Dense prose, no headings, no bullet lists. Reads as
--      the opening voice that frames the destination before the
--      sectioned long-form.
--
--   2. `editorial_sections jsonb` — array of 6-9 entries. Shape mirrors
--      `editorial_rankings.editorial_sections` (introduced in 0028) so the
--      front-end renderer can reuse the same `<EnrichedText>` + sticky-TOC
--      machinery:
--        [{
--          anchor:   text,                          -- kebab-case
--          title_fr: text,                          -- 4-9 words
--          body_fr:  text,                          -- 400-700 words
--          position: int,                           -- 1-based, monotonic
--          kind?:    'overview' | 'when-to-visit' | 'what-to-see'
--                  | 'how-to-get-around' | 'where-to-eat' | 'where-to-stay'
--                  | 'practical' | 'concierge-tip' | 'context'
--        }]
--
-- Why a NEW column instead of overwriting `sections`?
--   - Side-by-side authoring: editors can compare legacy gpt-4o sections vs
--     Concierge rewrite without losing the historical baseline.
--   - The two payloads have different shapes (legacy uses `key`/`type`/
--     `body_en`/`title_en` keys; Concierge uses `anchor`/`kind`/`position`).
--     Keeping them apart avoids a polymorphic JSONB nightmare in the Zod
--     readers downstream.
--   - Forward-only: when the front-end migrates to the Concierge rewrite,
--     a follow-up migration can drop `sections` (write a 00NN_drop_sections.sql
--     when ready).
--
-- No CHECK constraint on `summary_long_fr` length (Zod-side validation
-- handles the 2500-5500 envelope — keeps mutating drafts cheap and avoids
-- locking ourselves out of partial backfills).
--
-- Skill : concierge-voice-pipeline, content-modeling, llm-output-robustness,
--         editorial-long-read-rendering.

alter table public.editorial_guides
  add column if not exists summary_long_fr text;

alter table public.editorial_guides
  add column if not exists editorial_sections jsonb not null default '[]'::jsonb;

comment on column public.editorial_guides.summary_long_fr is
  'Concierge-voice magazine lead-in (~2500-5500 chars, 400-700 words FR). '
  'Dense prose, no headings/bullets. Authored by '
  'scripts/editorial-pilot/overnight-guides-sections-fr.ts (post-ADR-0011 voice).';

comment on column public.editorial_guides.editorial_sections is
  'Concierge-voice long-form sections (6-9 entries). Shape: '
  '[{anchor,title_fr,body_fr,position,kind?}]. Mirrors editorial_rankings.editorial_sections (0028). '
  'Authored by scripts/editorial-pilot/overnight-guides-sections-fr.ts.';

insert into public._cct_sql_migrations (filename)
values ('0039_editorial_guides_summary_long_and_sections.sql')
on conflict do nothing;
