-- 0041_fr_residuals_translations.sql — auto-generated by translate-fr-residuals.ts
-- Restores the French canonical form of two pockets of English content
-- that leaked into _fr-suffixed columns:
--   (a) 57 hotels — restaurant_info.venues[*].type_fr (dictionary)
--   (b) 75 hotels — policies.pets.notes_fr (LLM, Concierge voice)
-- Source audit: out/fr-residuals-runlog-2026-05-20.jsonl
-- Forward-only. Idempotent: re-running on already-translated rows is a no-op.

-- [cuisine] 5-terres-hotel-spa-mgallery-by-sofitel — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Alsatian"→"Alsacienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"gourmet restaurant","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"name":"restaurant gastronomique","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Joël Philipps","name":"La Table du 5","type_en":"Alsatian","type_fr":"Alsacienne"}]'::jsonb)
where slug = '5-terres-hotel-spa-mgallery-by-sofitel';

-- [cuisine] balthazar-hotel-spa — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Benjamin Jourdren","name":"La Table du Balthazar","type_en":"Cuisine moderne","type_fr":"Cuisine moderne"},{"chef":"Michel Rostang","name":"La Table de Balthazar","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1}]'::jsonb)
where slug = 'balthazar-hotel-spa';

-- [cuisine] bulgari-hotel-paris — 1 venue(s) — "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Niko Romito","name":"Il Ristorante – Niko Romito","type_en":"Italian","type_fr":"Italienne","michelin_stars":3}]'::jsonb)
where slug = 'bulgari-hotel-paris';

-- [cuisine] byblos-saint-tropez — 3 venue(s) — "Mediterranean"→"Méditerranéenne", "Italian"→"Italienne", "Creative"→"Créative"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Arnaud Donckele","name":"La Vague d''Or","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":3},{"chef":"Philippe Colinet","name":"Colette","type_en":"Mediterranean","type_fr":"Méditerranéenne","michelin_stars":1},{"chef":"Nicola Canuti","name":"Il Giardino","type_en":"Italian","type_fr":"Italienne"},{"chef":"Arnaud Donckele","name":"La Vague d''Or - Cheval Blanc St-Tropez","type_en":"Creative","type_fr":"Créative","michelin_stars":3}]'::jsonb)
where slug = 'byblos-saint-tropez';

-- [cuisine] chateau-dapigne — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Nicolas Briand","name":"Les Tourelles","type_en":"modern gastronomy","type_fr":"modern gastronomy"},{"name":"Les Tourelles - Château d''Apigné","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"}]'::jsonb)
where slug = 'chateau-dapigne';

-- [cuisine] chateau-golf-spa-daugerville — 1 venue(s) — "Traditional cuisine"→"Cuisine traditionnelle"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Olivier ZOCCOLA","name":"Jacques Coeur","type_en":"Traditional cuisine","type_fr":"Cuisine traditionnelle"},{"name":"Jacques Cœur","type_en":"traditional local cuisine","type_fr":"traditional local cuisine"}]'::jsonb)
where slug = 'chateau-golf-spa-daugerville';

-- [cuisine] chateau-saint-martin-vence — 1 venue(s) — "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le Saint-Martin restaurant","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"L''Oliveraie Restaurant","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Romain Antoine","name":"Le Saint-Martin","type_en":"Cuisine moderne","type_fr":"Cuisine moderne"},{"chef":"Romain Antoine","name":"L''Oliveraie","type_en":"Mediterranean","type_fr":"Méditerranéenne"}]'::jsonb)
where slug = 'chateau-saint-martin-vence';

-- [cuisine] cheval-blanc-courchevel — 2 venue(s) — "Creative"→"Créative", "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Yannick Alléno","name":"Le 1947","type_en":"Creative","type_fr":"Créative","michelin_stars":3},{"chef":"Stéphane Buron","name":"Le Chabichou by Stéphane Buron","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"name":"Le Grill Alpin","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Table de Partage","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Terrasse de Cheval Blanc","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Yannick Alléno","name":"Le 1947 à Cheval Blanc","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":3}]'::jsonb)
where slug = 'cheval-blanc-courchevel';

-- [cuisine] cheval-blanc-saint-tropez — 4 venue(s) — "Mediterranean Cuisine"→"Cuisine méditerranéenne", "Mediterranean Cuisine"→"Cuisine méditerranéenne", "Creative"→"Créative", "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Arnaud Donckele","name":"La Vague d''Or","type_en":"Mediterranean Cuisine","type_fr":"Cuisine méditerranéenne","michelin_stars":3},{"chef":"Arnaud Donckele","name":"La Terrasse","type_en":"Mediterranean Cuisine","type_fr":"Cuisine méditerranéenne","michelin_stars":1},{"chef":"Arnaud Donckele","name":"Plénitude - Cheval Blanc Paris","type_en":"Creative","type_fr":"Créative","michelin_stars":3},{"chef":"Arnaud Donckele","name":"Plénitude","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":3},{"name":"Le Bar Restaurant","type_en":"Mediterranean","type_fr":"Méditerranéenne"},{"name":"Riviera Nights","type_en":"Provençal","type_fr":"Provençal"}]'::jsonb)
where slug = 'cheval-blanc-saint-tropez';

-- [cuisine] domaine-de-primard — 2 venue(s) — "Bistronomic"→"Bistronomique", "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Bistrot Martin","type_en":"Bistronomic","type_fr":"Bistronomique"},{"name":"Ottavio La Tavola","type_en":"Italian","type_fr":"Italienne"}]'::jsonb)
where slug = 'domaine-de-primard';

-- [cuisine] four-seasons-hotel-george-v — 2 venue(s) — "French classics"→"Classiques français", "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Christian Le Squer","name":"Le Cinq","type_en":"French classics","type_fr":"Classiques français","michelin_stars":3},{"chef":"Simone Zanoni","name":"Le George","type_en":"Italian","type_fr":"Italienne","michelin_stars":1},{"name":"L’Orangerie","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":2}]'::jsonb)
where slug = 'four-seasons-hotel-george-v';

-- [cuisine] grand-hotel-barriere-de-dinard — 2 venue(s) — "French brasserie"→"Brasserie française", "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le George V","type_en":"French brasserie","type_fr":"Brasserie française"},{"name":"Le Georges V","type_en":"cuisine raffinée","type_fr":"cuisine raffinée"},{"chef":"Julien Hennote","name":"Pourquoi Pas","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1}]'::jsonb)
where slug = 'grand-hotel-barriere-de-dinard';

-- [cuisine] grand-hotel-cap-ferrat — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Yoric Tièche","name":"Le Cap","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"name":"Club Dauphin","type_en":"Provençal","type_fr":"Provençal"}]'::jsonb)
where slug = 'grand-hotel-cap-ferrat';

-- [cuisine] grand-hotel-de-cala-rossa — 1 venue(s) — "Asian"→"Asiatique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"U Sognu","type_en":"Asian","type_fr":"Asiatique"},{"name":"La Plage Casadelmar","type_en":"Cuisine italienne","type_fr":"Cuisine italienne"}]'::jsonb)
where slug = 'grand-hotel-de-cala-rossa';

-- [cuisine] hostellerie-cedre-spa-beaune — 1 venue(s) — "Burgundian"→"Bourguignonne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Christophe Fouquin","name":"Restaurant Hostellerie Cèdre & Spa","type_en":"Burgundian","type_fr":"Bourguignonne","michelin_stars":1}]'::jsonb)
where slug = 'hostellerie-cedre-spa-beaune';

-- [cuisine] hostellerie-la-cheneaudiere-spa — 3 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Modern Cuisine"→"Cuisine moderne", "Creative"→"Créative"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Cheneaudière - Le Chêne","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"name":"Le Chêne","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"name":"Le Feuillage","type_en":"Creative","type_fr":"Créative","michelin_stars":1}]'::jsonb)
where slug = 'hostellerie-la-cheneaudiere-spa';

-- [cuisine] hotel-a-mandria-di-murtoli — 1 venue(s) — "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le goût de l''Italie","type_en":"italienne","type_fr":"italienne"},{"name":"Restaurant","type_en":"italienische Küche","type_fr":"italienische Küche"},{"name":"guest-only restaurant","type_en":"Italian","type_fr":"Italienne"}]'::jsonb)
where slug = 'hotel-a-mandria-di-murtoli';

-- [cuisine] hotel-castelbrac — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Seafood"→"Fruits de mer"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Julien Hennote","name":"Pourquoi Pas","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"name":"Le Pourquoi Pas","type_en":"Seafood","type_fr":"Fruits de mer"},{"name":"Pourquoi Pas Restaurant","type_en":"Restaurant","type_fr":"Restaurant"}]'::jsonb)
where slug = 'hotel-castelbrac';

-- [cuisine] hotel-chateau-dartigny — 1 venue(s) — "Creative, Modern Cuisine"→"Cuisine créative et moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Gaëtan Evrard","name":"L''Évidence","type_en":"Creative, Modern Cuisine","type_fr":"Cuisine créative et moderne","michelin_stars":1}]'::jsonb)
where slug = 'hotel-chateau-dartigny';

-- [cuisine] hotel-clos-vauban — 1 venue(s) — "Creative"→"Créative"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Valentin Loison","name":"Bulle d''Osier","type_en":"Creative","type_fr":"Créative"},{"name":"Mirabelle","type_en":"Cuisine moderne","type_fr":"Cuisine moderne"}]'::jsonb)
where slug = 'hotel-clos-vauban';

-- [cuisine] hotel-como-le-montrachet — 1 venue(s) — "seasonal French classics"→"Classiques français de saison"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"restaurante","type_en":"cocina clásica francesa de temporada","type_fr":"cocina clásica francesa de temporada"},{"name":"restaurant","type_en":"seasonal French classics","type_fr":"Classiques français de saison"}]'::jsonb)
where slug = 'hotel-como-le-montrachet';

-- [cuisine] hotel-corsica — 1 venue(s) — "Mediterranean and Corsica flavors"→"Méditerranéenne et corse"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Signoria","type_en":"Mediterranean and Corsica flavors","type_fr":"Méditerranéenne et corse"}]'::jsonb)
where slug = 'hotel-corsica';

-- [cuisine] hotel-de-crillon-a-rosewood-hotel — 2 venue(s) — "traditional French cuisine with a twist"→"Cuisine française traditionnelle revisitée", "French-style grill"→"Grill à la française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Paul Pairet","name":"Nonos & Comestibles","type_en":"grill à la française","type_fr":"grill à la française"},{"chef":"Matthieu Carlin","name":"Restaurant Jardin d’Hiver","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Xavier Thuizat","name":"La Cave","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"L’Écrin","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1},{"name":"Nonos & Comestibles par Paul Pairet","type_en":"traditional French cuisine with a twist","type_fr":"Cuisine française traditionnelle revisitée"},{"chef":"Paul Pairet","name":"Nonos par Paul Pairet","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Paul Pairet","name":"Nonos","type_en":"French-style grill","type_fr":"Grill à la française"}]'::jsonb)
where slug = 'hotel-de-crillon-a-rosewood-hotel';

-- [cuisine] hotel-des-berges — 1 venue(s) — "Classic Cuisine"→"Cuisine classique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Jean-Paul Bostoen","name":"l''Auberge de l''Ill","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":2},{"chef":"Marc Haeberlin","name":"Auberge de l''Ill","type_en":"Classic Cuisine","type_fr":"Cuisine classique","michelin_stars":2}]'::jsonb)
where slug = 'hotel-des-berges';

-- [cuisine] hotel-domaine-misincu — 1 venue(s) — "Gastronomic Cuisine"→"Cuisine gastronomique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Reine Sammut","name":"La Table","type_en":"Gastronomic Cuisine","type_fr":"Cuisine gastronomique"}]'::jsonb)
where slug = 'hotel-domaine-misincu';

-- [cuisine] hotel-don-cesar-spa — 3 venue(s) — "Italian"→"Italienne", "Modern Cuisine"→"Cuisine moderne", "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"restaurant & grill","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Plage Casadelmar","type_en":"Italian","type_fr":"Italienne"},{"name":"La Table de Mina","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"chef":"Fabio Bragagnolo","name":"Casadelmar","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":2}]'::jsonb)
where slug = 'hotel-don-cesar-spa';

-- [cuisine] hotel-du-cap-eden-roc — 5 venue(s) — "Mediterranean Cuisine"→"Cuisine méditerranéenne", "Mediterranean and Provençal"→"Méditerranéenne et provençale", "Mediterranean and Provençal"→"Méditerranéenne et provençale", "Mediterranean and Provençal"→"Méditerranéenne et provençale", "Mediterranean and Provençal"→"Méditerranéenne et provençale"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Sébastien Broda","name":"Louroc","type_en":"Mediterranean Cuisine","type_fr":"Cuisine méditerranéenne","michelin_stars":1},{"chef":"Sébastien Broda","name":"Restaurant LouRoc","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1},{"chef":"Sébastien Broda","name":"Eden-Roc Restaurant","type_en":"Mediterranean and Provençal","type_fr":"Méditerranéenne et provençale"},{"chef":"Sébastien Broda","name":"The Grill","type_en":"Mediterranean and Provençal","type_fr":"Méditerranéenne et provençale"},{"chef":"Sébastien Broda","name":"Louroc Restaurant","type_en":"Mediterranean and Provençal","type_fr":"Méditerranéenne et provençale"},{"chef":"Sébastien Broda","name":"Giovanni''s","type_en":"Mediterranean and Provençal","type_fr":"Méditerranéenne et provençale"}]'::jsonb)
where slug = 'hotel-du-cap-eden-roc';

-- [cuisine] hotel-du-centre-nautique — 1 venue(s) — "Corsican and Italian"→"Corse et italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le Restaurant","type_en":"cuisine corse et italienne","type_fr":"cuisine corse et italienne"},{"name":"The Restaurant","type_en":"Corsican and Italian","type_fr":"Corse et italienne"}]'::jsonb)
where slug = 'hotel-du-centre-nautique';

-- [cuisine] hotel-le-chambard — 1 venue(s) — "Alsatian"→"Alsacienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Olivier Nasti","name":"La Table d''Olivier Nasti","type_en":"contemporary cuisine","type_fr":"contemporary cuisine","michelin_stars":2},{"name":"La Winstub","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Olivier Nasti","name":"Winstub du Chambard","type_en":"Cuisine alsacienne, Cuisine traditionnelle","type_fr":"Cuisine alsacienne, Cuisine traditionnelle"},{"chef":"Olivier Nasti","name":"La Winstub du Chambard","type_en":"Alsatian","type_fr":"Alsacienne"}]'::jsonb)
where slug = 'hotel-le-chambard';

-- [cuisine] hotel-le-chateau-de-germigney — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Indulgent cuisine"→"Cuisine gourmande"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Maison Zugno","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"name":"Le Bistrot de Port Lesney","type_en":"Indulgent cuisine","type_fr":"Cuisine gourmande"}]'::jsonb)
where slug = 'hotel-le-chateau-de-germigney';

-- [cuisine] hotel-le-domaine-de-locguenole-spa — 2 venue(s) — "Gastronomic"→"Gastronomique", "Traditional Cuisine"→"Cuisine traditionnelle"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Yann Maget","name":"L’Inattendu","type_en":"Gastronomic","type_fr":"Gastronomique","michelin_stars":1},{"chef":"Yann Maget","name":"La Maison Alyette","type_en":"Traditional Cuisine","type_fr":"Cuisine traditionnelle"}]'::jsonb)
where slug = 'hotel-le-domaine-de-locguenole-spa';

-- [cuisine] hotel-le-domaine-des-hauts-de-loire — 2 venue(s) — "Traditional Cuisine"→"Cuisine traditionnelle", "Classic Cuisine"→"Cuisine classique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Arthur Peta","name":"Le Restaurant gastronomique","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"Le Bistrot","type_en":"cuisine de terroir","type_fr":"cuisine de terroir"},{"chef":"Arthur Peta","name":"Gourmet restaurant","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"Bistrot des Hauts de Loire","type_en":"Traditional Cuisine","type_fr":"Cuisine traditionnelle"},{"name":"Les Hauts de Loire","type_en":"Classic Cuisine","type_fr":"Cuisine classique"}]'::jsonb)
where slug = 'hotel-le-domaine-des-hauts-de-loire';

-- [cuisine] hotel-maison-doucet — 1 venue(s) — "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Frédéric Doucet","name":"Frédéric Doucet","type_en":"French","type_fr":"Française","michelin_stars":2}]'::jsonb)
where slug = 'hotel-maison-doucet';

-- [cuisine] hotel-marinca — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Romain Masset","name":"La Verrière","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"name":"La Paillote","type_en":"Produits méditerranéens à l’honneur","type_fr":"Produits méditerranéens à l’honneur"},{"name":"La Table du Moulin","type_en":"Authentique et intimiste","type_fr":"Authentique et intimiste"}]'::jsonb)
where slug = 'hotel-marinca';

-- [cuisine] hotel-ritz-paris — 2 venue(s) — "French cuisine"→"Cuisine française", "haute French cuisine"→"Haute cuisine française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Eugénie Béziat","name":"Espadon restaurant","type_en":"French cuisine","type_fr":"Cuisine française","michelin_stars":1},{"chef":"Eugénie Béziat","name":"Espadon","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1},{"chef":"Nicolas Sale","name":"La Table de L’Espadon","type_en":"haute French cuisine","type_fr":"Haute cuisine française","michelin_stars":2},{"chef":"Arnaud Faye","name":"Épicure","type_en":"haute gastronomy","type_fr":"haute gastronomy","michelin_stars":3}]'::jsonb)
where slug = 'hotel-ritz-paris';

-- [cuisine] hotel-royal-evian — 1 venue(s) — "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"L''Oliveraie","type_en":"Mediterranean","type_fr":"Méditerranéenne"},{"chef":"Patrice Vander","name":"Les Fresques","type_en":"Moderne Küche","type_fr":"Moderne Küche","michelin_stars":1},{"name":"Les Fresques - Hôtel Royal","type_en":"Cuisine moderne","type_fr":"Cuisine moderne","michelin_stars":1}]'::jsonb)
where slug = 'hotel-royal-evian';

-- [cuisine] hotel-sofitel-golfe-dajaccio — 1 venue(s) — "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Carte Postale","type_en":"Mediterranean","type_fr":"Méditerranéenne"},{"name":"Le Charlie","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1}]'::jsonb)
where slug = 'hotel-sofitel-golfe-dajaccio';

-- [cuisine] hotel-spa-lagapa — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le Belouga","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"}]'::jsonb)
where slug = 'hotel-spa-lagapa';

-- [cuisine] hotel-spa-le-domaine-de-la-klauss — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Bistronomic"→"Bistronomique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Benoit Potdevin","name":"Le K","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"chef":"Lucien Keff","name":"Le Komptoir","type_en":"Bistronomic","type_fr":"Bistronomique"},{"chef":"Lucien Keff","name":"La Paillote","type_en":"cuisine estivale","type_fr":"cuisine estivale"}]'::jsonb)
where slug = 'hotel-spa-le-domaine-de-la-klauss';

-- [cuisine] hotel-the-peninsula-paris — 2 venue(s) — "Creative"→"Créative", "Cantonese"→"Cantonaise"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"David Bizet","name":"Le Rooftop","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"David Bizet","name":"L''Oiseau Blanc","type_en":"Creative","type_fr":"Créative","michelin_stars":2},{"name":"LiLi","type_en":"Cantonese","type_fr":"Cantonaise"}]'::jsonb)
where slug = 'hotel-the-peninsula-paris';

-- [cuisine] la-reserve-paris-hotel-and-spa — 1 venue(s) — "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Jérôme Banctel","name":"Le Gabriel","type_en":"Cuisine créative","type_fr":"Cuisine créative","michelin_stars":3},{"chef":"Jérôme Banctel","name":"La Pagode de Cos","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Jérôme Banctel","name":"La Pagode","type_en":"French","type_fr":"Française","michelin_stars":3}]'::jsonb)
where slug = 'la-reserve-paris-hotel-and-spa';

-- [cuisine] la-reserve-ramatuelle — 4 venue(s) — "Japanese"→"Japonaise", "Modern Cuisine"→"Cuisine moderne", "Mediterranean"→"Méditerranéenne", "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Muña","type_en":"Japanese","type_fr":"Japonaise"},{"chef":"Eric Canino","name":"La Voile","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":2},{"chef":"Nicolas Cantrel","name":"La Réserve à la Plage","type_en":"Mediterranean","type_fr":"Méditerranéenne"},{"name":"La Piscine","type_en":"Italian","type_fr":"Italienne"}]'::jsonb)
where slug = 'la-reserve-ramatuelle';

-- [cuisine] lapogee-courchevel — 1 venue(s) — "French cuisine"→"Cuisine française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Romain Antoine","name":"L''Apogée Club","type_en":"French cuisine","type_fr":"Cuisine française"},{"chef":"Romain Antoine","name":"Beefbar Courchevel","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Sébastien Vauxion","name":"Le Sarkara","type_en":"Cuisine créative","type_fr":"Cuisine créative","michelin_stars":2}]'::jsonb)
where slug = 'lapogee-courchevel';

-- [cuisine] le-k2-palace — 2 venue(s) — "Creative"→"Créative", "Peruvian"→"Péruvienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"Le Sarkara","type_en":"Creative","type_fr":"Créative","michelin_stars":2},{"name":"L''Altiplano au K2 Palace","type_en":"Peruvian","type_fr":"Péruvienne"},{"name":"Bottleneck","type_en":"Restaurant","type_fr":"Restaurant"}]'::jsonb)
where slug = 'le-k2-palace';

-- [cuisine] le-royal-monceau-raffles-paris — 2 venue(s) — "Peruvian-Japanese"→"Péruvienne-japonaise", "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Hideki","name":"Matsuhisa Paris","type_en":"Peruvian-Japanese","type_fr":"Péruvienne-japonaise"},{"chef":"Oliver Piras and Alessandra Del Favero","name":"Il Carpaccio","type_en":"Italian","type_fr":"Italienne","michelin_stars":1}]'::jsonb)
where slug = 'le-royal-monceau-raffles-paris';

-- [cuisine] les-airelles-courchevel — 1 venue(s) — "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Adrien Trouilloud","name":"La Table des Airelles","type_en":"French","type_fr":"Française","michelin_stars":1},{"name":"L''Altitude","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1},{"chef":"Sébastien Vauxion","name":"Sarkara","type_en":"Desserts","type_fr":"Desserts","michelin_stars":2}]'::jsonb)
where slug = 'les-airelles-courchevel';

-- [cuisine] les-airelles-gordes — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Italian"→"Italienne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Table de La Bastide","type_en":"Modern Cuisine","type_fr":"Cuisine moderne"},{"chef":"Jean-François Piège","name":"Clover Gordes","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":1},{"name":"Ladurée","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Bastide de Pierres","type_en":"Italian","type_fr":"Italienne"},{"name":"Beefbar","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Pierre Marty","name":"The Kitchen Garden Table","type_en":"Restaurant","type_fr":"Restaurant"}]'::jsonb)
where slug = 'les-airelles-gordes';

-- [cuisine] les-airelles-saint-tropez — 3 venue(s) — "Japanese and Peruvian"→"Japonaise et péruvienne", "Mediterranean"→"Méditerranéenne", "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Nobuyuki ‘Nobu’ Matsuhisa","name":"Matsuhisa Saint-Tropez","type_en":"Japanese and Peruvian","type_fr":"Japonaise et péruvienne"},{"name":"Le restaurant des Trois Saisons","type_en":"Méditerranéenne","type_fr":"Méditerranéenne"},{"chef":"Franck-Louis Broc","name":"Les Trois Saisons","type_en":"Mediterranean","type_fr":"Méditerranéenne"},{"name":"Trois Saisons","type_en":"Mediterranean","type_fr":"Méditerranéenne"}]'::jsonb)
where slug = 'les-airelles-saint-tropez';

-- [cuisine] les-sources-de-caudalie — 2 venue(s) — "Modern Cuisine"→"Cuisine moderne", "Traditional Cuisine"→"Cuisine traditionnelle"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Nicolas Masse","name":"La Grand''Vigne","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":2},{"name":"La Table du Lavoir","type_en":"Traditional Cuisine","type_fr":"Cuisine traditionnelle"}]'::jsonb)
where slug = 'les-sources-de-caudalie';

-- [cuisine] les-sources-de-vougeot — 4 venue(s) — "Burgundy"→"Bourguignonne", "Burgundian"→"Bourguignonne", "French"→"Française", "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Julien Martin","name":"Le Clos de la Tour","type_en":"Burgundy","type_fr":"Bourguignonne"},{"chef":"Julien Martin","name":"L’Auberge des Cîteaux","type_en":"Burgundian","type_fr":"Bourguignonne"},{"name":"Auberge des Cîteaux","type_en":"French","type_fr":"Française"},{"name":"Clos de la Tour","type_en":"French","type_fr":"Française"}]'::jsonb)
where slug = 'les-sources-de-vougeot';

-- [cuisine] lesquisse-hotel-spa — 1 venue(s) — "Creative"→"Créative"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"JY''s","type_en":"Creative","type_fr":"Créative","michelin_stars":2}]'::jsonb)
where slug = 'lesquisse-hotel-spa';

-- [cuisine] mandarin-oriental-paris — 2 venue(s) — "French gastronomic tradition"→"Tradition gastronomique française", "Mediterranean"→"Méditerranéenne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Nina Haradji","name":"Camélia","type_en":"French gastronomic tradition","type_fr":"Tradition gastronomique française"},{"chef":"Florent Pietravalle","name":"Lutetia pop-up","type_en":"Mediterranean","type_fr":"Méditerranéenne","michelin_stars":1},{"chef":"Thierry Marx","name":"Sur Mesure","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":2},{"chef":"Thierry Marx","name":"Sur Mesure by Thierry Marx","type_en":"Restaurant","type_fr":"Restaurant","michelin_stars":2}]'::jsonb)
where slug = 'mandarin-oriental-paris';

-- [cuisine] plaza-athenee-paris — 2 venue(s) — "Classic Cuisine"→"Cuisine classique", "Classic Cuisine"→"Cuisine classique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Jean Imbert","name":"Jean Imbert au Plaza Athénée","type_en":"Classic Cuisine","type_fr":"Cuisine classique","michelin_stars":1},{"name":"Le Relais Plaza","type_en":"Classic Cuisine","type_fr":"Cuisine classique"},{"name":"La Galerie","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Cour Jardin","type_en":"Restaurant","type_fr":"Restaurant"},{"name":"La Terrasse Montaigne","type_en":"Restaurant","type_fr":"Restaurant"}]'::jsonb)
where slug = 'plaza-athenee-paris';

-- [cuisine] prince-de-galles-paris — 1 venue(s) — "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Norbert Tarayre","name":"19.20 by Norbert Tarayre","type_en":"Restaurant","type_fr":"Restaurant"},{"chef":"Stéphanie Le Quellec","name":"La Scène","type_en":"French","type_fr":"Française","michelin_stars":2}]'::jsonb)
where slug = 'prince-de-galles-paris';

-- [cuisine] shangri-la-paris — 2 venue(s) — "Chinese"→"Chinoise", "French, Asian"→"Française et asiatique"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Tony Xu","name":"Shang Palace","type_en":"Chinese","type_fr":"Chinoise","michelin_stars":1},{"chef":"Simon Havage, Timothy Lam","name":"La Bauhinia","type_en":"French, Asian","type_fr":"Française et asiatique"}]'::jsonb)
where slug = 'shangri-la-paris';

-- [cuisine] sofitel-quiberon-thalassa-sea-spa — 1 venue(s) — "French"→"Française"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"name":"La Presqu''île","type_en":"French","type_fr":"Française"}]'::jsonb)
where slug = 'sofitel-quiberon-thalassa-sea-spa';

-- [cuisine] villa-la-coste — 1 venue(s) — "Modern Cuisine"→"Cuisine moderne"
update public.hotels
set restaurant_info = jsonb_set(restaurant_info, '{venues}', '[{"chef":"Francis Mallmann","name":"Francis Mallmann au Chteau La Coste","type_en":"Cuisine argentine","type_fr":"Cuisine argentine"},{"name":"La Table de l''Orangerie - Chteau de Fonscolombe","type_en":"Modern Cuisine","type_fr":"Cuisine moderne","michelin_stars":1},{"name":"Les Jardins","type_en":"light and refined cuisine","type_fr":"light and refined cuisine"},{"chef":"Florent Pietravalle","name":"Cuisine by Florent Pietravalle","type_en":"Restaurant","type_fr":"Restaurant"}]'::jsonb)
where slug = 'villa-la-coste';

-- [pets] 5-terres-hotel-spa-mgallery-by-sofitel — "Pets allowed on request. Charges may apply.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = '5-terres-hotel-spa-mgallery-by-sofitel';

-- [pets] auberge-des-templiers — "The property allows all pets. They are welcome at a charge o…" → "L'établissement accepte tous les animaux. Ils sont les bienv…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''établissement accepte tous les animaux. Ils sont les bienvenus sans frais supplémentaires, hors nourriture."'::jsonb)
where slug = 'auberge-des-templiers';

-- [pets] balthazar-hotel-spa — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'balthazar-hotel-spa';

-- [pets] bulgari-hotel-paris — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'bulgari-hotel-paris';

-- [pets] byblos-saint-tropez — "Pets are allowed. Charges may be applicable.…" → "Animaux acceptés. Un supplément peut s'appliquer.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés. Un supplément peut s''appliquer."'::jsonb)
where slug = 'byblos-saint-tropez';

-- [pets] chateau-de-l-ile-spa-strasbourg — "Pets are allowed. Charges may be applicable.…" → "Animaux acceptés. Un supplément peut s'appliquer.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés. Un supplément peut s''appliquer."'::jsonb)
where slug = 'chateau-de-l-ile-spa-strasbourg';

-- [pets] chateau-saint-martin-vence — "Unfortunately, pets are not allowed within the property.…" → "Malheureusement, les animaux ne sont pas autorisés dans l'ét…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Malheureusement, les animaux ne sont pas autorisés dans l''établissement."'::jsonb)
where slug = 'chateau-saint-martin-vence';

-- [pets] cheval-blanc-courchevel — "Additional Fee for Pets…" → "Supplément pour les animaux.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Supplément pour les animaux."'::jsonb)
where slug = 'cheval-blanc-courchevel';

-- [pets] cheval-blanc-paris — "Pets are allowed on request.…" → "Animaux acceptés sur demande.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande."'::jsonb)
where slug = 'cheval-blanc-paris';

-- [pets] cheval-blanc-st-barth — "Pets Allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'cheval-blanc-st-barth';

-- [pets] domaine-de-primard — "the place is also very pet friendly, staff will pour water i…" → "L'établissement accepte également les animaux. Le personnel …"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''établissement accepte également les animaux. Le personnel servira de l''eau dans des gamelles adaptées pour vos compagnons à quatre pattes."'::jsonb)
where slug = 'domaine-de-primard';

-- [pets] fouquets-courchevel — "Fouquet's Courchevel is a dog-friendly hotel, please enquire…" → "Fouquet's Courchevel est un hôtel accueillant les chiens. Ve…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Fouquet''s Courchevel est un hôtel accueillant les chiens. Veuillez vous renseigner pour plus d''informations si vous souhaitez amener votre animal."'::jsonb)
where slug = 'fouquets-courchevel';

-- [pets] grand-hotel-barriere-de-dinard — "Pets accepted (with supplement)…" → "Animaux acceptés (avec supplément)…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés (avec supplément)"'::jsonb)
where slug = 'grand-hotel-barriere-de-dinard';

-- [pets] grand-hotel-cap-ferrat — "the hotel offers personalized presents for pets, showing a h…" → "L'hôtel propose des cadeaux personnalisés pour les animaux, …"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''hôtel propose des cadeaux personnalisés pour les animaux, témoignant d''un haut niveau d''attention et de soin."'::jsonb)
where slug = 'grand-hotel-cap-ferrat';

-- [pets] grand-hotel-de-cala-rossa — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'grand-hotel-de-cala-rossa';

-- [pets] grand-hotel-la-cloche — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'grand-hotel-la-cloche';

-- [pets] hostellerie-cedre-spa-beaune — "Pet Friendly…" → "Animaux acceptés…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés"'::jsonb)
where slug = 'hostellerie-cedre-spa-beaune';

-- [pets] hostellerie-de-levernois — "The pet fee charged by the hotel will not exceed the amount …" → "Le supplément pour animaux facturé par l'hôtel ne dépassera …"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Le supplément pour animaux facturé par l''hôtel ne dépassera pas le montant indiqué sur votre confirmation de réservation BringFido."'::jsonb)
where slug = 'hostellerie-de-levernois';

-- [pets] hostellerie-du-moulin-des-oliviers — "small pet at extra charge…" → "Petit animal avec un supplément.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Petit animal avec un supplément."'::jsonb)
where slug = 'hostellerie-du-moulin-des-oliviers';

-- [pets] hostellerie-la-cheneaudiere-spa — "Dogs accepted : €50 /day/animal except in top-suites 'Les Ci…" → "Chiens acceptés : 50 €/jour/animal, sauf dans les suites sup…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Chiens acceptés : 50 €/jour/animal, sauf dans les suites supérieures ''Les Cimes'', ''Capucines'' et ''Costelle''."'::jsonb)
where slug = 'hostellerie-la-cheneaudiere-spa';

-- [pets] hotel-a-piattatella — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-a-piattatella';

-- [pets] hotel-a-speranza — "No pets allowed…" → "Aucun animal n'est autorisé.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Aucun animal n''est autorisé."'::jsonb)
where slug = 'hotel-a-speranza';

-- [pets] hotel-casa-paradisu — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-casa-paradisu';

-- [pets] hotel-casadelmar — "Pets not allowed. Service animals are exempt from fees/restr…" → "Animaux non autorisés. Les animaux d'assistance sont exempté…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux non autorisés. Les animaux d''assistance sont exemptés des frais et restrictions. Les animaux d''assistance sont autorisés."'::jsonb)
where slug = 'hotel-casadelmar';

-- [pets] hotel-castelbrac — "No pets allowed…" → "Aucun animal n'est autorisé.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Aucun animal n''est autorisé."'::jsonb)
where slug = 'hotel-castelbrac';

-- [pets] hotel-chateau-dartigny — "Yes, your four-legged friends are welcome (supplement of €20…" → "Oui, vos amis à quatre pattes sont les bienvenus. Un supplém…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Oui, vos amis à quatre pattes sont les bienvenus. Un supplément de 20 € par jour s''applique."'::jsonb)
where slug = 'hotel-chateau-dartigny';

-- [pets] hotel-chateau-sainte-sabine — "Pet friendly in at least one room, the restaurant and common…" → "Animaux acceptés dans au moins une chambre, le restaurant et…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés dans au moins une chambre, le restaurant et les espaces communs."'::jsonb)
where slug = 'hotel-chateau-sainte-sabine';

-- [pets] hotel-clos-vauban — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'hotel-clos-vauban';

-- [pets] hotel-como-le-montrachet — "the hotel is very pet-friendly and welcomes dogs, even in th…" → "L'hôtel accepte les animaux et accueille les chiens, même da…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''hôtel accepte les animaux et accueille les chiens, même dans le restaurant."'::jsonb)
where slug = 'hotel-como-le-montrachet';

-- [pets] hotel-corsica — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-corsica';

-- [pets] hotel-de-crillon-a-rosewood-hotel — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'hotel-de-crillon-a-rosewood-hotel';

-- [pets] hotel-de-la-ferme — "Pets are not allowed inside the houses, in the restaurants o…" → "Les animaux ne sont pas autorisés à l'intérieur des maisons,…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés à l''intérieur des maisons, dans les restaurants ou sur les plages. Sinon, votre séjour sera annulé."'::jsonb)
where slug = 'hotel-de-la-ferme';

-- [pets] hotel-demeure-loredana — "Pets not allowed.…" → "Animaux non autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux non autorisés."'::jsonb)
where slug = 'hotel-demeure-loredana';

-- [pets] hotel-des-berges — "Pets are allowed. Charges may be applicable.…" → "Animaux acceptés. Un supplément peut s'appliquer.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-des-berges';

-- [pets] hotel-domaine-de-rymska — "Sorry, pets aren't allowed.…" → "Désolé, les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Désolé, les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-domaine-de-rymska';

-- [pets] hotel-don-cesar-spa — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-don-cesar-spa';

-- [pets] hotel-du-centre-nautique — "Free! Pets are allowed. No extra charges.…" → "Gratuit ! Animaux acceptés. Aucun supplément.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Gratuit ! Animaux acceptés. Aucun supplément."'::jsonb)
where slug = 'hotel-du-centre-nautique';

-- [pets] hotel-du-palais-biarritz — "Pet Friendly…" → "Animaux acceptés…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés"'::jsonb)
where slug = 'hotel-du-palais-biarritz';

-- [pets] hotel-fleur-de-loire — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'hotel-fleur-de-loire';

-- [pets] hotel-la-maison-des-tetes — "Pets are allowed. Charges may be applicable.…" → "Animaux acceptés. Un supplément peut s'appliquer.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-la-maison-des-tetes';

-- [pets] hotel-labbaye — "Animals accepted (supplement: 15€/day)…" → "Animaux acceptés (supplément : 15 €/jour).…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés (supplément : 15 €/jour)."'::jsonb)
where slug = 'hotel-labbaye';

-- [pets] hotel-lagnonu — "Pets are not permitted in this accommodation.…" → "Les animaux ne sont pas autorisés dans cet hébergement.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés dans cet hébergement."'::jsonb)
where slug = 'hotel-lagnonu';

-- [pets] hotel-le-cep — "Pets are allowed on request. Charges may be applicable.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-le-cep';

-- [pets] hotel-le-chateau-de-germigney — "Chateau De Germigney is pet friendly. Feel free to bring you…" → "Le Château De Germigney accepte les animaux. Vous pouvez ame…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Le Château De Germigney accepte les animaux. Vous pouvez amener votre animal de compagnie lors de votre séjour au Château De Germigney."'::jsonb)
where slug = 'hotel-le-chateau-de-germigney';

-- [pets] hotel-le-domaine-de-locguenole-spa — "Domaine de Locguénolé & Spa - Relais & Chateaux is a pet fri…" → "Le Domaine de Locguénolé & Spa - Relais & Châteaux accepte l…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Le Domaine de Locguénolé & Spa - Relais & Châteaux accepte les animaux."'::jsonb)
where slug = 'hotel-le-domaine-de-locguenole-spa';

-- [pets] hotel-le-domaine-des-hauts-de-loire — "Pets allowed on request. Charges may apply.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-le-domaine-des-hauts-de-loire';

-- [pets] hotel-le-manoir-les-minimes — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'hotel-le-manoir-les-minimes';

-- [pets] hotel-le-maquis — "Pets allowed…" → "Animaux acceptés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés."'::jsonb)
where slug = 'hotel-le-maquis';

-- [pets] hotel-le-relais-bernard-loiseau — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'hotel-le-relais-bernard-loiseau';

-- [pets] hotel-les-tresorieres — "Pets are allowed on request. Charges may be applicable.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-les-tresorieres';

-- [pets] hotel-maison-doucet — "Pets are not allowed in the restaurant.…" → "Les animaux ne sont pas autorisés dans le restaurant.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés dans le restaurant."'::jsonb)
where slug = 'hotel-maison-doucet';

-- [pets] hotel-marinca — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'hotel-marinca';

-- [pets] hotel-miramar-corsica — "Pets are allowed on request. Charges may be applicable.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-miramar-corsica';

-- [pets] hotel-restaurant-la-maison-zugno — "pets are not allowed and our establishment is an Adults Only…" → "Les animaux ne sont pas acceptés. Notre établissement est un…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas acceptés. Notre établissement est un hôtel réservé aux adultes, les mineurs ne sont pas autorisés."'::jsonb)
where slug = 'hotel-restaurant-la-maison-zugno';

-- [pets] hotel-sofitel-golfe-dajaccio — "Maximum number of pets per room 2. Only dogs and cats are al…" → "Nombre maximum d'animaux par chambre : 2. Seuls les chiens e…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Nombre maximum d''animaux par chambre : 2. Seuls les chiens et les chats sont autorisés. Les animaux d''assistance sont exemptés des frais et restrictions."'::jsonb)
where slug = 'hotel-sofitel-golfe-dajaccio';

-- [pets] hotel-spa-le-domaine-de-la-klauss — "Little animals (with supplement)…" → "Petits animaux (avec supplément)…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Petits animaux (avec supplément)"'::jsonb)
where slug = 'hotel-spa-le-domaine-de-la-klauss';

-- [pets] hotel-the-peninsula-paris — "Pets allowed on request. Charges may apply.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'hotel-the-peninsula-paris';

-- [pets] hotel-villa-maier — "Yes, cats and dogs are welcome. There's a charge of EUR 35 p…" → "Oui, les chats et les chiens sont les bienvenus. Un suppléme…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Oui, les chats et les chiens sont les bienvenus. Un supplément de 35 EUR par animal et par jour s''applique. Les animaux d''assistance sont exemptés des frais."'::jsonb)
where slug = 'hotel-villa-maier';

-- [pets] la-reserve-paris-hotel-and-spa — "Additional Fee for Pets…" → "Supplément pour les animaux.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Supplément pour les animaux."'::jsonb)
where slug = 'la-reserve-paris-hotel-and-spa';

-- [pets] lapogee-courchevel — "pets are not allowed on the property or its grounds.…" → "Les animaux ne sont pas autorisés sur la propriété ni dans s…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés sur la propriété ni dans ses espaces extérieurs."'::jsonb)
where slug = 'lapogee-courchevel';

-- [pets] le-bristol-paris — "We accept pet until 7 kg, but we are very flexible if the pe…" → "Nous acceptons les animaux jusqu'à 7 kg. Nous sommes cependa…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Nous acceptons les animaux jusqu''à 7 kg. Nous sommes cependant très flexibles si l''animal est bien éduqué."'::jsonb)
where slug = 'le-bristol-paris';

-- [pets] le-grand-hotel-des-thermes — "Pets are allowed on request.…" → "Animaux acceptés sur demande.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande."'::jsonb)
where slug = 'le-grand-hotel-des-thermes';

-- [pets] le-meurice — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'le-meurice';

-- [pets] les-airelles-courchevel — "Pets (includes VIP welcome)…" → "Animaux (comprend un accueil VIP)…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux (comprend un accueil VIP)"'::jsonb)
where slug = 'les-airelles-courchevel';

-- [pets] les-airelles-gordes — "Pets are allowed on request. Charges may be applicable.…" → "Animaux acceptés sur demande. Un supplément peut s'appliquer…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Animaux acceptés sur demande. Un supplément peut s''appliquer."'::jsonb)
where slug = 'les-airelles-gordes';

-- [pets] les-airelles-saint-tropez — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'les-airelles-saint-tropez';

-- [pets] les-sources-de-caudalie — "Pets must be kept on a leash and are not allowed near our po…" → "Les animaux doivent être tenus en laisse. Ils ne sont pas au…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux doivent être tenus en laisse. Ils ne sont pas autorisés près de nos piscines, au spa Vinothérapie, ni dans le restaurant étoilé Michelin La Grand’Vigne."'::jsonb)
where slug = 'les-sources-de-caudalie';

-- [pets] les-sources-de-vougeot — "The hotel is dog friendly; you can even dine with your four-…" → "L'hôtel accueille les chiens. Vous pouvez même dîner avec vo…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''hôtel accueille les chiens. Vous pouvez même dîner avec votre compagnon à quatre pattes dans l''auberge."'::jsonb)
where slug = 'les-sources-de-vougeot';

-- [pets] lesquisse-hotel-spa — "The property allows dogs or cats in guestrooms (size limitat…" → "L'établissement accepte les chiens ou les chats dans les cha…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"L''établissement accepte les chiens ou les chats dans les chambres. Des limitations de taille peuvent s''appliquer."'::jsonb)
where slug = 'lesquisse-hotel-spa';

-- [pets] mandarin-oriental-paris — "Mandarin Oriental Paris is a pet friendly hotel!…" → "Le Mandarin Oriental Paris est un hôtel qui accepte les anim…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Le Mandarin Oriental Paris est un hôtel qui accepte les animaux."'::jsonb)
where slug = 'mandarin-oriental-paris';

-- [pets] plaza-athenee-paris — "Pet amenities available…" → "Équipements pour animaux disponibles…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Équipements pour animaux disponibles"'::jsonb)
where slug = 'plaza-athenee-paris';

-- [pets] prince-de-galles-paris — "Pets are not allowed.…" → "Les animaux ne sont pas autorisés.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux ne sont pas autorisés."'::jsonb)
where slug = 'prince-de-galles-paris';

-- [pets] shangri-la-paris — "Only one pet up to 10 kg per room is allowed for no addition…" → "Un seul animal pesant jusqu'à 10 kg par chambre est autorisé…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Un seul animal pesant jusqu''à 10 kg par chambre est autorisé sans frais supplémentaires. Les animaux doivent être tenus en laisse courte et surveillés en tout temps dans les espaces communs. Ils doivent être portés dans un sac au bar ou au restaurant."'::jsonb)
where slug = 'shangri-la-paris';

-- [pets] sofitel-quiberon-thalassa-sea-spa — "Most house pets, such as dogs, are welcomed guests at Sofite…" → "La plupart des animaux de compagnie, comme les chiens, sont …"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"La plupart des animaux de compagnie, comme les chiens, sont des invités bienvenus au Sofitel Quiberon Thalassa Sea & Spa."'::jsonb)
where slug = 'sofitel-quiberon-thalassa-sea-spa';

-- [pets] villa-la-coste — "Pets are welcome at Villa La Coste.…" → "Les animaux sont les bienvenus à la Villa La Coste.…"
update public.hotels
set policies = jsonb_set(policies, '{pets,notes_fr}', '"Les animaux sont les bienvenus à la Villa La Coste."'::jsonb)
where slug = 'villa-la-coste';

insert into public._cct_sql_migrations (filename)
values ('0041_fr_residuals_translations.sql')
  on conflict do nothing;
