-- 0042 — Hotels: factual_summary (CDC §2.3, AEO).
--
-- Adds the bilingual `factual_summary_*` columns surfaced on the
-- hotel detail page right under the H1 + injected into the
-- `Hotel.description` JSON-LD as the canonical AI-ready summary.
--
-- Format expected (per CDC §2.3):
--   "[Type] [étoiles] situé [quartier/ville], à [distance] de [POI],
--    avec [3 USP]."
--   Length: 130-150 chars (lint-soft, no DB CHECK so legacy editorial
--   entries can be incrementally migrated).
--
-- Mirrors the pattern adopted for rankings in migration 0030. The
-- field is read by `apps/web/src/components/hotel/factual-summary.tsx`
-- and consumed as the source-of-truth `Hotel.description` value in
-- `packages/seo/src/jsonld/hotel.ts`.
--
-- Skill: geo-llm-optimization, structured-data-schema-org, content-modeling.

alter table public.hotels
  add column if not exists factual_summary_fr text,
  add column if not exists factual_summary_en text;

comment on column public.hotels.factual_summary_fr is
  'CDC §2.3 — IA-ready 130-150 chars summary surfaced under the H1 + injected '
  'into Hotel.description JSON-LD. Generated by the editorial pipeline; '
  'falls back to truncate(description_fr, 150) when null.';

comment on column public.hotels.factual_summary_en is
  'EN sibling of factual_summary_fr. Optional in V1; the page falls back to '
  'factual_summary_fr → description_en → description_fr when null.';

insert into public._cct_sql_migrations (filename)
values ('0042_hotels_factual_summary.sql')
  on conflict do nothing;
