-- 0057 — Le Concierge Club foundations.
--
-- Sprint 1 of the membership program (see plan
-- `.cursor/plans/le_cercle_membership_program_dc0717ed.plan.md`).
-- This migration is the **single forward-only DB change** for the
-- entire Phase 1 of Le Concierge Club. Everything that follows
-- (Stripe billing, Little API sync, member price differential) is
-- additive and ships in its own future migration in Phase 6.
--
-- What this migration does, in order:
--
--   1. Loyalty tier rename : `free → club`, `premium → prestige`.
--      The original 0001 migration used a CHECK constraint (not an
--      enum), so we drop+rewrite the constraint and UPDATE rows in
--      place. The 0003 `handle_new_auth_user` trigger is rewritten to
--      insert the new default `'club'`.
--
--   2. `loyalty_members` gains the Phase 6 billing columns up front
--      (trial_*, paid_until, stripe_*) so Sprint 1 code can reference
--      a stable shape and Phase 6 only needs to flip a feature flag
--      and wire the Stripe webhook — no migration churn.
--
--   3. New tables (all empty in Phase 1):
--        - `hotel_member_benefits`   — per-hotel benefit reality,
--          populated by the Little API sync in Phase 6 (source='little_api'),
--          or by addendum data (source='manual_addendum'). Phase 1
--          renders the maximalist catalogue client-side from a hardcoded
--          config; the table exists for forward compatibility.
--        - `member_price_differential` — price discount per hotel/room/
--          tier, populated by the Amadeus offer-time cron in Phase 6.
--        - `club_eligibility`        — opt-in flag per hotel for the
--          program, plus the addendum signed timestamp.
--        - `prestige_waitlist`       — anonymous + member email capture
--          before Prestige goes live in Phase 6.
--
--   4. `hotels` editorial columns for the 4 enriched concierge sections
--      shipped in Sprint 2 (conseil enrichi 200-300 mots, quartier,
--      gastronomie, timing/accès). Each carries an `_editorial_review_status`
--      so the back-office UX (Sprint 1 Payload work) can route drafts to
--      human fact-check before publish.
--
--   5. RLS + covering indexes for every FK + grants. The internal
--      `_cct_sql_migrations` log row at the end is mandatory per
--      `.cursor/rules/supabase-rls.mdc`.
--
-- Editorial review status convention:
--   * 'draft'    — generated by the LLM pipeline, awaiting human review
--   * 'pending'  — flagged for review by an editor (fact-check queue)
--   * 'approved' — human-validated, safe to render
--
-- Forward-only: do NOT edit this migration after it ships. If we need
-- to undo any of these changes, create a new 00NN_revert_<thing>.sql.

----------------------------------------------------------------
-- 1. loyalty_members — tier rename + billing columns
----------------------------------------------------------------

-- Drop the old check constraint and rewrite (the original 0001 used
-- a plain text + CHECK pattern, not a Postgres enum, so a simple
-- UPDATE + ALTER CONSTRAINT is enough).
alter table public.loyalty_members
  drop constraint if exists loyalty_members_tier_ck;

-- Rename in place. ON CONFLICT not needed (tier is non-unique).
update public.loyalty_members
   set tier = 'club'
 where tier = 'free';

update public.loyalty_members
   set tier = 'prestige'
 where tier = 'premium';

alter table public.loyalty_members
  alter column tier set default 'club',
  add constraint loyalty_members_tier_ck
    check (tier in ('club', 'prestige'));

-- Phase 6 billing columns — added now so Sprint 1 code typechecks
-- against the final shape. All nullable, no backfill needed.
alter table public.loyalty_members
  add column if not exists trial_started_at      timestamptz,
  add column if not exists trial_ends_at         timestamptz,
  add column if not exists paid_until            timestamptz,
  add column if not exists stripe_subscription_id text,
  add column if not exists stripe_customer_id    text,
  add column if not exists cancelled_at          timestamptz,
  add column if not exists cancellation_reason   text;

-- Covering indexes used by Phase 6 cron jobs (trial expiry, renewal).
create index if not exists loyalty_members_tier_idx
  on public.loyalty_members (tier);

create index if not exists loyalty_members_trial_ends_at_idx
  on public.loyalty_members (trial_ends_at)
  where trial_ends_at is not null;

create index if not exists loyalty_members_paid_until_idx
  on public.loyalty_members (paid_until)
  where paid_until is not null;

create unique index if not exists loyalty_members_stripe_subscription_id_uk
  on public.loyalty_members (stripe_subscription_id)
  where stripe_subscription_id is not null;

----------------------------------------------------------------
-- 2. Update the auto-create trigger to insert the new default tier
----------------------------------------------------------------

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_locale text;
  v_display text;
begin
  v_locale := coalesce(new.raw_user_meta_data ->> 'locale_pref', 'fr');
  if v_locale not in ('fr', 'en') then
    v_locale := 'fr';
  end if;

  v_display := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');

  insert into public.profiles (id, display_name, locale_pref, newsletter_opt_in)
  values (
    new.id,
    v_display,
    v_locale,
    coalesce((new.raw_user_meta_data ->> 'newsletter_opt_in')::boolean, false)
  )
  on conflict (id) do nothing;

  insert into public.loyalty_members (id, tier, total_bookings)
  values (new.id, 'club', 0)
  on conflict (id) do nothing;

  return new;
end;
$$;

-- SECURITY DEFINER hardening per .cursor/rules/supabase-rls.mdc.
revoke execute on function public.handle_new_auth_user() from public;
revoke execute on function public.handle_new_auth_user() from anon;
revoke execute on function public.handle_new_auth_user() from authenticated;

----------------------------------------------------------------
-- 3. hotel_member_benefits — per-hotel benefit reality
----------------------------------------------------------------
--
-- Phase 1 : empty. The <ClubBenefitsBlock> renders the maximalist
-- catalogue from a hardcoded client-side config.
-- Phase 6 : populated nightly by the Little API sync
-- (`packages/integrations/little-hotelier/sync/`), with addendum-only
-- entries for hotels that have a signed legal addendum (source='manual_addendum').

create table if not exists public.hotel_member_benefits (
  id           uuid primary key default gen_random_uuid(),
  hotel_id     uuid not null references public.hotels (id) on delete cascade,
  tier         text not null,
  benefit_code text not null,
  description_fr text,
  description_en text,
  is_subject_to_availability boolean not null default false,
  sort_order   integer not null default 100,
  source       text not null default 'default',
  valid_from   timestamptz,
  valid_until  timestamptz,
  created_at   timestamptz not null default timezone('utc', now()),
  updated_at   timestamptz not null default timezone('utc', now()),

  constraint hotel_member_benefits_tier_ck
    check (tier in ('club', 'prestige')),
  constraint hotel_member_benefits_source_ck
    check (source in ('default', 'manual_addendum', 'little_api')),
  constraint hotel_member_benefits_unique
    unique (hotel_id, tier, benefit_code)
);

create index if not exists hotel_member_benefits_hotel_id_idx
  on public.hotel_member_benefits (hotel_id);

create index if not exists hotel_member_benefits_tier_idx
  on public.hotel_member_benefits (tier);

create trigger hotel_member_benefits_set_updated_at
  before update on public.hotel_member_benefits
  for each row execute function public.set_updated_at();

----------------------------------------------------------------
-- 4. member_price_differential — empty Phase 1, wired Phase 6
----------------------------------------------------------------

create table if not exists public.member_price_differential (
  id           uuid primary key default gen_random_uuid(),
  hotel_id     uuid not null references public.hotels (id) on delete cascade,
  room_id      uuid references public.hotel_rooms (id) on delete cascade,
  tier         text not null,
  -- discount in basis points (e.g. 1000 = -10.00%). Avoid floats.
  discount_bps integer not null,
  -- absolute minimum member price in minor units (cents). Used to clamp
  -- the displayed differential when the upstream price is unusually low.
  min_price_minor integer,
  source       text not null default 'amadeus_offer',
  valid_from   timestamptz,
  valid_until  timestamptz,
  created_at   timestamptz not null default timezone('utc', now()),
  updated_at   timestamptz not null default timezone('utc', now()),

  constraint member_price_differential_tier_ck
    check (tier in ('club', 'prestige')),
  constraint member_price_differential_discount_ck
    check (discount_bps >= 0 and discount_bps <= 10000),
  constraint member_price_differential_source_ck
    check (source in ('amadeus_offer', 'little_api', 'manual'))
);

create index if not exists member_price_differential_hotel_id_idx
  on public.member_price_differential (hotel_id);

create index if not exists member_price_differential_room_id_idx
  on public.member_price_differential (room_id)
  where room_id is not null;

create index if not exists member_price_differential_tier_idx
  on public.member_price_differential (tier);

create trigger member_price_differential_set_updated_at
  before update on public.member_price_differential
  for each row execute function public.set_updated_at();

----------------------------------------------------------------
-- 5. club_eligibility — opt-in flag per hotel for the program
----------------------------------------------------------------

create table if not exists public.club_eligibility (
  hotel_id              uuid primary key references public.hotels (id) on delete cascade,
  is_eligible           boolean not null default false,
  addendum_signed_at    timestamptz,
  addendum_signed_by    text,
  notes                 text,
  created_at            timestamptz not null default timezone('utc', now()),
  updated_at            timestamptz not null default timezone('utc', now())
);

create index if not exists club_eligibility_is_eligible_idx
  on public.club_eligibility (is_eligible)
  where is_eligible = true;

create trigger club_eligibility_set_updated_at
  before update on public.club_eligibility
  for each row execute function public.set_updated_at();

----------------------------------------------------------------
-- 6. prestige_waitlist — email capture before Phase 6
----------------------------------------------------------------

create table if not exists public.prestige_waitlist (
  id          uuid primary key default gen_random_uuid(),
  email       text not null,
  user_id     uuid references auth.users (id) on delete set null,
  source      text,
  locale      text not null default 'fr',
  -- light marketing context — never PII beyond email
  utm_source  text,
  utm_medium  text,
  utm_campaign text,
  hotel_id    uuid references public.hotels (id) on delete set null,
  contacted_at timestamptz,
  created_at  timestamptz not null default timezone('utc', now()),

  constraint prestige_waitlist_locale_ck
    check (locale in ('fr', 'en', 'de', 'es', 'it')),
  constraint prestige_waitlist_email_unique
    unique (email)
);

create index if not exists prestige_waitlist_user_id_idx
  on public.prestige_waitlist (user_id)
  where user_id is not null;

create index if not exists prestige_waitlist_hotel_id_idx
  on public.prestige_waitlist (hotel_id)
  where hotel_id is not null;

create index if not exists prestige_waitlist_contacted_at_idx
  on public.prestige_waitlist (contacted_at)
  where contacted_at is null;

----------------------------------------------------------------
-- 7. hotels — 3 enriched editorial sections for Sprint 2 pipeline
----------------------------------------------------------------
--
-- The existing `concierge_advice` (migration 0032) is kept as-is — its
-- 50-110 word block becomes the "tip court". Sprint 2 will additionally
-- generate a 200-300 word "conseil enrichi" stored alongside, then 3
-- new long-form sections (quartier, gastronomie, timing/accès).
--
-- Shape per section (mirror of the future Zod schema):
--   {
--     fr: { title, body },
--     en: { title, body }
--   }
--
-- The `_editorial_review_status` companion column gates publish in the
-- Payload UI.

alter table public.hotels
  add column if not exists conseil_enrichi              jsonb,
  add column if not exists conseil_enrichi_generated_at timestamptz,
  add column if not exists conseil_enrichi_review_status text default 'draft',

  add column if not exists quartier_concierge           jsonb,
  add column if not exists quartier_concierge_generated_at timestamptz,
  add column if not exists quartier_concierge_review_status text default 'draft',

  add column if not exists gastronomie_concierge        jsonb,
  add column if not exists gastronomie_concierge_generated_at timestamptz,
  add column if not exists gastronomie_concierge_review_status text default 'draft',

  add column if not exists timing_acces_concierge       jsonb,
  add column if not exists timing_acces_concierge_generated_at timestamptz,
  add column if not exists timing_acces_concierge_review_status text default 'draft';

alter table public.hotels
  drop constraint if exists hotels_conseil_enrichi_review_ck;
alter table public.hotels
  add constraint hotels_conseil_enrichi_review_ck
    check (conseil_enrichi_review_status in ('draft', 'pending', 'approved'));

alter table public.hotels
  drop constraint if exists hotels_quartier_concierge_review_ck;
alter table public.hotels
  add constraint hotels_quartier_concierge_review_ck
    check (quartier_concierge_review_status in ('draft', 'pending', 'approved'));

alter table public.hotels
  drop constraint if exists hotels_gastronomie_concierge_review_ck;
alter table public.hotels
  add constraint hotels_gastronomie_concierge_review_ck
    check (gastronomie_concierge_review_status in ('draft', 'pending', 'approved'));

alter table public.hotels
  drop constraint if exists hotels_timing_acces_concierge_review_ck;
alter table public.hotels
  add constraint hotels_timing_acces_concierge_review_ck
    check (timing_acces_concierge_review_status in ('draft', 'pending', 'approved'));

-- Partial indexes for the editorial review queue (Sprint 2 back-office).
create index if not exists hotels_conseil_enrichi_pending_idx
  on public.hotels (id)
  where conseil_enrichi_review_status = 'pending';

create index if not exists hotels_quartier_pending_idx
  on public.hotels (id)
  where quartier_concierge_review_status = 'pending';

create index if not exists hotels_gastronomie_pending_idx
  on public.hotels (id)
  where gastronomie_concierge_review_status = 'pending';

create index if not exists hotels_timing_acces_pending_idx
  on public.hotels (id)
  where timing_acces_concierge_review_status = 'pending';

comment on column public.hotels.conseil_enrichi is
  'Conseil enrichi du Concierge (200-300 mots FR/EN, voix ADR-0011). Shape: {fr:{title,body}, en:{title,body}}. Generated by scripts/editorial-pilot/src/hotels/run-hotel-conseil-enrichi.ts in Sprint 2.';

comment on column public.hotels.quartier_concierge is
  'Section Quartier (200-300 mots FR/EN). Insider knowledge: best restaurants, hidden gems, walking radius. Generated by scripts/editorial-pilot/src/hotels/run-hotel-quartier.ts in Sprint 2.';

comment on column public.hotels.gastronomie_concierge is
  'Section Gastronomie (200-300 mots FR/EN). On-site dining + nearby curated picks, Michelin/Gault & Millau where relevant. Generated by scripts/editorial-pilot/src/hotels/run-hotel-gastronomie.ts in Sprint 2.';

comment on column public.hotels.timing_acces_concierge is
  'Section Timing & accès (150-200 mots FR/EN). Best months, airport routes, station distances, urban quirks. Generated by scripts/editorial-pilot/src/hotels/run-hotel-timing-acces.ts in Sprint 2.';

----------------------------------------------------------------
-- 8. RLS — every new table is opt-in to authenticated reads
----------------------------------------------------------------

alter table public.hotel_member_benefits enable row level security;
alter table public.member_price_differential enable row level security;
alter table public.club_eligibility enable row level security;
alter table public.prestige_waitlist enable row level security;

-- hotel_member_benefits : public read for authenticated (and we'll
-- expose a server-side function for anon if needed). Writes restricted
-- to operator + admin (Little API sync uses the service role).
create policy hotel_member_benefits_select
  on public.hotel_member_benefits
  for select
  to authenticated
  using (true);

create policy hotel_member_benefits_insert_staff
  on public.hotel_member_benefits
  for insert
  to authenticated
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy hotel_member_benefits_update_staff
  on public.hotel_member_benefits
  for update
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'))
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy hotel_member_benefits_delete_staff
  on public.hotel_member_benefits
  for delete
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

-- member_price_differential : authenticated reads only (we never expose
-- raw discount data to anon users — the price differential is rendered
-- server-side once the user is logged in).
create policy member_price_differential_select_authenticated
  on public.member_price_differential
  for select
  to authenticated
  using (true);

create policy member_price_differential_insert_staff
  on public.member_price_differential
  for insert
  to authenticated
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy member_price_differential_update_staff
  on public.member_price_differential
  for update
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'))
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy member_price_differential_delete_staff
  on public.member_price_differential
  for delete
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

-- club_eligibility : authenticated reads, staff writes.
create policy club_eligibility_select
  on public.club_eligibility
  for select
  to authenticated
  using (true);

create policy club_eligibility_insert_staff
  on public.club_eligibility
  for insert
  to authenticated
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy club_eligibility_update_staff
  on public.club_eligibility
  for update
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'))
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy club_eligibility_delete_staff
  on public.club_eligibility
  for delete
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

-- prestige_waitlist : insert is open to authenticated *and* anon
-- (the /api/club/waitlist API route is anonymous-friendly), reads/
-- updates limited to staff. The unique constraint on email handles
-- duplicates idempotently.
create policy prestige_waitlist_insert_anon
  on public.prestige_waitlist
  for insert
  to anon
  with check (true);

create policy prestige_waitlist_insert_authenticated
  on public.prestige_waitlist
  for insert
  to authenticated
  with check (true);

create policy prestige_waitlist_select_staff
  on public.prestige_waitlist
  for select
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy prestige_waitlist_update_staff
  on public.prestige_waitlist
  for update
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'))
  with check ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

create policy prestige_waitlist_delete_staff
  on public.prestige_waitlist
  for delete
  to authenticated
  using ((select auth.jwt() ->> 'role') in ('operator', 'admin'));

----------------------------------------------------------------
-- 9. Migration log entry (mandatory per supabase-rls.mdc)
----------------------------------------------------------------

insert into public._cct_sql_migrations (filename)
  values ('0057_loyalty_member_program.sql')
  on conflict do nothing;
