/**
 * Editorial destinations catalog — single source of truth for the
 * `/guide/[slug]` route surface. Each entry drives one `editorial_guides`
 * row in Supabase + one generated long-form article.
 *
 * Coverage: French luxury-travel hotspots that actually host one or
 * more Palaces in our catalog (so each guide can naturally cross-link
 * to fiches via `<RelatedHotels>` and emit an `ItemList[Hotel]` JSON-LD
 * graph). Adding a destination here MUST be paired with at least one
 * published `hotels` row mapping to the same city / cluster.
 *
 * The `keywords` field feeds the IA prompts so the editorial copy
 * captures domain-specific facts (architects, palaces, gastronomic
 * heritage) — never a generic Wikipedia summary.
 */

export type GuideScope = 'city' | 'cluster' | 'region' | 'country';

export interface DestinationGuideSeed {
  /** URL slug — kebab-case ASCII, stable. */
  readonly slug: string;
  /** Display name FR. */
  readonly nameFr: string;
  /** Display name EN. */
  readonly nameEn: string;
  /** Editorial scope (drives the JSON-LD shape). */
  readonly scope: GuideScope;
  /** ISO 3166-1 alpha-2 country code. */
  readonly countryCode: string;
  /** Matching `hotels.city` values (case-insensitive) for cross-link. */
  readonly hotelCityKeys: readonly string[];
  /** Editorial keywords / facts the AI MUST anchor (palaces, history, gastronomy). */
  readonly keywordsFr: readonly string[];
  /** Editorial keywords / facts the AI MUST anchor (EN locale). */
  readonly keywordsEn: readonly string[];
  /** One-line "tone" hint for the AI ("intemporel", "alpin", "balnéaire"). */
  readonly toneFr: string;
  /** Optional Cloudinary hero `public_id` already curated by editorial. */
  readonly heroImage?: string;
}

export const DESTINATIONS: readonly DestinationGuideSeed[] = [
  // ── Paris ─────────────────────────────────────────────────────────────────
  {
    slug: 'paris',
    nameFr: 'Paris',
    nameEn: 'Paris',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['paris'],
    keywordsFr: [
      'Palaces parisiens Atout France',
      'Plaza Athénée, Le Bristol, Le Meurice, Ritz, Crillon, Cheval Blanc, George V, Lutetia, Mandarin Oriental',
      "Triangle d'or — Avenue Montaigne, rue Saint-Honoré, Champs-Élysées",
      'Rive gauche : Saint-Germain-des-Prés, Lutetia, Le Pavillon de la Reine',
      'Gastronomie : Alléno, Ducasse, Anne-Sophie Pic, Cyril Lignac',
      'Musées : Louvre, Orsay, Orangerie, Picasso, Rodin',
      "Saisons : Fashion Weeks, Roland-Garros, Salon de l'Aéronautique",
      'Aéroports : CDG (32 km), Orly (18 km), Le Bourget (jet privé)',
    ],
    keywordsEn: [
      'Parisian Palaces awarded by Atout France',
      'Plaza Athénée, Le Bristol, Le Meurice, Ritz, Crillon, Cheval Blanc Paris',
      'Golden Triangle: Avenue Montaigne, Rue Saint-Honoré, Champs-Élysées',
      'Left Bank: Saint-Germain-des-Prés, Lutetia',
      'Gastronomy: Alléno, Ducasse, Pic, Lignac',
      'Museums: Louvre, Orsay, Orangerie, Picasso, Rodin',
    ],
    toneFr: 'intemporel, élégant, parisien',
    heroImage: 'editorial/destinations/paris-hero',
  },

  // ── Côte d'Azur (cluster) ─────────────────────────────────────────────────
  {
    slug: 'cote-d-azur',
    nameFr: "Côte d'Azur",
    nameEn: 'French Riviera',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'cannes',
      'nice',
      'antibes',
      "cap d'antibes",
      'saint-jean-cap-ferrat',
      'cap-ferrat',
      'menton',
      'eze',
      'saint-tropez',
      'ramatuelle',
      'monaco',
      'monte-carlo',
      'beaulieu-sur-mer',
      'roquebrune-cap-martin',
    ],
    keywordsFr: [
      'Riviera française — de Saint-Tropez à Menton',
      'Palaces emblématiques : Hôtel du Cap-Eden-Roc, Grand-Hôtel du Cap-Ferrat, La Réserve Ramatuelle, Cheval Blanc Saint-Tropez, Le Negresco, Château Saint-Martin, Cap-Estel',
      'Climat méditerranéen — 300 jours de soleil',
      'Festival de Cannes (mai), Grand Prix de Monaco (mai), Yachting',
      "Gastronomie : Mauro Colagreco (Mirazur), Argilla, La Vague d'Or",
      "Aéroport : Nice-Côte d'Azur (NCE), héliport de Monaco",
    ],
    keywordsEn: [
      'French Riviera — from Saint-Tropez to Menton',
      'Iconic Palaces: Hôtel du Cap-Eden-Roc, Grand-Hôtel du Cap-Ferrat, La Réserve, Cheval Blanc Saint-Tropez',
      'Mediterranean climate — 300 sunny days',
      'Cannes Film Festival, Monaco Grand Prix, yachting',
      'Gastronomy: Mauro Colagreco (Mirazur)',
    ],
    toneFr: 'balnéaire, lumineux, méditerranéen',
    heroImage: 'editorial/destinations/cote-d-azur-hero',
  },

  // ── Alpes (cluster) ───────────────────────────────────────────────────────
  {
    slug: 'alpes',
    nameFr: 'Alpes françaises',
    nameEn: 'French Alps',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'courchevel',
      'megève',
      'megeve',
      "val d'isère",
      "val d'isere",
      'chamonix',
      'chamonix-mont-blanc',
      'tignes',
      'val thorens',
      "l'alpe d'huez",
      'avoriaz',
      'morzine',
    ],
    keywordsFr: [
      "Stations 5 étoiles — Courchevel 1850, Megève, Val d'Isère, Chamonix",
      'Palaces alpins : Les Airelles, Cheval Blanc Courchevel, Le K2 Palace, Six Senses Courchevel, Four Seasons Megève, Le Strato',
      'Domaine skiable des 3 Vallées (600 km de pistes)',
      'Ski-in / ski-out, hélicoptère privé, dameuse de nuit',
      'Gastronomie alpine : Le 1947 (Yannick Alléno, Cheval Blanc), Pierre Gagnaire',
      'Saisons : ski (décembre-avril), été montagne (juin-septembre)',
    ],
    keywordsEn: [
      "Five-star resorts: Courchevel 1850, Megève, Val d'Isère, Chamonix",
      'Alpine Palaces: Les Airelles, Cheval Blanc Courchevel, Le K2 Palace, Six Senses',
      '3 Valleys ski domain (600 km of slopes)',
      'Alpine gastronomy: Le 1947 (Yannick Alléno)',
    ],
    toneFr: 'alpin, sportif, exclusif',
    heroImage: 'editorial/destinations/alpes-hero',
  },

  // ── Courchevel (city) ─────────────────────────────────────────────────────
  {
    slug: 'courchevel',
    nameFr: 'Courchevel',
    nameEn: 'Courchevel',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['courchevel'],
    keywordsFr: [
      'Courchevel 1850 — station la plus prestigieuse des Alpes',
      "Palaces : Les Airelles, Cheval Blanc Courchevel, Le K2 Palace, Six Senses Courchevel, L'Apogée, Le Strato, Aman Le Mélézin",
      'Domaine skiable des 3 Vallées — 600 km, ski-in / ski-out',
      'Altiport (privatif), héliport, Genève à 2h en voiture',
      "Gastronomie : Le 1947 (Yannick Alléno), La Table de l'Hubert",
      'Saison : 15 décembre - 15 avril (hiver), été restreint',
    ],
    keywordsEn: [
      'Courchevel 1850 — most prestigious resort in the Alps',
      'Palaces: Les Airelles, Cheval Blanc Courchevel, Le K2 Palace',
      'Altiport, helipad, 2h from Geneva',
    ],
    toneFr: 'altitudes, raffiné, exclusivité absolue',
  },

  // ── Megève ────────────────────────────────────────────────────────────────
  {
    slug: 'megeve',
    nameFr: 'Megève',
    nameEn: 'Megève',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['megève', 'megeve'],
    keywordsFr: [
      'Megève — village 5* aux portes du Mont-Blanc',
      'Palaces : Four Seasons Megève, Le Fer à Cheval, Les Fermes de Marie',
      'Patrimoine Noémie de Rothschild — esprit village authentique',
      'Domaine Évasion Mont-Blanc — 445 km de pistes',
      'Aéroport de Genève (1h30)',
      "Gastronomie : La Table de l'Alpaga, 1920 (Edouard Loubet)",
    ],
    keywordsEn: [
      'Megève — 5-star village at the gates of Mont-Blanc',
      'Palaces: Four Seasons Megève, Le Fer à Cheval, Les Fermes de Marie',
      'Évasion Mont-Blanc ski domain (445 km)',
    ],
    toneFr: 'authentique, village, chaleureux',
  },

  // ── Cannes ────────────────────────────────────────────────────────────────
  {
    slug: 'cannes',
    nameFr: 'Cannes',
    nameEn: 'Cannes',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['cannes'],
    keywordsFr: [
      'Cannes — capitale du cinéma et des yachts',
      'Palaces : Carlton Cannes, Majestic Barrière, Martinez, JW Marriott',
      'Boulevard de la Croisette, Palais des Festivals',
      'Îles de Lérins (Sainte-Marguerite, Saint-Honorat)',
      'Festival de Cannes (mai), MIPIM, Cannes Lions',
      "Aéroport Nice-Côte d'Azur (30 min), héliport (15 min)",
    ],
    keywordsEn: [
      'Cannes — capital of cinema and yachts',
      'Palaces: Carlton, Majestic, Martinez, JW Marriott',
      'Croisette, Palais des Festivals, Lérins Islands',
    ],
    toneFr: 'cinématographique, méditerranéen, glamour',
  },

  // ── Saint-Tropez ──────────────────────────────────────────────────────────
  {
    slug: 'saint-tropez',
    nameFr: 'Saint-Tropez',
    nameEn: 'Saint-Tropez',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['saint-tropez', 'ramatuelle'],
    keywordsFr: [
      'Saint-Tropez — village mythique du golfe',
      'Palaces : Cheval Blanc Saint-Tropez (ex-Résidence de la Pinède), La Réserve Ramatuelle, Lou Pinet, Byblos',
      'Plages de Pampelonne — Club 55, Nikki Beach, La Plage des Jumeaux',
      'Citadelle, place des Lices, port',
      'Yachting, Voiles de Saint-Tropez (octobre)',
      'Aéroport Saint-Tropez La Môle (jet privé) ou Nice (1h30)',
    ],
    keywordsEn: [
      'Saint-Tropez — legendary village of the gulf',
      'Palaces: Cheval Blanc Saint-Tropez, La Réserve Ramatuelle, Byblos',
      'Pampelonne beaches: Club 55, Nikki Beach',
    ],
    toneFr: 'estival, festif, méditerranéen',
  },

  // ── Saint-Jean-Cap-Ferrat ─────────────────────────────────────────────────
  {
    slug: 'cap-ferrat',
    nameFr: 'Cap-Ferrat',
    nameEn: 'Cap-Ferrat',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['saint-jean-cap-ferrat', 'cap-ferrat'],
    keywordsFr: [
      "Saint-Jean-Cap-Ferrat — presqu'île la plus chère du monde",
      "Palaces : Grand-Hôtel du Cap-Ferrat (Four Seasons), Cap-Estel, La Voile d'Or",
      'Villa Ephrussi de Rothschild, Villa Santo Sospir',
      'Sentier des douaniers, plage de Passable',
      'Aéroport Nice (20 min), héliport Monaco (8 min)',
    ],
    keywordsEn: [
      'Saint-Jean-Cap-Ferrat — most expensive peninsula in the world',
      'Palaces: Grand-Hôtel du Cap-Ferrat (Four Seasons), Cap-Estel',
      'Villa Ephrussi de Rothschild',
    ],
    toneFr: 'serein, exclusif, intime',
  },

  // ── Cap d'Antibes ────────────────────────────────────────────────────────
  {
    slug: 'cap-d-antibes',
    nameFr: "Cap d'Antibes",
    nameEn: "Cap d'Antibes",
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ["cap d'antibes", 'cap-d-antibes', 'antibes'],
    keywordsFr: [
      "Cap d'Antibes — entre Cannes et Nice",
      'Palaces : Hôtel du Cap-Eden-Roc (1870)',
      'Plage de la Garoupe, Phare de la Garoupe',
      'Musée Picasso, Vieil Antibes, Port Vauban',
      "Aéroport Nice-Côte d'Azur (20 min)",
    ],
    keywordsEn: [
      "Cap d'Antibes — between Cannes and Nice",
      'Palace: Hôtel du Cap-Eden-Roc (1870)',
      'Musée Picasso, Old Antibes',
    ],
    toneFr: 'discret, prestigieux, intemporel',
  },

  // ── Biarritz ──────────────────────────────────────────────────────────────
  {
    slug: 'biarritz',
    nameFr: 'Biarritz',
    nameEn: 'Biarritz',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['biarritz'],
    keywordsFr: [
      'Biarritz — perle de la Côte basque',
      "Palace : Hôtel du Palais (1854, ancien palais d'été d'Eugénie de Montijo)",
      'Plages : Grande Plage, Plage Miramar, Côte des Basques',
      'Surf, golf, thalasso',
      'Pays basque, Bayonne, San Sebastián (45 min)',
      'Aéroport BIQ',
    ],
    keywordsEn: [
      'Biarritz — pearl of the Basque coast',
      'Palace: Hôtel du Palais (1854)',
      'Grande Plage, surf, thalasso',
    ],
    toneFr: 'atlantique, basque, raffiné',
  },

  // ── Bordeaux ──────────────────────────────────────────────────────────────
  {
    slug: 'bordeaux',
    nameFr: 'Bordeaux',
    nameEn: 'Bordeaux',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['bordeaux', 'martillac', 'saint-emilion', 'saint-émilion', 'pauillac'],
    keywordsFr: [
      'Bordeaux — capitale mondiale du vin (UNESCO)',
      'Palaces : Les Sources de Caudalie (Martillac), Château Hôtel Grand Barrail (Saint-Émilion), InterContinental Bordeaux',
      'Vignobles : Médoc, Saint-Émilion, Pessac-Léognan, Pomerol',
      "Cité du Vin, Place de la Bourse, Miroir d'Eau",
      'Châteaux : Margaux, Lafite Rothschild, Cheval Blanc',
      'Œnotourisme, vendanges (septembre-octobre)',
      'Aéroport BOD, TGV Paris (2h)',
    ],
    keywordsEn: [
      'Bordeaux — world wine capital (UNESCO)',
      'Palace: Les Sources de Caudalie (Martillac)',
      'Vineyards: Médoc, Saint-Émilion, Pessac-Léognan',
    ],
    toneFr: 'viticole, gastronomique, art de vivre',
  },

  // ── Reims / Champagne ─────────────────────────────────────────────────────
  {
    slug: 'reims-champagne',
    nameFr: 'Reims & Champagne',
    nameEn: 'Reims & Champagne',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: ['reims', 'épernay', 'epernay'],
    keywordsFr: [
      'Reims — cité des sacres, capitale du Champagne',
      'Palaces : Domaine Les Crayères (Reims), Royal Champagne (Champillon)',
      'Maisons : Pommery, Veuve Clicquot, Krug, Ruinart, Moët & Chandon, Dom Pérignon',
      'Cathédrale Notre-Dame de Reims (UNESCO), Palais du Tau',
      'Caves visitables, vendanges (septembre)',
      'TGV Paris (45 min)',
    ],
    keywordsEn: [
      'Reims — city of coronations, capital of Champagne',
      'Palaces: Domaine Les Crayères, Royal Champagne',
      'Maisons: Pommery, Veuve Clicquot, Krug, Moët & Chandon',
    ],
    toneFr: 'effervescent, royal, gastronomique',
  },

  // ── Provence ──────────────────────────────────────────────────────────────
  {
    slug: 'provence',
    nameFr: 'Provence',
    nameEn: 'Provence',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'le puy-sainte-réparade',
      'le puy sainte réparade',
      'gordes',
      'lourmarin',
      'ménerbes',
      'menerbes',
    ],
    keywordsFr: [
      'Provence — Luberon, Alpilles, plateau de Valensole',
      'Palaces : Villa La Coste (Le Puy-Sainte-Réparade), La Coquillade Provence Resort, Capelongue (Beaumes)',
      'Villages perchés : Gordes, Roussillon, Bonnieux, Lourmarin',
      'Lavande (juillet-août), oliviers, marchés provençaux',
      "Festival d'Aix-en-Provence, vendanges",
      'Aéroport Marseille (1h), TGV Avignon',
    ],
    keywordsEn: [
      'Provence — Luberon, Alpilles, Valensole plateau',
      'Palaces: Villa La Coste, La Coquillade Provence Resort',
      'Hilltop villages: Gordes, Roussillon, Lourmarin',
    ],
    toneFr: 'rural, lumineux, art de vivre',
  },

  // ── Corse ─────────────────────────────────────────────────────────────────
  {
    slug: 'corse',
    nameFr: 'Corse',
    nameEn: 'Corsica',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: ['porto-vecchio', 'calvi', 'ajaccio', 'bonifacio'],
    keywordsFr: [
      'Corse — île de beauté, GR20, plages Lavezzi',
      'Adresses : Domaine de Murtoli, Cala Rossa (Porto-Vecchio), Casadelmar',
      'Bonifacio (falaises calcaires), Calvi (citadelle génoise), Ajaccio (Napoléon)',
      'Cuisine : charcuterie corse, brocciu, vins AOP, miel',
      'Aéroport Figari / Calvi / Ajaccio, ferry Marseille-Toulon-Nice',
    ],
    keywordsEn: [
      'Corsica — island of beauty, GR20 trail, Lavezzi beaches',
      'Domaine de Murtoli, Cala Rossa, Casadelmar',
      'Bonifacio cliffs, Calvi citadel, Ajaccio',
    ],
    toneFr: 'sauvage, méditerranéen, intemporel',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Sprint 6 — combler le delta Yonder : 16 nouvelles destinations FR
  // Couverture demandée pour aligner notre maillage interne (top-down)
  // avec celui des comparateurs éditoriaux (Yonder, Magazine du Voyageur).
  // ─────────────────────────────────────────────────────────────────────────

  // ── Deauville ─────────────────────────────────────────────────────────────
  {
    slug: 'deauville',
    nameFr: 'Deauville',
    nameEn: 'Deauville',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['deauville', 'trouville', 'trouville-sur-mer'],
    keywordsFr: [
      'Deauville — reine de la Côte Fleurie depuis 1860 (Duc de Morny)',
      'Adresses : Hôtel Barrière Le Normandy, Hôtel Barrière Le Royal, Les Manoirs de Tourgéville',
      'Planches, casino, hippodromes (La Touques, Clairefontaine)',
      'American Film Festival (septembre), Polo Gold Cup, Lancel Trophy',
      'Cinéma : Un homme et une femme (Lelouch), Coco Chanel',
      'Côte Fleurie : Honfleur, Trouville, Cabourg (Proust)',
      'Aéroport Deauville-Saint-Gatien, Paris (2h en voiture)',
    ],
    keywordsEn: [
      'Deauville — queen of the Côte Fleurie since 1860 (Duke of Morny)',
      'Hôtel Barrière Le Normandy, Hôtel Barrière Le Royal',
      'Boardwalks, casino, racecourses, American Film Festival',
    ],
    toneFr: 'normand, équestre, chic balnéaire',
  },

  // ── Marseille ─────────────────────────────────────────────────────────────
  {
    slug: 'marseille',
    nameFr: 'Marseille',
    nameEn: 'Marseille',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['marseille', 'cassis'],
    keywordsFr: [
      'Marseille — plus ancienne ville de France (Phocée, 600 av. J.-C.)',
      'Adresses : InterContinental Hôtel-Dieu, Sofitel Vieux-Port, NH Collection Marseille, C2 Hotel, Les Bords de Mer',
      'Vieux-Port, MUCEM, Notre-Dame de la Garde, Le Panier',
      'Calanques : Sormiou, Morgiou, En-Vau, Cassis',
      'Gastronomie : bouillabaisse, Gérald Passédat (Le Petit Nice ***), AM par Alexandre Mazzia ***',
      "Îles du Frioul, Château d'If",
      'Aéroport Marseille-Provence, TGV Paris (3h)',
    ],
    keywordsEn: [
      'Marseille — oldest city in France (600 BC)',
      'InterContinental Hôtel-Dieu, Sofitel Vieux-Port',
      'Vieux-Port, MUCEM, Notre-Dame de la Garde, Calanques',
    ],
    toneFr: 'méditerranéen, phocéen, authentique',
  },

  // ── Lyon ──────────────────────────────────────────────────────────────────
  {
    slug: 'lyon',
    nameFr: 'Lyon',
    nameEn: 'Lyon',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['lyon'],
    keywordsFr: [
      'Lyon — capitale mondiale de la gastronomie (Curnonsky, 1935)',
      'Adresses : InterContinental Lyon Hôtel-Dieu, Villa Maïa, Cour des Loges, Sofitel Bellecour',
      "Vieux Lyon (UNESCO), traboules, Croix-Rousse, presqu'île",
      'Gastronomie : Paul Bocuse ***, Mère Brazier **, Têtedoie *, bouchons lyonnais',
      'Fête des Lumières (8 décembre), Quais du Polar',
      'Vignobles : Beaujolais, Côtes-du-Rhône (Côte-Rôtie, Condrieu)',
      'Aéroport Saint-Exupéry, TGV Paris (2h)',
    ],
    keywordsEn: [
      'Lyon — world gastronomy capital (Curnonsky, 1935)',
      'InterContinental Lyon Hôtel-Dieu, Villa Maïa, Cour des Loges',
      'Old Lyon (UNESCO), traboules, Paul Bocuse',
    ],
    toneFr: 'gastronomique, soyeux, historique',
  },

  // ── Aix-en-Provence ──────────────────────────────────────────────────────
  {
    slug: 'aix-en-provence',
    nameFr: 'Aix-en-Provence',
    nameEn: 'Aix-en-Provence',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['aix-en-provence'],
    keywordsFr: [
      'Aix-en-Provence — ville de Cézanne, capitale historique de la Provence',
      'Adresses : Villa Gallici, Hôtel Renoir, Le Pigonnet, La Bastide de Tourtour, Château de la Gaude',
      'Cours Mirabeau, atelier Cézanne, fondation Vasarely, hôtels particuliers XVIIIᵉ',
      "Festival d'Art Lyrique (juillet), marché provençal",
      'Montagne Sainte-Victoire (peinte 87 fois par Cézanne)',
      "Vignobles Coteaux d'Aix, Cassis, Bandol à proximité",
      'Aéroport Marseille-Provence (30 min), TGV Aix (3h Paris)',
    ],
    keywordsEn: [
      "Aix-en-Provence — Cézanne's city, historic Provençal capital",
      'Villa Gallici, Le Pigonnet, Château de la Gaude',
      "Cours Mirabeau, Cézanne studio, Festival d'Art Lyrique",
    ],
    toneFr: 'cézannien, provençal, raffiné',
  },

  // ── Arles ─────────────────────────────────────────────────────────────────
  {
    slug: 'arles',
    nameFr: 'Arles',
    nameEn: 'Arles',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['arles', 'le paradou', 'paradou'],
    keywordsFr: [
      'Arles — ville romaine UNESCO, ville de Van Gogh (200 toiles)',
      "Adresses : L'Hôtel Particulier, Le Cloître, Hôtel Jules César MGallery, Le Mas de Peint",
      'Arènes romaines, théâtre antique, Cryptoportiques, Alyscamps',
      'Rencontres de la Photographie (juillet), LUMA Arles (Frank Gehry, 2021)',
      'Camargue : manades, flamants roses, Parc Naturel Régional',
      'Vignobles : Costières de Nîmes, Côtes du Rhône méridionales',
      'TGV Avignon ou Aix (15-25 min), aéroport Marseille (1h)',
    ],
    keywordsEn: [
      "Arles — Roman UNESCO city, Van Gogh's city",
      "L'Hôtel Particulier, Hôtel Jules César MGallery",
      'Roman amphitheatre, Rencontres de la Photographie, LUMA Arles',
    ],
    toneFr: 'romain, artistique, camarguais',
  },

  // ── Dinard ────────────────────────────────────────────────────────────────
  {
    slug: 'dinard',
    nameFr: 'Dinard',
    nameEn: 'Dinard',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['dinard'],
    keywordsFr: [
      "Dinard — station Belle Époque, élue 'Nice du Nord' (XIXᵉ)",
      'Adresses : Grand Hôtel Barrière de Dinard, Hôtel Castelbrac (ex-Musée de la Mer)',
      'Villas Belle Époque (407 répertoriées), Pointe du Moulinet',
      'Festival du Film Britannique (octobre), Coupes Internationales de Pétanque',
      'Plages : Écluse, Saint-Énogat, Prieuré',
      'Saint-Malo (15 min en navette maritime), Cap Fréhel, Cancale',
      'Aéroport Dinard-Pleurtuit-Saint-Malo, TGV Saint-Malo (2h15 Paris)',
    ],
    keywordsEn: [
      'Dinard — Belle Époque resort, "Nice of the North"',
      'Grand Hôtel Barrière de Dinard, Hôtel Castelbrac',
      'Belle Époque villas, Pointe du Moulinet, Saint-Malo',
    ],
    toneFr: 'belle époque, balnéaire, britannique',
  },

  // ── La Baule ──────────────────────────────────────────────────────────────
  {
    slug: 'la-baule',
    nameFr: 'La Baule',
    nameEn: 'La Baule',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['la baule', 'la-baule', 'la baule-escoublac'],
    keywordsFr: [
      "La Baule — plus belle baie d'Europe selon le Club des Plus Belles Baies du Monde",
      "Adresses : Hôtel Barrière Le Royal La Baule, Hôtel Barrière L'Hermitage, Castel Marie-Louise",
      'Plage de sable fin (9 km), villas Belle Époque, casino',
      'Golf international de La Baule, hippodrome, thalasso',
      'Parc Naturel Régional de Brière (zone humide), Guérande (sel)',
      'Saint-Nazaire (chantiers Atlantique), Nantes (45 min)',
      'TGV Paris (3h), aéroport Nantes-Atlantique (1h)',
    ],
    keywordsEn: [
      "La Baule — Europe's finest bay (Club des Plus Belles Baies)",
      "Hôtel Barrière Le Royal, Hôtel Barrière L'Hermitage, Castel Marie-Louise",
      'Belle Époque villas, golf, thalasso, Briere wetlands',
    ],
    toneFr: 'atlantique, balnéaire, élégant',
  },

  // ── Saint-Rémy-de-Provence ───────────────────────────────────────────────
  {
    slug: 'saint-remy-de-provence',
    nameFr: 'Saint-Rémy-de-Provence',
    nameEn: 'Saint-Rémy-de-Provence',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['saint-rémy-de-provence', 'saint-remy-de-provence', 'maussane'],
    keywordsFr: [
      "Saint-Rémy — village d'Alpilles, lieu d'asile de Van Gogh (1889-1890)",
      "Adresses : Hôtel de Tourrel, Le Vallon de Valrugues, Château des Alpilles, Hôtel L'Image",
      'Saint-Paul-de-Mausole (cloître où séjourna Van Gogh)',
      'Glanum (cité gallo-romaine), Mausolée et Arc municipal',
      "Marché du mercredi (l'un des plus beaux de Provence), oliviers AOP",
      'Les Baux-de-Provence (Carrières de Lumières), Mausanne, Maussane',
      'TGV Avignon (25 min), aéroport Marseille-Provence (1h)',
    ],
    keywordsEn: [
      'Saint-Rémy — Alpilles village, Van Gogh asylum (1889-1890)',
      'Hôtel de Tourrel, Le Vallon de Valrugues, Château des Alpilles',
      'Saint-Paul-de-Mausole, Glanum Roman city, Les Baux-de-Provence',
    ],
    toneFr: 'alpilles, provençal, art de vivre',
  },

  // ── Bourgogne ────────────────────────────────────────────────────────────
  {
    slug: 'bourgogne',
    nameFr: 'Bourgogne',
    nameEn: 'Burgundy',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'beaune',
      'dijon',
      'gevrey-chambertin',
      'chassagne-montrachet',
      'puligny-montrachet',
      'levernois',
      'gilly-lès-cîteaux',
    ],
    keywordsFr: [
      'Bourgogne — Climats du vignoble UNESCO (2015), Grands Crus mondialement uniques',
      'Adresses : Hostellerie Cèdre & Spa Beaune, Hôtel le Cep, Les Sources de Cheverny, Domaine de Rymska, Levernois, Hôtel Como Le Montrachet',
      'Côte de Nuits (Romanée-Conti, Chambertin, Vougeot), Côte de Beaune (Montrachet, Corton)',
      'Hospices de Beaune (1443), Cité Internationale de la Gastronomie et du Vin (Dijon)',
      'Gastronomie : Bernard Loiseau ***, William Frachot (Hostellerie du Chapeau Rouge)',
      'Vendanges (septembre), Vente aux enchères des Hospices (3ᵉ dimanche novembre)',
      'TGV Dijon (1h35 Paris), aéroport Lyon (1h45)',
    ],
    keywordsEn: [
      'Burgundy — UNESCO Climats vineyard, unique Grands Crus',
      'Hostellerie Cèdre & Spa Beaune, Hôtel le Cep, Domaine de Rymska',
      'Côte de Nuits, Côte de Beaune, Hospices de Beaune, Bernard Loiseau',
    ],
    toneFr: 'viticole, climats, gastronomique',
  },

  // ── Bretagne ─────────────────────────────────────────────────────────────
  {
    slug: 'bretagne',
    nameFr: 'Bretagne',
    nameEn: 'Brittany',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'saint-malo',
      'dinard',
      'rennes',
      'quiberon',
      'arzon',
      'perros-guirec',
      'kervignac',
    ],
    keywordsFr: [
      'Bretagne — région maritime, 2 700 km de côtes, identité celtique',
      "Adresses : Sofitel Quiberon Thalassa Sea & Spa, Le Grand Hôtel des Thermes Saint-Malo, Hôtel Spa L'Agapa Perros-Guirec, Hôtel le Domaine de Locguénole & Spa",
      "Côte de Granit Rose (Perros-Guirec, Ploumanac'h), Cap Fréhel, Pointe du Raz",
      'Mont-Saint-Michel (Manche/Bretagne frontière), Saint-Malo (cité corsaire)',
      'Gastronomie : huîtres de Cancale, crêpes, beurre Bordier, cidre',
      'Festival Interceltique de Lorient (août), Tour de Bretagne',
      'TGV Rennes (1h30 Paris), aéroport Rennes / Brest / Nantes',
    ],
    keywordsEn: [
      'Brittany — maritime region, 2,700 km coastline, Celtic identity',
      "Sofitel Quiberon Thalassa, Le Grand Hôtel des Thermes Saint-Malo, L'Agapa Perros-Guirec",
      'Côte de Granit Rose, Cap Fréhel, Mont-Saint-Michel, Saint-Malo',
    ],
    toneFr: 'maritime, celtique, authentique',
  },

  // ── Normandie ────────────────────────────────────────────────────────────
  {
    slug: 'normandie',
    nameFr: 'Normandie',
    nameEn: 'Normandy',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: ['deauville', 'trouville', 'honfleur', 'cabourg', 'bayeux'],
    keywordsFr: [
      'Normandie — région impressionniste, plages du Débarquement, falaises',
      'Adresses : Hôtel Barrière Le Normandy Deauville, Hôtel Barrière Le Royal, Domaine de Primard',
      "Côte Fleurie (Deauville, Trouville, Honfleur, Cabourg), Côte d'Albâtre (Étretat)",
      'Plages du Débarquement (Omaha, Utah, Juno, Gold, Sword), Cimetière américain',
      'Mont-Saint-Michel (UNESCO), abbaye, baie',
      'Gastronomie : camembert, calvados, cidre, fruits de mer, agneau de pré-salé',
      'Festival du Cinéma Américain Deauville, Impressionnisme route',
    ],
    keywordsEn: [
      'Normandy — Impressionist region, D-Day beaches, cliffs',
      'Hôtel Barrière Le Normandy Deauville, Domaine de Primard',
      "Côte Fleurie, Côte d'Albâtre, D-Day beaches, Mont-Saint-Michel",
    ],
    toneFr: 'impressionniste, mémoriel, balnéaire',
  },

  // ── Châteaux de la Loire ─────────────────────────────────────────────────
  {
    slug: 'chateaux-de-la-loire',
    nameFr: 'Châteaux de la Loire',
    nameEn: 'Loire Valley Châteaux',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'amboise',
      'blois',
      'chenonceaux',
      'montbazon',
      'noizay',
      'onzain',
      'cheverny',
      'tours',
      'reugny',
    ],
    keywordsFr: [
      'Vallée de la Loire — Patrimoine mondial UNESCO (2000), 280 km de Sully à Chalonnes',
      "Adresses : Hôtel Fleur de Loire (Christophe Hay), Domaine des Hauts de Loire, Château d'Artigny, Auberge du Bon Laboureur, Les Sources de Cheverny, Château Louise de la Vallière",
      'Châteaux royaux : Chambord, Chenonceau, Amboise, Blois, Cheverny, Villandry, Azay-le-Rideau',
      'Vignobles : Vouvray, Chinon, Bourgueil, Sancerre, Sauvignon de Touraine',
      'Gastronomie : Christophe Hay (Fleur de Loire **), Bon Laboureur',
      'Loire à vélo (900 km), jardins de Villandry, Forteresse royale de Loches',
      'TGV Tours-Saint-Pierre-des-Corps (1h Paris), aéroport Tours',
    ],
    keywordsEn: [
      'Loire Valley — UNESCO World Heritage (2000), 280 km of châteaux',
      "Hôtel Fleur de Loire, Domaine des Hauts de Loire, Château d'Artigny",
      'Chambord, Chenonceau, Amboise, Blois, Cheverny, Villandry',
    ],
    toneFr: 'royal, fluvial, jardins',
  },

  // ── Vaucluse / Luberon ───────────────────────────────────────────────────
  {
    slug: 'luberon',
    nameFr: 'Luberon',
    nameEn: 'Luberon',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'gordes',
      'ménerbes',
      'menerbes',
      'bonnieux',
      'lourmarin',
      'isle-sur-la-sorgue',
    ],
    keywordsFr: [
      'Luberon — Parc Naturel Régional, plus beaux villages de France',
      'Adresses : Airelles Gordes La Bastide, La Coquillade Village, Capelongue Beaumier Bonnieux, Le Phébus & Spa',
      'Villages perchés : Gordes, Ménerbes, Bonnieux, Roussillon (ocres), Lacoste',
      'Abbaye de Sénanque (cisterciens, lavandes), Fontaine-de-Vaucluse',
      'Marchés provençaux : Isle-sur-la-Sorgue (antiquaires), Apt (samedi)',
      'Vignobles : Côtes du Luberon AOC, Ventoux',
      'TGV Avignon (40 min), aéroport Marseille-Provence (1h15)',
    ],
    keywordsEn: [
      'Luberon — Natural Regional Park, most beautiful villages of France',
      'Airelles Gordes La Bastide, La Coquillade, Capelongue Bonnieux',
      'Gordes, Ménerbes, Bonnieux, Roussillon, Sénanque Abbey',
    ],
    toneFr: 'provençal, lavandes, perché',
  },

  // ── Alsace ───────────────────────────────────────────────────────────────
  {
    slug: 'alsace',
    nameFr: 'Alsace',
    nameEn: 'Alsace',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'strasbourg',
      'colmar',
      'kaysersberg',
      'illhaeusern',
      'barr',
      'ostwald',
      'colroy-la-roche',
    ],
    keywordsFr: [
      'Alsace — région bilingue, route des vins (170 km, 67 villages viticoles)',
      "Adresses : Hôtel le Chambard (Olivier Nasti **), Auberge de l'Ill (Haeberlin ***), Hôtel des Berges, Maison des Têtes, Château de l'Île Strasbourg",
      'Strasbourg (UNESCO, Parlement européen), Colmar (Petite Venise, Schongauer)',
      'Route des Vins : Riesling, Gewürztraminer, Pinot Gris, Crémant',
      "Gastronomie : Auberge de l'Ill ***, Olivier Nasti **, choucroute, tarte flambée, Munster",
      'Marchés de Noël (Strasbourg, Colmar, Kaysersberg, Riquewihr)',
      'TGV Strasbourg (1h45 Paris), aéroport Strasbourg / Bâle-Mulhouse',
    ],
    keywordsEn: [
      'Alsace — bilingual region, Wine Route (170 km, 67 wine villages)',
      "Hôtel le Chambard (Olivier Nasti), Auberge de l'Ill (Haeberlin)",
      'Strasbourg, Colmar, Riesling, Christmas markets',
    ],
    toneFr: 'alsacien, viticole, mitteleuropa',
  },

  // ── Méribel ──────────────────────────────────────────────────────────────
  {
    slug: 'meribel',
    nameFr: 'Méribel',
    nameEn: 'Méribel',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['méribel', 'meribel', 'les allues'],
    keywordsFr: [
      'Méribel — station alpine du domaine des 3 Vallées (600 km de pistes)',
      'Adresses : Le Coucou Méribel (Maja Hoffmann), Le Kaïla, La Chaudanne, Allodis',
      'Architecture chalets traditionnels (Peter Lindsay, 1936 — fondateur britannique)',
      'Domaine skiable : Trois Vallées (Courchevel, Méribel, Val Thorens, Brides-les-Bains)',
      'Gastronomie : Le Cèpe Méribel, La Table du Coucou',
      'Saison hiver : décembre - avril, été : juin - août (rando, VTT)',
      'Aéroport Genève (2h30), Lyon (2h), Chambéry (1h45)',
    ],
    keywordsEn: [
      'Méribel — Alpine resort, Trois Vallées domain (600 km of slopes)',
      'Le Coucou Méribel (Maja Hoffmann), Le Kaïla, La Chaudanne',
      'British heritage (Peter Lindsay, 1936), Trois Vallées',
    ],
    toneFr: 'alpin, chalets, britannique',
  },

  // ── Annecy ───────────────────────────────────────────────────────────────
  {
    slug: 'annecy',
    nameFr: 'Annecy',
    nameEn: 'Annecy',
    scope: 'city',
    countryCode: 'FR',
    hotelCityKeys: ['annecy', 'talloires', 'veyrier-du-lac'],
    keywordsFr: [
      "Annecy — 'Venise des Alpes', lac le plus pur d'Europe (LCSQA)",
      "Adresses : Hôtel Black Bass, La Maison Bleue (Veyrier-du-Lac), Hôtel de l'Abbaye (Talloires), Hôtel Beauregard",
      "Vieille ville, Palais de l'Isle (XIIᵉ), Pont des Amours",
      'Lac (27 km de tour à vélo), plages de Saint-Jorioz, Doussard',
      'Gastronomie : Yoann Conte ** (Veyrier-du-Lac), Le Clos des Sens *** (Annecy-le-Vieux)',
      "Fête du Lac (premier samedi août), Festival International du Film d'Animation (juin)",
      'Aéroport Genève (45 min), Lyon (1h45), Chambéry (50 min)',
    ],
    keywordsEn: [
      'Annecy — "Venice of the Alps", purest lake in Europe',
      'Hôtel Black Bass, La Maison Bleue (Veyrier-du-Lac)',
      "Old town, Palais de l'Isle, Yoann Conte, Le Clos des Sens",
    ],
    toneFr: 'lacustre, alpin, romantique',
  },

  // ── Phase F seeds (May 2026) ─ Yonder-derived drafts ─────────────────────
  // Ten guide drafts scaffolded overnight in `editorial_guides`. Seeds added
  // here so `run-guides-v2.ts --all` can regenerate them. Several have zero
  // matching published hotels today — the `<RelatedHotels>` section will
  // render empty until the corresponding hotels publish, but the guide body,
  // FAQ and JSON-LD remain valuable for SEO and topic authority.

  {
    slug: 'pays-basque',
    nameFr: 'Pays Basque',
    nameEn: 'Basque Country',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'biarritz',
      'saint-jean-de-luz',
      'bayonne',
      'anglet',
      'bidart',
      'hendaye',
      'ciboure',
      'guéthary',
      'guethary',
      'ainhoa',
      'sare',
      'cambo-les-bains',
    ],
    keywordsFr: [
      'Pays Basque français — côte Labourd, montagne Soule, intérieur Basse-Navarre',
      'Adresses : Hôtel du Palais Biarritz (Hyatt — ancienne villa Eugénie 1855), Hôtel Régina Biarritz, Grand Hôtel Saint-Jean-de-Luz, Hôtel du Palais Saint-Jean-de-Luz, La Réserve Saint-Jean-de-Luz',
      "Surf : Côte des Basques (Biarritz), spot historique de l'Europe (1957), Grande Plage, Hossegor à 30 min",
      "Gastronomie : Brikéténia *, Briketenia (Guéthary), Argi Eder, Auberge Basque, piment d'Espelette AOP, jambon de Bayonne IGP",
      'Patrimoine : Villa Eugénie, Rocher de la Vierge, port de Saint-Jean-de-Luz (mariage de Louis XIV, 1660), maisons labourdines à colombages rouges',
      'Saisons : Biarritz Surf Festival (juillet), Fêtes de Bayonne (août, 1 M visiteurs), Big Wave Hossegor (octobre)',
      'Aéroport Biarritz-Pays Basque (BIQ, 7 km Biarritz), TGV Paris-Biarritz (4h, 2h Bordeaux)',
    ],
    keywordsEn: [
      'French Basque Country — Labourd coast, Soule mountains, Basse-Navarre inland',
      'Hôtel du Palais Biarritz (Hyatt, Empress Eugénie 1855), Grand Hôtel Saint-Jean-de-Luz',
      'Surf: Côte des Basques (Biarritz, 1957), gastronomy: Espelette pepper PDO, Bayonne ham PGI',
    ],
    toneFr: 'océanique, basque, élégance balnéaire',
  },

  {
    slug: 'sologne',
    nameFr: 'Sologne',
    nameEn: 'Sologne',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'cheverny',
      'chambord',
      'romorantin',
      'romorantin-lanthenay',
      'lamotte-beuvron',
      'salbris',
      'aubigny-sur-nère',
      'aubigny-sur-nere',
      'argent-sur-sauldre',
      'boismorand',
    ],
    keywordsFr: [
      'Sologne — 500 000 hectares de forêts, étangs et landes au sud de la Loire (Loir-et-Cher, Loiret, Cher)',
      'Adresses : Les Sources de Cheverny (Caudalie), Hôtel Grand Saint-Michel (Chambord), Domaine des Hauts de Loire, Auberge de la Croix Blanche',
      'Chasse présidentielle de Chambord (1948-2010, devenue gestion cynégétique), tradition de la chasse à courre, brame du cerf (septembre-octobre)',
      'Châteaux : Chambord (UNESCO, 440 pièces, escalier Léonard de Vinci), Cheverny (résidence Hurault depuis 6 siècles), Beauregard (galerie 327 portraits), Villesavin (1537)',
      'Gastronomie : tarte Tatin (créée à Lamotte-Beuvron 1898), gibier (sanglier, chevreuil, faisan), carpe de Sologne IGP, fromage Selles-sur-Cher AOP',
      "Activités : équitation, golf (Les Bordes 18 trous classé 1er d'Europe Continentale), randonnée (5 000 km de chemins balisés)",
      'Accès : 1h30-2h Paris (A10 / A71), aéroport Tours (TUF) ou Paris-Orly (ORY)',
    ],
    keywordsEn: [
      'Sologne — 500,000 hectares of forests, ponds and heaths south of the Loire',
      'Les Sources de Cheverny (Caudalie), Hôtel Grand Saint-Michel (Chambord)',
      'Châteaux: Chambord (UNESCO), Cheverny, Villesavin — hunting tradition, deer rutting season',
    ],
    toneFr: 'forestier, cynégétique, aristocratique',
  },

  {
    slug: 'sud-ouest',
    nameFr: 'Sud-Ouest',
    nameEn: 'South-West France',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'bordeaux',
      'saint-emilion',
      'saint-émilion',
      'martillac',
      'sauternes',
      'pauillac',
      'biarritz',
      'saint-jean-de-luz',
      'hossegor',
      'soorts-hossegor',
      'cognac',
      'eugénie-les-bains',
      'eugenie-les-bains',
      'mont-de-marsan',
      'pau',
      'dax',
    ],
    keywordsFr: [
      'Sud-Ouest — Gironde + Landes + Pyrénées-Atlantiques + Charente, climat océanique tempéré',
      "Adresses : Les Sources de Caudalie (Martillac, Mathilde Cathiard-Thomas), Hôtel du Palais Biarritz, Les Prés d'Eugénie (Michel Guérard ***), Château Cordeillan-Bages, La Co(o)rniche (Pyla)",
      'Vignobles : Bordeaux (1er vignoble AOC mondial), Saint-Émilion (UNESCO 1999), Médoc, Sauternes, Pessac-Léognan, Pomerol — 60 grands crus classés',
      "Gastronomie : foie gras IGP Sud-Ouest, magret, confit, canard, agneau de Pauillac, huîtres d'Arcachon, jambon de Bayonne, piment d'Espelette",
      'Surf : Hossegor (mondial), La Gravière, Plage Centrale Biarritz, océan Atlantique, dune du Pilat (110 m)',
      'Patrimoine : Bordeaux (UNESCO 2007), Cognac (maisons Hennessy / Martell / Rémy Martin), Saint-Émilion souterrain',
      'Accès : TGV Paris-Bordeaux 2h04, aéroports Bordeaux-Mérignac (BOD), Biarritz-Pays Basque (BIQ), Pau-Pyrénées (PUF)',
    ],
    keywordsEn: [
      'South-West France — Gironde, Landes, Pyrénées-Atlantiques, Charente',
      "Les Sources de Caudalie (Martillac), Les Prés d'Eugénie (Michel Guérard), Château Cordeillan-Bages",
      'Bordeaux vineyards (UNESCO), Saint-Émilion, surf at Hossegor / Biarritz, foie gras territory',
    ],
    toneFr: 'gourmand, vinicole, atlantique',
  },

  {
    slug: 'hauts-de-france',
    nameFr: 'Hauts-de-France',
    nameEn: 'Hauts-de-France',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'lille',
      'chantilly',
      'compiègne',
      'compiegne',
      'senlis',
      'amiens',
      'arras',
      'le touquet',
      'le touquet-paris-plage',
      'pierrefonds',
      'gerberoy',
    ],
    keywordsFr: [
      'Hauts-de-France — fusion 2016 Nord-Pas-de-Calais + Picardie, 6 M habitants, façade Manche',
      'Adresses : Auberge du Jeu de Paume (Chantilly, Oetker Collection), Westminster Le Touquet, Hôtel Hermitage Gantois Lille, La Cour Carrée (Senlis), Château de Montvillargenne',
      'Châteaux royaux : Chantilly (Musée Condé, 2ᵉ collection peintures anciennes après le Louvre), Compiègne (résidence Napoléon III), Pierrefonds (Viollet-le-Duc), Domaine de Chaalis',
      "Patrimoine : Cathédrale Notre-Dame d'Amiens (UNESCO, plus vaste de France), Vieux-Lille (Vieille Bourse 1653), Beffrois (UNESCO), citadelle Vauban d'Arras",
      'Gastronomie : maroilles, carbonade flamande, welsh, ficelle picarde, gaufres, bière artisanale (3 Brasseurs, Goudale), endives (Nord, 1ᵉʳ producteur Europe)',
      'Hippodrome de Chantilly (Prix de Diane, Prix du Jockey Club), Grandes Écuries (musée du Cheval), Le Touquet (golf, polo, racing)',
      'Accès : Eurostar Paris-Lille 1h, Paris-Chantilly 25 min (RER + TER), aéroport Lille-Lesquin (LIL)',
    ],
    keywordsEn: [
      'Hauts-de-France — northern region, English Channel coast',
      'Auberge du Jeu de Paume (Chantilly, Oetker Collection), Westminster Le Touquet',
      'Châteaux: Chantilly (Musée Condé), Compiègne, Pierrefonds — Amiens Cathedral (UNESCO)',
    ],
    toneFr: 'royal, équestre, septentrional',
  },

  {
    slug: 'occitanie',
    nameFr: 'Occitanie',
    nameEn: 'Occitanie',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'toulouse',
      'carcassonne',
      'albi',
      'narbonne',
      'perpignan',
      'sète',
      'sete',
      'collioure',
      'cordes-sur-ciel',
      'cahors',
      'montpellier',
      'nîmes',
      'nimes',
      'rocamadour',
      'lourdes',
      'saint-cirq-lapopie',
    ],
    keywordsFr: [
      'Occitanie — fusion 2016 Languedoc-Roussillon + Midi-Pyrénées, 6 M habitants, façade méditerranéenne',
      'Adresses : La Réserve Saint-Jean-de-Luz (proche frontière), Domaine de Verchant (Montpellier), Hôtel La Cité (Carcassonne), Le Château de la Treyne (Lacave)',
      'Patrimoine UNESCO : Cité de Carcassonne (Viollet-le-Duc), Canal du Midi (Riquet, 1681, 240 km), chemins de Saint-Jacques, Pont du Gard, citadelle de Mont-Louis (Vauban)',
      'Pays cathare : châteaux de Quéribus, Peyrepertuse, Puilaurens, Termes, Aguilar, Lastours — résistance albigeoise XIIIᵉ',
      'Gastronomie : cassoulet (Castelnaudary, Carcassonne, Toulouse — guerre triangulaire), foie gras du Sud-Ouest IGP, magret, vins de Languedoc (Pic Saint-Loup, Faugères, Minervois, Corbières)',
      'Pyrénées : Cirque de Gavarnie (UNESCO), Lourdes (sanctuaire marial, 6 M pèlerins/an), Pic du Midi (observatoire 2877 m), Andorre frontière',
      "Toulouse 'la Ville rose' (briques foraines), Airbus, Cité de l'Espace, basilique Saint-Sernin (plus grande romane d'Europe)",
    ],
    keywordsEn: [
      'Occitanie — southern region, Mediterranean and Pyrénées',
      'La Cité (Carcassonne), Domaine de Verchant (Montpellier), Château de la Treyne',
      'UNESCO Carcassonne, Canal du Midi, Pont du Gard — Cathar castles, cassoulet rivalries',
    ],
    toneFr: 'occitan, cathare, ensoleillé',
  },

  {
    slug: 'pays-de-la-loire',
    nameFr: 'Pays de la Loire',
    nameEn: 'Pays de la Loire',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'nantes',
      'la baule',
      'la baule-escoublac',
      'pornic',
      'le croisic',
      'piriac-sur-mer',
      'angers',
      'le mans',
      'saumur',
      'noirmoutier',
      'saint-jean-de-monts',
      'les sables-d-olonne',
      'sables-d-olonne',
    ],
    keywordsFr: [
      'Pays de la Loire — 5 départements (Loire-Atlantique, Maine-et-Loire, Mayenne, Sarthe, Vendée), façade atlantique',
      "Adresses : Hôtel Barrière L'Hermitage La Baule, Hôtel Royal-Thalasso Barrière La Baule, Hôtel de Loire (Angers), Domaine du Hézo, Hôtel Anne d'Anjou (Saumur)",
      "La Baule — plus belle baie d'Europe (Saint-Brévin à Le Croisic, 9 km de sable fin), thalasso pionnière (Barrière 1978), golf (3 parcours), tennis (futur Open féminin)",
      "Châteaux d'Anjou : Saumur (Apocalypse, 7 m de tapisserie), Brissac (plus haut de France), Angers (forteresse Capétienne, tenture de l'Apocalypse 104 m), Cunault",
      'Gastronomie : muscadet (sur lie, 13 000 ha), Anjou Coteaux du Layon, beurre blanc nantais, fouace, rillettes du Mans IGP, sel de Guérande IGP',
      "Patrimoine : Nantes (Machines de l'Île, château des Ducs), 24 Heures du Mans (juin, automobile), Vendée Globe (tous les 4 ans, départ Sables-d'Olonne)",
      'Accès : TGV Paris-Nantes 2h, Paris-Le Mans 55 min, aéroport Nantes Atlantique (NTE)',
    ],
    keywordsEn: [
      'Pays de la Loire — Atlantic coast, Anjou châteaux, Loire estuary',
      "Hôtel Barrière L'Hermitage La Baule, Royal-Thalasso Barrière",
      'La Baule beach, Angers / Saumur châteaux, 24 Hours of Le Mans, Vendée Globe',
    ],
    toneFr: 'atlantique, élégant, ligérien',
  },

  {
    slug: 'lac-leman',
    nameFr: 'Lac Léman',
    nameEn: 'Lake Geneva',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'évian-les-bains',
      'evian-les-bains',
      'évian',
      'evian',
      'thonon-les-bains',
      'yvoire',
      'amphion-les-bains',
      'publier',
    ],
    keywordsFr: [
      "Lac Léman — plus grand lac alpin d'Europe (582 km², 73 km de long), rive française du Chablais",
      'Adresses : Hôtel Royal Evian (Mauresque, 1909, Resort 5 étoiles), Hôtel Ermitage Evian (Belle Époque), Hilton Evian, La Verniaz et ses Chalets, Cottage Bise (Talloires côté français)',
      'Évian-les-Bains — eau minérale Evian (Source Cachat, embouteillée depuis 1859), thermes (Évian Resort), Casino Évian Palais Lumière',
      "Patrimoine : Yvoire (Plus Beau Village de France, médiéval XIVᵉ), Château de Ripaille (résidence du duc Amédée VIII de Savoie), villas Belle Époque d'Évian",
      'Activités : navigation lac (compagnie CGN, ferries Évian-Lausanne 35 min), golf Royal Évian (Evian Championship LPGA), thermes, Mont-Blanc en arrière-plan',
      'Gastronomie : féra du Léman, omble chevalier, perche meunière, vins de Savoie (Chignin, Roussette, Mondeuse), tomme des Bauges',
      'Accès : 1h Genève (GVA), 2h Lyon (LYS), Mont-Blanc à 1h, frontière suisse à Saint-Gingolph',
    ],
    keywordsEn: [
      'Lake Geneva — largest Alpine lake (582 km²), French Chablais shore',
      'Hôtel Royal Evian (1909), Ermitage Evian, La Verniaz et ses Chalets',
      'Evian mineral water source, Yvoire medieval village, Evian Championship LPGA',
    ],
    toneFr: 'lacustre, thermal, Belle Époque',
  },

  {
    slug: 'vexin',
    nameFr: 'Vexin Français',
    nameEn: 'French Vexin',
    scope: 'cluster',
    countryCode: 'FR',
    hotelCityKeys: [
      'giverny',
      'la roche-guyon',
      'vétheuil',
      'vetheuil',
      'magny-en-vexin',
      'auvers-sur-oise',
      "l'isle-adam",
      'isle-adam',
      'beauvais',
      'gerberoy',
    ],
    keywordsFr: [
      "Vexin Français — Parc Naturel Régional (1995, 71 000 ha), plateau calcaire entre Seine et Epte (Val-d'Oise + Yvelines)",
      "Adresses : Le Moulin de Fourges (Fourges, restaurant gastronomique), Domaine de Villiers (Saint-Jean-aux-Bois), Hôtel de la Chaîne d'Or (Les Andelys, vue Château-Gaillard)",
      'Giverny — Maison et jardins de Claude Monet (1883-1926, restaurés 1980), Musée des Impressionnismes (15 expositions), Bassin aux Nymphéas, pont japonais',
      'Auvers-sur-Oise — dernière demeure de Vincent Van Gogh (mai-juillet 1890, 70 toiles), Maison-Atelier de Daubigny, Auberge Ravoux (chambre Van Gogh préservée)',
      'Patrimoine : Château de La Roche-Guyon (donjon XIIᵉ, salle à manger Rochefoucauld), Abbaye de Royaumont, Gerberoy (Plus Beau Village de France, rosiers de Henri Le Sidaner)',
      'Activités : Route des Crêtes du Vexin, randonnée GR2, peinture en plein air (terrain de prédilection des impressionnistes 1860-1910), Seine en canoë',
      'Accès : 1h Paris (A15 + A14), gare Mantes-la-Jolie SNCF (40 min Paris-Saint-Lazare), Roissy-CDG à 50 min',
    ],
    keywordsEn: [
      'French Vexin — Regional Nature Park (1995), chalk plateau between Seine and Epte',
      "Le Moulin de Fourges, Hôtel de la Chaîne d'Or (Les Andelys)",
      'Giverny (Monet 1883-1926), Auvers-sur-Oise (Van Gogh, May-July 1890), La Roche-Guyon castle',
    ],
    toneFr: 'impressionniste, bucolique, francilien',
  },

  {
    slug: 'ile-de-france-region',
    nameFr: 'Île-de-France (région)',
    nameEn: 'Île-de-France region',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'versailles',
      'fontainebleau',
      'chantilly',
      'barbizon',
      'rambouillet',
      'saint-germain-en-laye',
      'auvers-sur-oise',
      'magny-en-vexin',
      'gouvieux',
      'guainville',
      'augerville-la-rivière',
      'augerville-la-riviere',
    ],
    keywordsFr: [
      'Île-de-France — région capitale, 12 M habitants (1/5 de la population française), 8 départements + Paris',
      'Adresses (hors Paris) : Auberge du Jeu de Paume (Chantilly), Domaine de Fontenille (Versailles à 30 min), Domaine des Étangs (Massignac frontière), Château de Versailles Le Grand Contrôle (Airelles)',
      'Châteaux royaux et résidences : Versailles (UNESCO 1979, 800 ha, Galerie des Glaces 73 m), Fontainebleau (UNESCO 1981, 9 siècles résidence royale), Chantilly (Musée Condé), Vaux-le-Vicomte (Le Nôtre / Le Vau / Le Brun, 1656-1661), Rambouillet',
      "Forêts royales : Fontainebleau (25 000 ha, paradis de l'escalade et site impressionniste), Rambouillet (14 000 ha), Chantilly (6 300 ha), Saint-Germain (3 500 ha)",
      'Patrimoine artistique : Barbizon (école 1830, Millet / Rousseau / Daubigny), Auvers-sur-Oise (Van Gogh), Médan (Zola)',
      'Provins (UNESCO 2001, cité médiévale champenoise), Maisons-Laffitte (Mansart 1651, course hippique), Disneyland Paris (Marne-la-Vallée)',
      'Accès : RER A/B/C/D, Transilien, TGV depuis Paris (Massy, Roissy), aéroports Paris-CDG / Orly / Beauvais',
    ],
    keywordsEn: [
      'Île-de-France region — capital region (12 M people), 8 departments around Paris',
      'Auberge du Jeu de Paume (Chantilly), Le Grand Contrôle (Versailles, Airelles)',
      'Royal châteaux: Versailles (UNESCO), Fontainebleau (UNESCO), Vaux-le-Vicomte, Rambouillet',
    ],
    toneFr: 'royal, francilien, monumental',
  },

  {
    slug: 'auvergne-rhone-alpes',
    nameFr: 'Auvergne-Rhône-Alpes',
    nameEn: 'Auvergne-Rhône-Alpes',
    scope: 'region',
    countryCode: 'FR',
    hotelCityKeys: [
      'lyon',
      'annecy',
      'talloires',
      'veyrier-du-lac',
      'chamonix',
      'chamonix-mont-blanc',
      'megève',
      'megeve',
      'courchevel',
      "val d'isère",
      "val d'isere",
      'méribel',
      'meribel',
      'evian-les-bains',
      'évian-les-bains',
      'vichy',
      'le-puy-en-velay',
      'puy-en-velay',
      'aix-les-bains',
      'chamonix',
    ],
    keywordsFr: [
      'Auvergne-Rhône-Alpes — fusion 2016, 8,1 M habitants (2ᵉ région française), 12 départements, Massif Central + Alpes + couloir rhodanien',
      "Adresses Alpes : Les Airelles Courchevel, Cheval Blanc Courchevel, Hôtel du Cap (Cap-Ferrat) côté azuréen, Four Seasons Megève, Le K2 Palace, Six Senses Courchevel — voir guides 'alpes' et 'courchevel' / 'megeve' / 'val-d-isere'",
      'Lyon — capitale gastronomique mondiale (Paul Bocuse Collonges 1965-2018, 19 étoiles Michelin), Vieux Lyon (UNESCO 1998), Confluence, mère de Lyon (Brazier 1933 première triplement étoilée)',
      "Annecy — 'Venise des Alpes', lac le plus pur d'Europe, Veyrier-du-Lac (Yoann Conte **), Annecy-le-Vieux (Laurent Petit *** Clos des Sens)",
      "Stations 5 étoiles : Courchevel 1850 (la plus prestigieuse, altiport), Val d'Isère + Tignes (Espace Killy 300 km), Megève (Rothschild 1920), Méribel (3 Vallées 600 km), Chamonix-Mont-Blanc (aiguille du Midi 3842 m)",
      "Thermes historiques : Vichy (Reine des villes d'eaux, Napoléon III), Aix-les-Bains, Évian, Brides-les-Bains, Allevard",
      "Patrimoine UNESCO : Lyon Vieux + Croix-Rousse, abbaye de Cluny (Saône-et-Loire frontière), grottes Chauvet (Pont d'Arc), pèlerinage du Puy-en-Velay (Saint-Jacques)",
    ],
    keywordsEn: [
      'Auvergne-Rhône-Alpes — 8.1 M people, Massif Central + Alps + Rhône corridor',
      'Lyon (gastronomic capital, Bocuse), Courchevel (Les Airelles, Cheval Blanc), Megève (Four Seasons)',
      'Lake Annecy (Yoann Conte, Le Clos des Sens), Vichy thermal baths, Mont-Blanc',
    ],
    toneFr: 'alpin, gourmand, lyonnais',
  },

  // ── INTERNATIONAL — country-level guides (Phase 2, post-Yonder intl) ──
  // Country guides anchor the "Monde — par pays" navigation. They join
  // hotels via `country_code` not `city`, so `hotelCityKeys` is left
  // empty — the page route dispatches on `guide.scope === 'country'`
  // and calls `getHotelsForCountry()` instead of `getHotelsForDestination()`.

  {
    slug: 'japon',
    nameFr: 'Japon',
    nameEn: 'Japan',
    scope: 'country',
    countryCode: 'JP',
    hotelCityKeys: [],
    keywordsFr: [
      'Japon — archipel de 6 852 îles (4 principales : Honshu, Hokkaido, Kyushu, Shikoku), 125 M habitants, capitale Tokyo (37 M métropole, plus grande zone urbaine mondiale)',
      'Palaces Tokyo : Aman Tokyo (Otemachi Tower), Mandarin Oriental Tokyo (Nihonbashi), Four Seasons Tokyo at Otemachi, Park Hyatt Tokyo (Shinjuku, Lost in Translation), The Peninsula Tokyo (Marunouchi face Palais Impérial)',
      'Palaces Kyoto : Aman Kyoto (Higashiyama, 32 chambres), Park Hyatt Kyoto (Kodaiji), Four Seasons Kyoto (Higashiyama, jardin Shakusui-en XIIIᵉ), HOSHINOYA Kyoto (en bateau sur la rivière Oi)',
      "Patrimoine UNESCO (25 sites) : Kyoto monuments anciens (17 temples, jardins zen, Kinkaku-ji pavillon d'or, Fushimi Inari 1 000 torii), Itsukushima torii flottant Miyajima, Nikko sanctuaires Tokugawa, château Himeji",
      'Gastronomie : 213 restaurants 3★ Michelin (1ʳᵉ ville mondiale Tokyo avec 12 trois étoiles 2024), saisons kaiseki (haute cuisine japonaise), washoku (Patrimoine immatériel UNESCO 2013), sushi Sukiyabashi Jiro, kappo, izakaya',
      'Saisons clés : sakura cerisiers fin mars-mi-avril (hanami), kōyō érables rouges fin octobre-novembre, été chaud humide juin-août, ski Hokkaido (Niseko, poudreuse mondialement reconnue) décembre-mars',
      'Art de vivre : ryokan auberges traditionnelles (futon, tatami, onsen sources thermales), cérémonie du thé (chanoyu), ikebana, bain public sento, kabuki, tradition Geisha Gion (Kyoto)',
      'Transports : Shinkansen TGV 320 km/h (Tokyo-Kyoto 2h15), JR Pass touristes étrangers, aéroports Narita (NRT, 60 km Tokyo) et Haneda (HND, 15 km), Kansai International (KIX) pour Kyoto/Osaka',
      'Climat : tempéré subtropical sud (Okinawa), continental nord (Hokkaido), tsuyu saison des pluies juin, typhons août-septembre',
    ],
    keywordsEn: [
      'Japan — archipelago of 6 852 islands, 125 M people, Tokyo metropolis (37 M, largest urban area in the world)',
      'Tokyo Palaces: Aman Tokyo, Mandarin Oriental Tokyo (Nihonbashi), Four Seasons Otemachi, Park Hyatt Tokyo (Shinjuku), Peninsula Tokyo (Marunouchi facing Imperial Palace)',
      'Kyoto Palaces: Aman Kyoto (Higashiyama), Park Hyatt Kyoto, Four Seasons Kyoto (Shakusui-en garden), HOSHINOYA Kyoto (riverboat arrival)',
      'UNESCO heritage: Kyoto ancient monuments (17 temples, zen gardens, Kinkaku-ji Golden Pavilion), Itsukushima floating torii (Miyajima), Nikko Tokugawa shrines, Himeji castle',
      'Gastronomy: Tokyo holds 12 three-Michelin-star restaurants (#1 city worldwide 2024), kaiseki seasonal high cuisine, washoku (UNESCO 2013), Sukiyabashi Jiro sushi',
      'Seasons: cherry blossoms late March-mid April (hanami), red maples October-November (kōyō), Hokkaido powder skiing December-March (Niseko)',
      'Lifestyle: ryokan traditional inns (futon, tatami, onsen hot springs), tea ceremony (chanoyu), ikebana, kabuki, Geisha Gion district (Kyoto)',
      'Transport: Shinkansen bullet train 320 km/h (Tokyo-Kyoto 2h15), JR Pass for tourists, Narita (NRT) + Haneda (HND) airports for Tokyo, Kansai (KIX) for Kyoto/Osaka',
    ],
    toneFr: 'raffiné, contemplatif, fidèle aux traditions millénaires',
  },

  {
    slug: 'etats-unis',
    nameFr: 'États-Unis',
    nameEn: 'United States',
    scope: 'country',
    countryCode: 'US',
    hotelCityKeys: [],
    keywordsFr: [
      'États-Unis — 50 états + District of Columbia, 333 M habitants (3ᵉ pays le plus peuplé), 9,8 M km² (4ᵉ pays par superficie), 6 fuseaux horaires continentaux + Hawaii + Alaska',
      'Palaces New York : The Mark Hotel (Madison Avenue), The Pierre (A Taj Hotel, Central Park), Aman New York (Crown Building, Fifth Avenue), Mandarin Oriental New York (Columbus Circle), Four Seasons Hotel New York Downtown',
      'Palaces Los Angeles : The Beverly Hills Hotel (Sunset Boulevard, Dorchester Collection, 1912), Hotel Bel-Air (Dorchester Collection, 1946, jardins 12 acres), Waldorf Astoria Beverly Hills, Maybourne Beverly Hills',
      'Palaces Miami : Faena Hotel Miami Beach (Collins Avenue, frontière design district), Four Seasons at The Surf Club (Surfside, ancien club années 1930), Mandarin Oriental Miami (Brickell Key)',
      'Patrimoine UNESCO (25 sites US) : Grand Canyon, Yellowstone (1ᵉʳ parc national mondial 1872), Yosemite (Half Dome, El Capitan), Statue of Liberty, Independence Hall (Philadelphia), Mesa Verde',
      'Gastronomie : 79 restaurants 3★ Michelin (New York 12, Bay Area 14, Los Angeles 7, Washington 3, Miami 1, Chicago 2), French Laundry (Yountville, Thomas Keller), Per Se (NYC, Thomas Keller), Eleven Madison Park (NYC, Daniel Humm, 100% végétal depuis 2021)',
      'Saisons : été 21 juin-22 septembre, foliage Nouvelle-Angleterre fin septembre-mi-octobre (Vermont, New Hampshire, Maine), saison sèche Californie mai-octobre, hurricanes Gulf juin-novembre',
      'Hubs aéroports : JFK + LGA + EWR (New York), LAX + SFO + LAS (Ouest), MIA + ATL + ORD (Sud/Centre), Délta + United + American Airlines (3 majors)',
      "Art de vivre : 'four corners' à Las Vegas / Aspen / Hamptons / Napa, Broadway 41 théâtres (NYC), Hollywood, Silicon Valley, Wall Street, NBA + NFL + MLB",
      'Climat : continental tempéré au centre, océanique au Nord-Est, méditerranéen en Californie, subtropical Floride, alpin Rocheuses, désertique Sud-Ouest',
    ],
    keywordsEn: [
      'United States — 50 states, 333 M people, 9.8 M km², 6 continental time zones + Hawaii + Alaska',
      'NYC Palaces: The Mark, The Pierre (A Taj Hotel), Aman New York (Crown Building), Mandarin Oriental Columbus Circle, Four Seasons Downtown',
      'LA Palaces: The Beverly Hills Hotel (1912, Dorchester), Hotel Bel-Air (1946, Dorchester, 12-acre gardens), Waldorf Astoria Beverly Hills, Maybourne Beverly Hills',
      'Miami Palaces: Faena Miami Beach, Four Seasons at The Surf Club, Mandarin Oriental Miami',
      'UNESCO heritage: Grand Canyon, Yellowstone (1872 — first national park), Yosemite, Statue of Liberty, Independence Hall, Mesa Verde',
      'Gastronomy: 79 three-Michelin-star restaurants nationwide, French Laundry (Yountville), Per Se (NYC), Eleven Madison Park (100% plant-based since 2021)',
      'Foliage New England late September-mid October (Vermont, New Hampshire, Maine), dry season California May-October, hurricane Gulf June-November',
    ],
    toneFr: 'ample, audacieux, contrasté entre côte Est patrimoniale et Ouest pionnier',
  },

  {
    slug: 'italie',
    nameFr: 'Italie',
    nameEn: 'Italy',
    scope: 'country',
    countryCode: 'IT',
    hotelCityKeys: [],
    keywordsFr: [
      'Italie — 60 M habitants, 20 régions, 7 600 km de côtes, péninsule + Sicile + Sardaigne, Rome capitale (4,3 M métropole)',
      'Palaces Rome : Hotel de Russie (Via del Babuino, Rocco Forte), Hassler Roma (Trinità dei Monti, 1893), Hotel Eden (Via Ludovisi, Dorchester), Bulgari Hotel Roma (Piazza Augusto Imperatore, 2023)',
      "Palaces Lac de Côme : Villa d'Este (Cernobbio, 1568, Travel + Leisure World's Best 2025), Passalacqua (Moltrasio, classé The World's 50 Best Hotels), Grand Hotel Tremezzo, Mandarin Oriental Lago di Como (Blevio)",
      'Palaces Florence : Four Seasons Hotel Firenze (jardin urbain le plus grand de Florence, Palazzo della Gherardesca XVᵉ), Hotel Lungarno (rive sud Arno, Salvatore Ferragamo), Portrait Firenze',
      "Patrimoine UNESCO Italie — **#1 mondial avec 60 sites** : Rome centre historique, Venise + lagune, Florence centre historique, Cinque Terre, Sassi di Matera, Val d'Orcia, Pompéi + Herculanum + Torre Annunziata",
      'Gastronomie : 13 restaurants 3★ Michelin (Niederkofler Sand St. Hubertus, Bottura Osteria Francescana Modène, Sgroi Le Calandre Padoue, Niko Romito Reale Castel di Sangro), pasta DOP région par région, San Marzano tomate, Parmigiano Reggiano, prosciutto di Parma',
      'Saisons clés : mai-juin et septembre-octobre (climat méditerranéen idéal), août très chaud + ferragosto (Italiens en vacances), ski Dolomites décembre-mars (UNESCO 2009)',
      'Art de vivre : aperitivo 18h-20h (Spritz, Negroni, Aperol), riposo (sieste sud) 13h-16h, dolce vita romaine, opera (La Scala Milan, Teatro La Fenice Venise, Arena di Verona été)',
      "Régions luxe : Toscane (Chianti, Val d'Orcia, San Gimignano), Pouilles (masseria, Lecce baroque), Sicile (Taormina, Etna, Palerme), Côte amalfitaine (Positano, Amalfi, Ravello), Lac de Côme, Capri",
      'Transports : Trenitalia Frecciarossa TGV (Rome-Milan 2h55), aéroports FCO Rome + LIN/MXP Milan + VCE Venise + FLR Florence, ITA Airways (ex-Alitalia 2021)',
    ],
    keywordsEn: [
      'Italy — 60 M people, 20 regions, 7 600 km of coastline, Rome capital (4.3 M metro)',
      'Rome Palaces: Hotel de Russie (Rocco Forte), Hassler Roma (1893, Trinità dei Monti), Hotel Eden (Dorchester), Bulgari Hotel Roma (2023)',
      "Lake Como Palaces: Villa d'Este (1568, T+L World's Best 2025), Passalacqua (W50), Grand Hotel Tremezzo, Mandarin Oriental Lago di Como",
      'Florence Palaces: Four Seasons Hotel Firenze (Gherardesca palazzo, largest private garden in Florence), Hotel Lungarno (Ferragamo), Portrait Firenze',
      "UNESCO: Italy holds the world record with 60 sites — Rome, Venice, Florence, Cinque Terre, Matera, Pompeii, Val d'Orcia",
      'Gastronomy: 13 three-Michelin-star restaurants — Niederkofler (Sand St Hubertus), Bottura (Osteria Francescana Modena), Sgroi (Le Calandre Padua), Romito (Reale Castel di Sangro)',
      'Seasons: May-June + September-October ideal Mediterranean climate, August very hot + ferragosto Italian holiday, Dolomites skiing December-March (UNESCO 2009)',
    ],
    toneFr: 'patrimonial, gourmand, dolce vita',
  },

  {
    slug: 'royaume-uni',
    nameFr: 'Royaume-Uni',
    nameEn: 'United Kingdom',
    scope: 'country',
    countryCode: 'GB',
    hotelCityKeys: [],
    keywordsFr: [
      "Royaume-Uni — 4 nations (Angleterre, Écosse, pays de Galles, Irlande du Nord), 67 M habitants, Londres capitale (9,5 M métropole), île de Grande-Bretagne + nord-est de l'Irlande",
      "Palaces Londres : Claridge's (Mayfair, 1812, Maybourne), The Connaught (Mayfair, Maybourne, bar Hélène Darroze ***), The Berkeley (Knightsbridge, Maybourne), Rosewood London (Holborn, 2013), Bulgari Hotel & Residences London (Knightsbridge)",
      'Mandarin Oriental Hyde Park (Knightsbridge, 1889, 2 étoiles Michelin restaurant Heston Blumenthal Dinner), The Lanesborough (Hyde Park Corner, Oetker Collection), Four Seasons Park Lane',
      "Patrimoine UNESCO (33 sites britanniques + 1 outre-mer) : Tour de Londres + Westminster + Palace, Stonehenge, Bath cité géorgienne, Edinburgh Old + New Towns, Maritime Greenwich, château et cathédrale de Canterbury, Mur d'Hadrien, île de Skellig (Irlande du Nord)",
      "Gastronomie : Londres 80+ restaurants étoilés Michelin (Core by Clare Smyth ***, Restaurant Gordon Ramsay ***, Alain Ducasse at The Dorchester ***), afternoon tea tradition (The Ritz London, Claridge's, The Savoy), pub gastronomique",
      'Art de vivre : familles royales (Buckingham Palace, Windsor, Balmoral, Sandringham), changement de la garde 11h Buckingham, Trooping the Colour (juin anniversaire roi), Royal Ascot (juin), Wimbledon (fin juin-mi-juillet), Henley Regatta',
      'Régions hors Londres : Cotswolds (villages de pierre dorée, Soho Farmhouse), Lake District (UNESCO 2017, William Wordsworth poètes lakistes), Highlands écossais (whisky Speyside, château Cawdor), Cornouailles (Tregenna Castle, plages Atlantique)',
      'Saisons : climat océanique tempéré, été 18-25°C juin-août, pluies fréquentes mais courtes, hiver doux 4-8°C, neige rare sauf Highlands, foliage octobre, jonquilles printemps mars-avril',
      'Transports : Heathrow LHR (5 terminaux, hub British Airways), Gatwick LGW, Stansted STN, City Airport LCY (jet privé), Eurostar Paris-Londres St Pancras 2h15, métro Underground (Tube) 11 lignes',
      'Pub & afternoon tea : tradition cream tea (Cornouailles + Devon, scones + clotted cream + jam), high tea, gin tonic post-1750, ale + cider, Sunday roast',
    ],
    keywordsEn: [
      'United Kingdom — 4 nations, 67 M people, London (9.5 M metro), Great Britain + Northern Ireland',
      "London Palaces: Claridge's (1812, Maybourne), The Connaught (Maybourne, Hélène Darroze ***), The Berkeley (Maybourne), Rosewood London (2013), Bulgari Knightsbridge",
      'Mandarin Oriental Hyde Park (1889, Heston Blumenthal Dinner ★★), The Lanesborough (Oetker Collection), Four Seasons Park Lane',
      "UNESCO: Tower of London + Westminster, Stonehenge, Bath, Edinburgh Old + New Town, Maritime Greenwich, Canterbury, Hadrian's Wall",
      'Gastronomy: London hosts 80+ Michelin-starred restaurants — Core by Clare Smyth ***, Restaurant Gordon Ramsay ***, Alain Ducasse at The Dorchester ***',
      'Lifestyle: Royal Family, changing of the guard, Trooping the Colour, Royal Ascot, Wimbledon, Henley Regatta',
      'Beyond London: Cotswolds (Soho Farmhouse), Lake District (UNESCO 2017), Scottish Highlands (Speyside whisky), Cornwall (Atlantic beaches)',
    ],
    toneFr: 'patrimonial, royal, britannique classique',
  },

  {
    slug: 'espagne',
    nameFr: 'Espagne',
    nameEn: 'Spain',
    scope: 'country',
    countryCode: 'ES',
    hotelCityKeys: [],
    keywordsFr: [
      "Espagne — 48 M habitants, 17 communautés autonomes, péninsule ibérique + Baléares + Canaries + Ceuta + Melilla, Madrid capitale (6,7 M métropole, plus haute capitale d'Europe à 667 m d'altitude)",
      'Palaces Madrid : Mandarin Oriental Ritz Madrid (1910 réhabilité 2021, Plaza de la Lealtad face Prado), Four Seasons Hotel Madrid (Centro Canalejas, 7 bâtiments historiques fusionnés, 2020), Bless Hotel Madrid (Salamanca), Rosewood Villa Magna',
      'Palaces Barcelone : Mandarin Oriental Barcelona (Passeig de Gràcia, Carme Ruscalleda Moments **), Hotel Arts Barcelona (Ritz-Carlton, plage Barceloneta), W Barcelona (Ricardo Bofill, voile architecturale), Casa Fuster (Lluís Domènech i Montaner moderniste)',
      'Patrimoine UNESCO (50 sites) : Alhambra de Grenade + Generalife (1984), Sagrada Familia + œuvres Gaudí Barcelone (Park Güell, Casa Milà, Casa Batlló), Tolède centre historique, Ségovie + aqueduc romain, Cordoue mosquée-cathédrale, Saint-Jacques-de-Compostelle, parc national de Doñana',
      'Gastronomie : 14 restaurants 3★ Michelin (DiverXO Madrid Dabiz Muñoz, ABaC Barcelone Jordi Cruz, Akelarre Pedro Subijana, Aponiente Ángel León, Disfrutar Barcelone), tapas, jamón ibérico de bellota, paella valencienne, pintxos (Pays basque), churros con chocolate',
      'Saisons : printemps mars-mai (Semana Santa Pâques, Feria de Abril Séville), été 35-40°C intérieur juillet-août, automne septembre-novembre vendanges Rioja, hiver doux côte méditerranéenne, ski Sierra Nevada (Andalousie) + Pyrénées',
      'Régions luxe : Andalousie (Marbella, Séville, Grenade, Cordoue), Côte catalane (Barcelone, Costa Brava), Baléares (Majorque, Ibiza, Minorque, Formentera), îles Canaries (Tenerife, Lanzarote), Pays basque (Saint-Sébastien, gastronomie)',
      'Art de vivre : flamenco (Andalousie, UNESCO 2010), corrida (Madrid Las Ventas), siesta 14h-17h, dîner tardif 21h-23h, paseo soirée, festas patronales chaque village été',
      'Transports : Renfe AVE TGV (Madrid-Barcelone 2h30, Madrid-Séville 2h30), aéroports MAD Madrid-Barajas + BCN Barcelone-El Prat + AGP Málaga + PMI Palma, Iberia + Vueling principaux opérateurs',
      'Climat : méditerranéen côtier (étés chauds secs, hivers doux), océanique au Nord (Cantabrie, Pays basque), continental au centre, subtropical Canaries (printemps éternel)',
    ],
    keywordsEn: [
      'Spain — 48 M people, 17 autonomous communities, Madrid capital (6.7 M metro, highest European capital at 667 m)',
      'Madrid Palaces: Mandarin Oriental Ritz Madrid (1910, restored 2021), Four Seasons Madrid (Centro Canalejas, 7 historic buildings, 2020), Rosewood Villa Magna',
      'Barcelona Palaces: Mandarin Oriental Barcelona (Passeig de Gràcia, Moments ★★ Carme Ruscalleda), Hotel Arts Barcelona (Ritz-Carlton), W Barcelona (Bofill)',
      'UNESCO: Alhambra (Granada), Gaudí works in Barcelona (Sagrada Familia, Park Güell, Casa Milà), Toledo old town, Segovia + Roman aqueduct, Córdoba mosque-cathedral, Santiago de Compostela',
      'Gastronomy: 14 three-Michelin-star restaurants — DiverXO (Madrid), ABaC + Disfrutar (Barcelona), Akelarre + Aponiente (Basque/Cádiz)',
      'Lifestyle: flamenco (UNESCO 2010), corrida (Madrid Las Ventas), siesta, late dinner 21h-23h',
      'Transport: AVE high-speed train (Madrid-Barcelona 2h30), Madrid-Barajas + Barcelona-El Prat + Málaga + Palma airports',
    ],
    toneFr: 'ensoleillé, festif, héritage mauresque + chrétien',
  },

  {
    slug: 'emirats-arabes-unis',
    nameFr: 'Émirats arabes unis',
    nameEn: 'United Arab Emirates',
    scope: 'country',
    countryCode: 'AE',
    hotelCityKeys: [],
    keywordsFr: [
      'Émirats arabes unis — fédération de 7 émirats (Abu Dhabi capitale, Dubaï le plus peuplé, Sharjah, Ajman, Umm al-Quwain, Ras al-Khaimah, Fujairah), 10 M habitants (90% expatriés), indépendance 1971',
      'Palaces Dubaï : Burj Al Arab (Jumeirah, 1999, hôtel-voile 321 m, considéré le plus luxueux du monde), Atlantis The Royal (Palm Jumeirah, 2023, ouvert par Beyoncé concert privé), Bulgari Resort Dubai (Jumeirah Bay Island), One&Only The Palm, Four Seasons Resort Jumeirah Beach, Mandarin Oriental Jumeira',
      'Palaces Abu Dhabi : Emirates Palace (Mandarin Oriental, 1 km de façade, dôme doré, 114 dômes, 1 002 chandeliers Swarovski), The St. Regis Abu Dhabi, Park Hyatt Abu Dhabi Saadiyat Island',
      "Patrimoine UNESCO (1 site) : sites culturels d'Al Aïn (oasis, Hili, Bida bint Saud, Jebel Hafit, 2011) — 6 oasis pré-islamiques + tombes circulaires âge du Bronze IIIᵉ millénaire",
      'Gastronomie : 19 restaurants étoilés Michelin Dubaï (1ʳᵉ édition 2022, Stay by Yannick Alléno ★★, Tresind Studio Himanshu Saini, Trèsind Dubai), 11 restaurants étoilés Abu Dhabi (Talea by Antonio Guida, Hakkasan), cuisine arabe (mezzes, mansaf, harees), khaleeji',
      'Saisons : hiver tempéré 20-28°C décembre-mars (saison touristique principale), printemps doux mars-avril, été extrême 40-50°C mai-septembre (humidité 80%), automne supportable octobre-novembre, plus aucune pluie 9 mois/an',
      'Architecture iconique : Burj Khalifa (Dubaï, 828 m, plus haute tour mondiale depuis 2010), Palm Jumeirah (île artificielle palmier), Dubai Frame (150 m), Louvre Abu Dhabi (Jean Nouvel 2017), Sheikh Zayed Grand Mosque (Abu Dhabi, 82 dômes blancs)',
      "Art de vivre : shopping malls climatisés (Dubai Mall + Mall of the Emirates avec piste de ski indoor Ski Dubai), brunchs vendredi-samedi tradition expatriée, courses de chameaux à Al Marmoom, fauconnerie patrimoine UNESCO immatériel 2010, désert dunes Rub' al-Khali",
      'Transports : aéroport Dubaï DXB (hub Emirates Airlines, plus fréquenté monde pour passagers internationaux), Abu Dhabi AUH (Etihad Airways), Dubai Metro (autonome, 2 lignes), Etihad Rail (Abu Dhabi-Fujairah 2024), Sheikh Zayed Road autoroute 12 voies',
      'Communauté luxe : tourisme de luxe, achat tax-free, événements F1 Abu Dhabi Grand Prix (novembre), Dubai World Cup (mars, plus riche course hippique mondiale), Dubai Shopping Festival, Art Dubai (mars)',
    ],
    keywordsEn: [
      'UAE — federation of 7 emirates (Abu Dhabi capital, Dubai most populated), 10 M people (90% expats), independence 1971',
      'Dubai Palaces: Burj Al Arab (1999, sail-shaped 321 m), Atlantis The Royal (Palm Jumeirah, 2023), Bulgari Resort Dubai, One&Only The Palm, Four Seasons Jumeirah, Mandarin Oriental Jumeira',
      'Abu Dhabi Palaces: Emirates Palace (Mandarin Oriental, 1 km facade, 114 domes, 1 002 Swarovski chandeliers), St. Regis Abu Dhabi, Park Hyatt Saadiyat',
      'UNESCO: Cultural Sites of Al Ain (oases, Hili, Bida bint Saud, Jebel Hafit — 2011)',
      'Gastronomy: 19 Michelin-starred restaurants in Dubai (Michelin Guide UAE launched 2022), Stay by Yannick Alléno ★★, Tresind Studio, plus 11 in Abu Dhabi',
      "Architecture: Burj Khalifa (828 m, world's tallest since 2010), Palm Jumeirah, Louvre Abu Dhabi (Jean Nouvel 2017), Sheikh Zayed Grand Mosque (82 white domes)",
      'Lifestyle: shopping malls (Dubai Mall, Mall of the Emirates + Ski Dubai indoor slope), Friday-Saturday brunch tradition, falconry (UNESCO intangible heritage 2010), camel racing',
    ],
    toneFr: 'spectaculaire, futuriste, hospitalité arabe XXIᵉ siècle',
  },

  {
    slug: 'turquie',
    nameFr: 'Turquie',
    nameEn: 'Turkey',
    scope: 'country',
    countryCode: 'TR',
    hotelCityKeys: [],
    keywordsFr: [
      'Turquie — 85 M habitants, à cheval Europe + Asie (Thrace 3% + Anatolie 97%), Istanbul plus grande ville (16 M, seule métropole transcontinentale au monde), Ankara capitale politique (5,7 M)',
      'Palaces Istanbul : Mandarin Oriental Bosphorus (Beşiktaş, façade Bosphore, 2022), Four Seasons Hotel Istanbul at the Bosphorus (palais Atik Pasha XIXᵉ rive européenne), Four Seasons Hotel Istanbul at Sultanahmet (ancienne prison Ottoman 1918, près Hagia Sophia), Çırağan Palace Kempinski (palais ottoman XIXᵉ, sultan Abdülaziz)',
      'Park Hyatt Istanbul - Maçka Palas (Nişantaşı, immeuble Art déco 1922), The Peninsula Istanbul (Karaköy, 2023, ancien terminal maritime), Six Senses Kocataş Mansions (Sarıyer, deux yalı bord du Bosphore)',
      "Patrimoine UNESCO (21 sites) : zones historiques d'Istanbul (Sultanahmet, Hagia Sophia VIᵉ Justinien, Mosquée Bleue, Topkapı palais sultans, Citerne basilique), Cappadoce (Göreme parc national, cheminées de fées, églises rupestres byzantines), Éphèse (Bibliothèque Celsus, théâtre 25 000 places), Pamukkale (vasques travertin blanc, Hiérapolis), Troie",
      'Gastronomie : 6 restaurants étoilés Michelin Istanbul (1ʳᵉ édition 2022, Turk Fatih Tutak ★★, Mikla, Neolokal, Tickle Restaurant), kebab + meze + raki, hammam, baklava + Turkish delight (lokum), thé noir (çay) tradition nationale',
      'Saisons : printemps avril-juin + automne septembre-octobre idéaux (15-25°C), été chaud Istanbul + côte égéenne 30°C, ski Uludağ + Erciyes décembre-mars, hiver doux côte méditerranéenne Antalya (15°C)',
      'Cappadoce : montgolfières au lever du soleil (200+ ballons à Göreme, considéré meilleur spot mondial), hôtels troglodytes (Argos in Cappadocia, Museum Hotel), randonnée vallées Rose + Ihlara',
      'Côte égéenne et méditerranéenne : Bodrum (yacht charter, Mandarin Oriental Bodrum, Bvlgari Bodrum, ancienne Halicarnasse), Çeşme (D-Hotel Maris), Antalya (riviera turque, anciennes cités lyciennes Demre Myra)',
      'Art de vivre : narguilé (chicha), bain turc hammam tradition (Çağaloğlu Hamamı 1741, Cemberlitaş 1584), tapis et kilim, bazar Grand Bazaar 4 000 boutiques, dervishes tourneurs Konya (UNESCO immatériel 2008)',
      'Transports : Istanbul Airport IST (2018, 3ᵉ plus grand mondial), Sabiha Gökçen SAW (low-cost), Antalya AYT (touristique), Turkish Airlines (THY) plus large réseau mondial (350+ destinations), TGV Marmaray sous le Bosphore, Bosphore ferries traditionnels',
    ],
    keywordsEn: [
      'Turkey — 85 M people, straddles Europe + Asia (Thrace 3% + Anatolia 97%), Istanbul largest city (16 M, only transcontinental megacity), Ankara political capital',
      'Istanbul Palaces: Mandarin Oriental Bosphorus (2022, Bosphorus waterfront), Four Seasons Bosphorus (Atik Pasha 19c palace), Four Seasons Sultanahmet (former 1918 Ottoman prison), Çırağan Palace Kempinski (19c Sultan Abdülaziz palace)',
      'Park Hyatt Istanbul - Maçka Palas (1922 Art Deco), The Peninsula Istanbul (2023, former maritime terminal), Six Senses Kocataş Mansions (Bosphorus yalı)',
      'UNESCO: Istanbul historic areas (Hagia Sophia 6c, Blue Mosque, Topkapı), Cappadocia (Göreme rock churches, fairy chimneys), Ephesus (Celsus library, 25k theatre), Pamukkale travertine pools, Troy',
      'Gastronomy: 6 Michelin-starred restaurants Istanbul (launched 2022) — Turk Fatih Tutak ★★, Mikla, Neolokal',
      'Cappadocia: 200+ hot-air balloons at Göreme sunrise (rated #1 globally), cave hotels, Argos in Cappadocia, Museum Hotel',
      'Aegean + Med coast: Bodrum (Mandarin Oriental Bodrum, Bvlgari Bodrum), Antalya (Turkish Riviera, ancient Lycian cities)',
    ],
    toneFr: 'transcontinental, ottoman, byzantin',
  },

  {
    slug: 'allemagne',
    nameFr: 'Allemagne',
    nameEn: 'Germany',
    scope: 'country',
    countryCode: 'DE',
    hotelCityKeys: [],
    keywordsFr: [
      "Allemagne — 84 M habitants (1ʳᵉ population européenne), 16 Länder, Berlin capitale (3,8 M, 4,7 M métropole), réunification 1990, économie n°1 de l'UE",
      'Palaces Berlin : Hotel Adlon Kempinski Berlin (Pariser Platz face Porte de Brandebourg, 1907, reconstruit 1997 avec accueil JFK), Hotel de Rome (Bebelplatz, Rocco Forte, ancienne banque Dresdner 1889), Soho House Berlin (Mitte, Torstrasse, immeuble Bauhaus 1928), The Ritz-Carlton Berlin (Potsdamer Platz)',
      'Palaces Munich : Bayerischer Hof (1841, Promenadeplatz), Hotel Vier Jahreszeiten Kempinski (Maximilianstrasse, 1858), Mandarin Oriental Munich (Altstadt), The Charles Hotel (Rocco Forte, Lenbachplatz), Rosewood Munich (Marienplatz, 2023)',
      'Palaces Hambourg : Fairmont Hotel Vier Jahreszeiten (Neuer Jungfernstieg, 1897, Lac Alster intérieur), The Fontenay Hamburg (2018, Außenalster), Atlantic Hotel Kempinski (1909)',
      'Patrimoine UNESCO (54 sites) : Aix-la-Chapelle cathédrale Charlemagne (1ʳᵉ site UNESCO Allemagne 1978), Cologne cathédrale (157 m flèches, 632 ans construction), Bauhaus (Weimar + Dessau + Bernau), Sanssouci (Potsdam, Frédéric II Rococo), île aux musées Berlin, Wartburg (Luther traduction Bible 1521)',
      'Gastronomie : 10 restaurants 3★ Michelin (JAN à Munich Jan Hartwig, Vendôme près Cologne Joachim Wissler, Schloss Schauenstein Andreas Caminada, GästeHaus Klaus Erfort Sarrebruck, Atelier Munich), cuisine de saison + nouvelle cuisine allemande, bière (Reinheitsgebot 1516 loi de pureté), Wurst (1 500 variétés), Brot (3 200 sortes pain UNESCO immatériel 2014)',
      'Saisons : printemps mai-juin (festival fleurs Mainau lac de Constance), été 25°C juin-août (festivals Berlin Underdocs, Wagner Bayreuth juillet-août), automne foliage Forêt-Noire + Saxonie, Oktoberfest Munich (16 jours fin septembre-début octobre, 6 M visiteurs), hiver Marchés de Noël (Christkindlmarkt) novembre-décembre',
      'Régions luxe : Bavière (Munich, Garmisch-Partenkirchen ski, Neuschwanstein château Louis II), Forêt-Noire (Baiersbronn 3 restaurants 3★ Michelin une seule petite ville, sources thermales Baden-Baden Brenners Park-Hotel), Hambourg (Hamburg-Speicherstadt UNESCO 2015 + Elbphilharmonie Herzog & de Meuron 2017)',
      'Art de vivre : ponctualité légendaire, Volkswagen + BMW + Mercedes-Benz + Porsche + Audi (constructeurs allemands), philosophie (Kant Königsberg, Hegel Stuttgart, Nietzsche Saxe), musique classique (Bach Leipzig, Beethoven Bonn, Brahms Hambourg, Wagner Bayreuth, Strauss Munich)',
      'Transports : Deutsche Bahn ICE TGV (Berlin-Munich 4h, Hambourg-Cologne 4h), aéroports Frankfurt FRA (hub Lufthansa, plus grand pays par passagers), Munich MUC, Berlin Brandenburg BER (2020), Hambourg HAM, Düsseldorf DUS, autobahn (autoroutes sans limite de vitesse 60% du réseau)',
    ],
    keywordsEn: [
      'Germany — 84 M people (#1 European population), 16 federal states, Berlin capital (3.8 M, 4.7 M metro), reunification 1990, #1 EU economy',
      'Berlin Palaces: Hotel Adlon Kempinski (Pariser Platz facing Brandenburg Gate, 1907 rebuilt 1997), Hotel de Rome (Bebelplatz, Rocco Forte, 1889 Dresdner bank), Soho House Berlin (1928 Bauhaus), Ritz-Carlton Berlin (Potsdamer Platz)',
      'Munich Palaces: Bayerischer Hof (1841, Promenadeplatz), Vier Jahreszeiten Kempinski (Maximilianstrasse, 1858), Mandarin Oriental Munich, The Charles Hotel (Rocco Forte), Rosewood Munich (2023)',
      'Hamburg Palaces: Fairmont Hotel Vier Jahreszeiten (1897, Alster Lake), The Fontenay Hamburg (2018), Atlantic Hotel Kempinski (1909)',
      'UNESCO: Aachen cathedral (Charlemagne, first German site 1978), Cologne cathedral (157 m spires, 632-year construction), Bauhaus (Weimar + Dessau + Bernau), Sanssouci (Potsdam Rococo), Museum Island Berlin',
      'Gastronomy: 10 three-Michelin-star restaurants — JAN Munich (Hartwig), Vendôme Cologne (Wissler), Schauenstein (Caminada), GästeHaus Klaus Erfort, Atelier Munich',
      'Lifestyle: Oktoberfest Munich (16 days late September-early October, 6 M visitors), Christmas markets Christkindlmarkt November-December, Wagner festival Bayreuth July-August',
    ],
    toneFr: 'patrimonial, précis, gastronomique nouvelle vague',
  },

  {
    slug: 'chine',
    nameFr: 'Chine',
    nameEn: 'China',
    scope: 'country',
    countryCode: 'CN',
    hotelCityKeys: [],
    keywordsFr: [
      "Chine — 1,41 milliard d'habitants (2ᵉ population mondiale), 23 provinces + 5 régions autonomes + 4 municipalités + 2 régions administratives spéciales (Hong Kong, Macao), Pékin (Beijing) capitale (21,5 M, 2ᵉ ville mondiale)",
      "Palaces Pékin : Aman Summer Palace (Beijing, à 100 m du Palais d'été UNESCO, anciens pavillons impériaux), Mandarin Oriental Wangfujing (2014, façade contemporaine), Rosewood Beijing (Chaoyang, 2014), The Peninsula Beijing (1989, première Peninsula Chine continentale), Bulgari Hotel Beijing",
      'Palaces Shanghai : The Peninsula Shanghai (Bund, 2009, dernier édifice du Bund), Mandarin Oriental Pudong (Lujiazui, 2013), Four Seasons Hotel Shanghai (Pudong + Puxi), Bulgari Hotel Shanghai (Suzhou Creek, 2018), Aman Yangyun (Minhang, jardin Antiquité)',
      "Palaces Hong Kong (région administrative spéciale) : Mandarin Oriental Hong Kong (Central, 1963, vue port Victoria), The Peninsula Hong Kong (Tsim Sha Tsui, 1928, 'la Grande Dame du Far East'), Rosewood Hong Kong (Tsim Sha Tsui, 2019), Four Seasons Hotel Hong Kong (IFC tower)",
      "Patrimoine UNESCO (57 sites — **#2 mondial avec l'Italie**) : Grande Muraille (21 196 km, dynasties Qin à Ming), Cité interdite Pékin (Forbidden City, 1406-1420, 980 bâtiments), Mausolée Qin Shi Huang armée terre cuite Xi'an (1974, 8 000+ soldats), Mont Huangshan + Mont Wudang, jardins classiques Suzhou, Lijiang vieille ville (UNESCO 1997)",
      'Gastronomie : 78 restaurants 3★ Michelin Chine continentale + Hong Kong + Macao (Shanghai 2 + Beijing 1 + Guangzhou 1 + Hong Kong 7 + Macao 2), 8 grandes cuisines régionales (Sichuan, Cantonaise, Shandong, Jiangsu, Zhejiang, Fujian, Hunan, Anhui), cérémonie du thé (Gongfu cha)',
      "Régions luxe : Shanghai (économique, Bund + Pudong + Concession française), Pékin (politique + impérial), Hong Kong (financier + culinaire), Hangzhou (lac de l'Ouest UNESCO 2011, OTM siège Alibaba), Chengdu (capitale Sichuan + pandas)",
      'Saisons : printemps avril-mai + automne septembre-novembre meilleurs (climat tempéré), été 35°C + humidité 80% Shanghai + Hong Kong juin-août, hiver -10°C Pékin (mais sec) décembre-février, ski Yabuli Heilongjiang',
      'Art de vivre : tradition millénaire (4 000 ans civilisation continue), médecine traditionnelle chinoise (acupuncture UNESCO 2010), opéra de Pékin (Jingju UNESCO 2010), arts martiaux (Tai Chi UNESCO 2020, Kung Fu Shaolin), nouvel an chinois (festival du printemps, premier nouveau mois lunaire)',
      'Transports : trains à grande vitesse CRH/Fuxing (Pékin-Shanghai 4h15, 350 km/h, plus long réseau mondial 45 000 km), aéroports Beijing Daxing PKX (2019, Zaha Hadid) + Capital PEK + Shanghai Pudong PVG + Shanghai Hongqiao SHA + Hong Kong HKG + Guangzhou CAN, Cathay Pacific (Hong Kong) + Air China + China Eastern',
    ],
    keywordsEn: [
      'China — 1.41 billion people (#2 globally), 23 provinces + 5 autonomous regions + 4 municipalities + 2 special administrative regions (Hong Kong, Macao), Beijing capital (21.5 M)',
      'Beijing Palaces: Aman Summer Palace (100 m from UNESCO Summer Palace, former imperial pavilions), Mandarin Oriental Wangfujing (2014), Rosewood Beijing (2014), The Peninsula Beijing (1989, first Peninsula in mainland China), Bulgari Hotel Beijing',
      'Shanghai Palaces: The Peninsula Shanghai (Bund, 2009 — last Bund building), Mandarin Oriental Pudong (2013), Four Seasons Shanghai (Pudong + Puxi), Bulgari Hotel Shanghai (Suzhou Creek, 2018), Aman Yangyun',
      'Hong Kong Palaces: Mandarin Oriental Hong Kong (Central, 1963), The Peninsula Hong Kong (Tsim Sha Tsui, 1928 — "the Grande Dame of the Far East"), Rosewood Hong Kong (2019), Four Seasons Hong Kong',
      "UNESCO: China holds 57 sites (tied #2 with Italy) — Great Wall (21 196 km), Forbidden City Beijing (1406-1420, 980 buildings), Qin Shi Huang Terracotta Army Xi'an (1974, 8 000+ soldiers), Mount Huangshan, Lijiang old town",
      'Gastronomy: 78 three-Michelin-star restaurants (mainland + HK + Macao) — Shanghai 2, Beijing 1, Guangzhou 1, Hong Kong 7, Macao 2',
      'Eight Great Cuisines: Sichuan, Cantonese, Shandong, Jiangsu, Zhejiang, Fujian, Hunan, Anhui',
    ],
    toneFr: 'millénaire, contrasté entre traditions impériales et hyper-modernité',
  },

  {
    slug: 'mexique',
    nameFr: 'Mexique',
    nameEn: 'Mexico',
    scope: 'country',
    countryCode: 'MX',
    hotelCityKeys: [],
    keywordsFr: [
      'Mexique — 130 M habitants (10ᵉ population mondiale), 32 États fédérés, capitale Mexico (CDMX, 22 M métropole, 3ᵉ plus grande ville mondiale), 1,96 M km² (13ᵉ pays superficie), 11 000 km de côtes Pacifique + Caraïbes',
      'Palaces Mexico (CDMX) : Four Seasons Hotel Mexico City (Paseo de la Reforma, jardin intérieur cour coloniale), Las Alcobas Mexico City (Polanco, Luxury Collection Marriott), Marquis Reforma (Reforma, design Bauhaus mexicain), St. Regis Mexico City (Reforma)',
      'Palaces Riviera Maya / Yucatán : Mayakoba Resort (Playa del Carmen, complexe Fairmont + Andaz + Banyan Tree + Rosewood), Rosewood Mayakoba (lagunes 2008, design Mexique Yucatán), Maroma A Belmond Hotel (Riviera Maya, plage privée), Chablé Maroma (cenote sacré maya), Las Ventanas al Paraíso Rosewood (Los Cabos, Baja California Sur)',
      'Palaces Cabo San Lucas (Basse-Californie) : Waldorf Astoria Los Cabos Pedregal (Pedregal Hill, 2014, tunnel privé), The Cape (Thompson Hotels, surf Monuments break), Esperanza Auberge Resorts Collection, Montage Los Cabos',
      'Patrimoine UNESCO (35 sites — 7ᵉ mondial) : Mexico City centre historique + Xochimilco (UNESCO 1987), Teotihuacán pyramides Soleil + Lune (50 km Mexico, civilisation pré-aztèque), Chichén Itzá (Yucatán, pyramide Kukulkán, équinoxe serpent qui descend), Palenque (jungle Chiapas, civilisation maya VIIᵉ siècle), Uxmal (style Puuc, Yucatán)',
      'Gastronomie : 18 restaurants étoilés Michelin Mexique (1ʳᵉ édition 2024, Pujol Mexico Enrique Olvera ★★, Quintonil Mexico Jorge Vallejo ★★, Sud777 Mexico Edgar Núñez ★), cuisine mexicaine Patrimoine immatériel UNESCO 2010, mole poblano (sauce 30 ingrédients), tacos al pastor, mezcal + tequila (Jalisco AOC), chocolat (origine maya 2000 av. J.-C.)',
      'Régions luxe : Riviera Maya (Cancún + Playa del Carmen + Tulum), Yucatán (Mérida coloniale + cénotes), Baja California Sur (Los Cabos + La Paz + Loreto), Mexico (capitale culturelle), Oaxaca (Pueblo Mágico patrimonial + cuisine), Puerto Vallarta (Jalisco Pacifique)',
      'Saisons : saison sèche novembre-avril (idéale touristique, 25-30°C côtes), saison humide mai-octobre (pluies courtes après-midi), hurricanes Caraïbes août-octobre + Pacifique juin-novembre, Festival Día de Muertos 1-2 novembre (UNESCO immatériel 2008)',
      'Art de vivre : siesta, mariachis (UNESCO 2011), corrida (Plaza México la plus grande mondiale 41 000 places), lucha libre (catch masqué), couleurs vives (textiles otomíes + zapotèques), murales (Diego Rivera + Frida Kahlo Casa Azul Coyoacán)',
      'Transports : Mexico Aéroport International Benito Juárez MEX + Felipe Ángeles AIFA (2022), Cancún Aéroport CUN (2ᵉ aéroport Mexique, hub touristique Caraïbes), Los Cabos SJD + La Paz LAP, Aeroméxico (compagnie nationale), pas de TGV (réseau ferré limité)',
    ],
    keywordsEn: [
      'Mexico — 130 M people (#10 globally), 32 federal states, Mexico City (CDMX, 22 M metro, #3 world city), 1.96 M km², 11 000 km of coasts (Pacific + Caribbean)',
      'CDMX Palaces: Four Seasons Mexico City (Paseo de la Reforma), Las Alcobas Mexico City (Polanco, Luxury Collection), Marquis Reforma, St. Regis Mexico City',
      'Riviera Maya / Yucatán: Mayakoba Resort (Fairmont + Andaz + Banyan Tree + Rosewood), Rosewood Mayakoba (2008), Maroma A Belmond Hotel, Chablé Maroma (Mayan sacred cenote)',
      'Los Cabos (Baja Sur): Waldorf Astoria Los Cabos Pedregal (2014, private tunnel), The Cape (Thompson), Esperanza Auberge Resorts, Montage Los Cabos, Las Ventanas al Paraíso Rosewood',
      'UNESCO: Mexico holds 35 sites (#7 globally) — Mexico City historic centre + Xochimilco, Teotihuacán pyramids, Chichén Itzá Kukulkán pyramid (equinox snake), Palenque (Mayan), Uxmal (Puuc style)',
      'Gastronomy: 18 Michelin-starred restaurants (Michelin Guide Mexico launched 2024) — Pujol ★★ + Quintonil ★★ Mexico City',
      'Mexican cuisine inscribed by UNESCO 2010 — mole poblano, tacos al pastor, mezcal + tequila (Jalisco AOC), chocolate (Mayan origin 2000 BCE)',
    ],
    toneFr: 'vibrant, ancestral maya + colonial espagnol, gastronomique UNESCO',
  },
];

export function findDestinationBySlug(slug: string): DestinationGuideSeed | null {
  return DESTINATIONS.find((d) => d.slug === slug) ?? null;
}
