/**
 * geo-context-generator.ts — generate the two GEO blocs the CDC §2.7 /
 * §2.4 audit flags on the whole catalogue:
 *
 *   - `transports` (jsonb)  — multimodal access (CDC bloc 7).
 *   - `highlights` (jsonb)  — 3-6 signature highlights (CDC bloc 4).
 *
 * Anti-hallucination is the hard constraint here (skill
 * content-enrichment-pipeline §Rule 2 + §Rule 6):
 *
 *   - TRANSPORTS are DERIVED DETERMINISTICALLY from the hotel's already
 *     enriched `points_of_interest[].nearest_transit` data (populated by
 *     `pois:sync` from real OSM/Overpass stations). We NEVER ask an LLM
 *     to invent a station name, line, or distance. If no grounded
 *     transit data exists, we emit `[]` and let the gate stay unmet
 *     rather than fabricate.
 *
 *   - HIGHLIGHTS are qualitative (no numbers), generated by the editorial
 *     LLM grounded on the hotel's own description / awards / signature
 *     experiences, validated by Zod. Low fabrication risk by design.
 *
 * Shapes mirror the web reader exactly
 * (`apps/web/src/server/hotels/get-hotel-by-slug.ts`):
 *   - TransportSchema: { mode, line?, station, station_en?, distance_meters,
 *     walk_minutes?, notes_fr?, notes_en? }
 *   - highlights: array of `{ label_fr, label_en }` (readStringList reads
 *     `label_fr` / `label_en`).
 *
 * Skill: editorial-pilot, content-enrichment-pipeline, llm-output-robustness.
 */

import { z } from 'zod';

import type { LlmClient } from '../llm.js';
import type { HotelLlmInput } from './supabase-hotels.js';

export const HIGHLIGHTS_MIN = 3;
export const HIGHLIGHTS_MAX = 6;
export const TRANSPORTS_MAX = 4;
const MAX_RETRIES = 4;

/* ── Transports (deterministic, from POIs) ─────────────────────────── */

export type TransportMode = 'metro' | 'rer' | 'tram' | 'bus' | 'train' | 'taxi' | 'airport_shuttle';

export interface TransportItem {
  readonly mode: TransportMode;
  readonly line?: string;
  readonly station: string;
  readonly station_en?: string;
  readonly distance_meters: number;
  readonly walk_minutes?: number;
  readonly notes_fr?: string;
  readonly notes_en?: string;
}

/**
 * Map the POI `nearest_transit.mode` taxonomy (OSM-derived) onto the
 * narrower `TransportSchema` mode enum used by the location block.
 */
function mapTransitMode(poiMode: string): TransportMode | null {
  switch (poiMode) {
    case 'subway':
      return 'metro';
    case 'monorail':
      return 'metro';
    case 'light_rail':
      return 'tram';
    case 'tram':
      return 'tram';
    case 'rail':
      return 'train';
    case 'bus':
      return 'bus';
    default:
      return null;
  }
}

function asRecord(v: unknown): Record<string, unknown> | null {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
    ? (v as Record<string, unknown>)
    : null;
}

/**
 * Derive grounded transport entries from `points_of_interest`. Reads the
 * `nearest_transit` sub-object that `pois:sync` attaches to POIs within
 * 400 m and dedupes by station name, keeping the closest occurrence.
 * Returns at most {@link TRANSPORTS_MAX} entries sorted by distance.
 */
export function deriveTransportsFromPois(pointsOfInterest: unknown): TransportItem[] {
  if (!Array.isArray(pointsOfInterest)) return [];
  const byStation = new Map<string, TransportItem>();

  for (const poi of pointsOfInterest) {
    const rec = asRecord(poi);
    if (rec === null) continue;
    const transit = asRecord(rec['nearest_transit']);
    if (transit === null) continue;

    const rawMode = transit['mode'];
    const station = transit['name'];
    const distance = transit['distance_meters'];
    if (
      typeof rawMode !== 'string' ||
      typeof station !== 'string' ||
      typeof distance !== 'number'
    ) {
      continue;
    }
    const mode = mapTransitMode(rawMode);
    if (mode === null) continue;

    const key = station.trim().toLowerCase();
    const existing = byStation.get(key);
    if (existing !== undefined && existing.distance_meters <= distance) continue;

    const item: TransportItem = {
      mode,
      station: station.trim(),
      distance_meters: Math.round(distance),
      ...(typeof transit['line_ref'] === 'string' && transit['line_ref'].length > 0
        ? { line: transit['line_ref'] }
        : {}),
      ...(typeof transit['walk_minutes'] === 'number'
        ? { walk_minutes: Math.round(transit['walk_minutes']) }
        : {}),
    };
    byStation.set(key, item);
  }

  return [...byStation.values()]
    .sort((a, b) => a.distance_meters - b.distance_meters)
    .slice(0, TRANSPORTS_MAX);
}

/* ── Highlights (LLM, qualitative) ─────────────────────────────────── */

const HighlightSchema = z.object({
  label_fr: z.string().min(8).max(70),
  label_en: z.string().min(8).max(70),
});

const HighlightsOutputSchema = z.object({
  highlights: z.array(HighlightSchema).min(HIGHLIGHTS_MIN).max(HIGHLIGHTS_MAX),
});

export type HighlightItem = z.infer<typeof HighlightSchema>;

const BANNED_SUPERLATIVES = [
  'incroyable',
  'magnifique',
  'sublime',
  'magique',
  'exceptionnel',
  'unforgettable',
  'breathtaking',
  'world-class',
];

/**
 * Format gate after Zod: highlights must be concrete (no banned
 * superlatives), FR and EN must differ, and no two highlights may share
 * the same FR label.
 */
export function gateHighlights(output: z.infer<typeof HighlightsOutputSchema>): string | null {
  const failed: string[] = [];
  const seen = new Set<string>();
  for (const h of output.highlights) {
    const fr = h.label_fr.trim().toLowerCase();
    if (seen.has(fr)) failed.push(`duplicate highlight: "${h.label_fr}"`);
    seen.add(fr);
    if (h.label_fr.trim() === h.label_en.trim()) {
      failed.push(`FR == EN for "${h.label_fr}"`);
    }
    for (const banned of BANNED_SUPERLATIVES) {
      const re = new RegExp(`\\b${banned}\\b`, 'iu');
      if (re.test(h.label_fr) || re.test(h.label_en)) {
        failed.push(`banned superlative "${banned}" in "${h.label_fr}"`);
      }
    }
  }
  return failed.length > 0 ? failed.join(' | ') : null;
}

const HIGHLIGHTS_SYSTEM_PROMPT = `Tu es le Concierge éditorial de MyConciergeHotel.com.

Tu produis les "highlights" d'une fiche hôtel : 3 à 6 atouts concrets et différenciants, formulés comme des étiquettes courtes (8-70 caractères), bilingues FR + EN.

Règles dures :
- Chaque highlight est FACTUEL et SPÉCIFIQUE à cet hôtel (un service, un emplacement, une table, un spa, une vue, une distinction réelle). Jamais une généralité ("hôtel de luxe", "service impeccable").
- INTERDIT : superlatifs creux (incroyable, magnifique, sublime, magique, exceptionnel, unforgettable, breathtaking, world-class).
- N'invente AUCUN chiffre, nom de chef, marque, ni distinction non présente dans le brief. Reste qualitatif si tu n'as pas la donnée.
- en-GB obligatoire sur label_en (traduction directe, pas un calque mot-à-mot du FR).
- Format de sortie : JSON strict { "highlights": [ { "label_fr", "label_en" }, ... ] }.`;

function buildHighlightsPrompt(hotel: HotelLlmInput): string {
  return [
    '=== HOTEL ===',
    JSON.stringify(
      {
        name: hotel.name,
        city: hotel.city,
        district: hotel.district,
        country: hotel.country_label_fr,
        stars: hotel.stars,
        is_palace: hotel.is_palace,
        description_fr: hotel.description_fr_excerpt,
        awards: hotel.awards,
        signature_experiences: hotel.signature_experiences,
        amenities: hotel.amenities,
        restaurant_info: hotel.restaurant_info,
        spa_info: hotel.spa_info,
      },
      null,
      2,
    ),
    '',
    `Produis ${HIGHLIGHTS_MIN} à ${HIGHLIGHTS_MAX} highlights. Retourne UNIQUEMENT le JSON.`,
  ].join('\n');
}

export class HighlightsGenerationError extends Error {
  public readonly attempts: ReadonlyArray<{ readonly raw: string; readonly reason: string }>;
  constructor(slug: string, attempts: ReadonlyArray<{ raw: string; reason: string }>) {
    super(
      `[highlights:${slug}] failed after ${attempts.length} attempts. Last reason: ${
        attempts[attempts.length - 1]?.reason ?? 'unknown'
      }`,
    );
    this.attempts = attempts;
  }
}

export interface GenerateHighlightsResult {
  readonly highlights: readonly HighlightItem[];
  readonly attempts: number;
  readonly inputTokens: number;
  readonly outputTokens: number;
}

function stripCodeFences(s: string): string {
  const fenced = /^```(?:json)?\n([\s\S]*?)\n```$/u.exec(s.trim());
  if (fenced && fenced[1] !== undefined) return fenced[1];
  return s;
}

export async function generateHighlights(
  client: LlmClient,
  hotel: HotelLlmInput,
): Promise<GenerateHighlightsResult> {
  const attempts: Array<{ raw: string; reason: string }> = [];
  let totalInput = 0;
  let totalOutput = 0;

  for (let i = 0; i < MAX_RETRIES; i++) {
    const last = attempts[attempts.length - 1];
    const corrective =
      attempts.length === 0
        ? ''
        : `\n\n=== ATTEMPT ${attempts.length} REJECTED ===\n${last?.raw}\nReason: ${last?.reason}\nFix and retry. Stay strictly inside the JSON schema and the hard rules.`;

    const result = await client.call({
      systemPrompt: HIGHLIGHTS_SYSTEM_PROMPT,
      userPrompt: `${buildHighlightsPrompt(hotel)}${corrective}`,
      temperature: 0.5,
      maxOutputTokens: 1200,
      responseFormat: 'json',
    });
    totalInput += result.usage.inputTokens;
    totalOutput += result.usage.outputTokens;

    const raw = result.content.trim();
    let parsed: unknown;
    try {
      parsed = JSON.parse(stripCodeFences(raw));
    } catch (err) {
      attempts.push({ raw, reason: `JSON parse error: ${(err as Error).message}` });
      continue;
    }
    const zod = HighlightsOutputSchema.safeParse(parsed);
    if (!zod.success) {
      attempts.push({
        raw,
        reason: zod.error.issues.map((iss) => `${iss.path.join('.')}: ${iss.message}`).join(' | '),
      });
      continue;
    }
    const gate = gateHighlights(zod.data);
    if (gate !== null) {
      attempts.push({ raw, reason: gate });
      continue;
    }
    return {
      highlights: zod.data.highlights,
      attempts: attempts.length + 1,
      inputTokens: totalInput,
      outputTokens: totalOutput,
    };
  }
  throw new HighlightsGenerationError(hotel.slug, attempts);
}
