/**
 * Factual amenities for Airelles Gordes, La Bastide — CDC §2.6 (≥ 80).
 * Sourced from airelles.com (informations pratiques, spa, restaurants, MICE).
 */

export interface AirellesAmenityRecord {
  readonly key: string;
  readonly label_fr: string;
  readonly label_en: string;
}

function a(key: string, label_fr: string, label_en: string): AirellesAmenityRecord {
  return { key, label_fr, label_en };
}

/** 80 curated amenities — no `michelin_restaurant` (property has fine dining, not a Michelin star). */
export const AIRELLES_AMENITIES: readonly AirellesAmenityRecord[] = [
  a('concierge_24h', 'Conciergerie 24h/24', '24-hour concierge'),
  a('reception_24h', 'Réception 24h/24', '24-hour front desk'),
  a('daily_housekeeping', 'Service de chambre quotidien', 'Daily housekeeping'),
  a(
    'housekeeping_twice_daily',
    'Service de chambre deux fois par jour',
    'Twice-daily housekeeping',
  ),
  a('turndown_service', 'Service de couverture', 'Turndown service'),
  a('luggage_storage', 'Consigne à bagages', 'Luggage storage'),
  a('laundry', 'Blanchisserie', 'Laundry service'),
  a('dry_cleaning', 'Nettoyage à sec', 'Dry cleaning'),
  a('valet', 'Voiturier', 'Valet parking'),
  a('butler_service', 'Service de majordome (suites)', 'Butler service (suites)'),
  a('airport_shuttle', 'Transfert aéroport', 'Airport transfer'),
  a('limousine_service', 'Service de limousine', 'Limousine service'),
  a('car_rental', 'Location de voiture', 'Car rental desk'),
  a('florist', 'Fleuriste', 'Florist'),
  a('shoe_shine', 'Cirage de chaussures', 'Shoeshine service'),
  a('wake_up_service', 'Service de réveil', 'Wake-up service'),
  a('currency_exchange', 'Change de devises', 'Currency exchange'),
  a('multilingual_staff', 'Personnel multilingue', 'Multilingual staff'),
  a('tour_desk', 'Bureau d’excursions', 'Tour desk'),
  a('gift_shop', 'Boutique Ladurée', 'Ladurée boutique'),
  a('spa', 'Spa Airelles by Guerlain', 'Airelles Spa by Guerlain'),
  a('indoor_pool', 'Piscine intérieure du spa', 'Spa indoor pool'),
  a('outdoor_pool', 'Piscines extérieures', 'Outdoor swimming pools'),
  a('heated_pool', 'Piscines chauffées', 'Heated pools'),
  a('terrace_pool', 'Piscine terrasse panoramique', 'Panoramic terrace pool'),
  a('kids_pool', 'Piscine Summer Camp', 'Summer Camp pool'),
  a('fitness', 'Salle de fitness Technogym (90 m²)', 'Technogym fitness room (90 sq m)'),
  a('personal_trainer', 'Coach personnel', 'Personal trainer'),
  a('hammam', 'Hammam', 'Hammam'),
  a('sauna', 'Sauna', 'Sauna'),
  a('yoga', 'Cours de yoga', 'Yoga classes'),
  a('massage', 'Massages et soins Guerlain', 'Guerlain massages and treatments'),
  a(
    'beauty_salon',
    'Soins Barbara Sturm & Seed to Skin',
    'Barbara Sturm & Seed to Skin treatments',
  ),
  a('restaurant', 'Six restaurants sur place', 'Six on-site restaurants'),
  a('fine_dining', 'Clover Gordes (Jean-François Piège)', 'Clover Gordes (Jean-François Piège)'),
  a('provencal_table', 'La Table de La Bastide', 'La Table de La Bastide'),
  a('italian_trattoria', 'La Bastide de Pierres (trattoria)', 'La Bastide de Pierres (trattoria)'),
  a('wood_fired_grill', 'Grill au feu de bois (Clover)', 'Wood-fired grill (Clover)'),
  a('breakfast', 'Petit-déjeuner buffet', 'Buffet breakfast'),
  a('brunch_service', 'Brunch du dimanche', 'Sunday brunch'),
  a('bar', 'Bar et salons', 'Bar and lounges'),
  a('lounge', 'Salons de réception', 'Reception lounges'),
  a('afternoon_tea', 'Salon de thé Ladurée', 'Ladurée tea salon'),
  a('room_service_24h', 'Room service', 'Room service'),
  a('private_dining', 'Dîners privatifs', 'Private dining'),
  a('air_conditioning', 'Climatisation', 'Air conditioning'),
  a('minibar', 'Minibar', 'Minibar'),
  a('in_room_safe', 'Coffre-fort en chambre', 'In-room safe'),
  a('nespresso_machine', 'Machine Nespresso', 'Nespresso machine'),
  a('flat_screen_tv', 'Télévision écran plat', 'Flat-screen TV'),
  a('bathrobes_slippers', 'Peignoirs et chaussons', 'Bathrobes and slippers'),
  a('premium_toiletries', 'Produits d’accueil de luxe', 'Premium toiletries'),
  a('pillow_menu', 'Carte des oreillers', 'Pillow menu'),
  a('blackout_curtains', 'Rideaux occultants', 'Blackout curtains'),
  a('soundproofing', 'Insonorisation', 'Soundproofing'),
  a('walk_in_shower', 'Douche à l’italienne', 'Walk-in shower'),
  a('bathtub', 'Baignoire', 'Bathtub'),
  a('balcony', 'Balcon', 'Balcony'),
  a('terrace', 'Terrasse privative (suites)', 'Private terrace (suites)'),
  a('fireplace', 'Cheminée (salons)', 'Fireplace (lounges)'),
  a('wifi', 'Wi-Fi gratuit', 'Free Wi-Fi'),
  a('wifi_premium', 'Wi-Fi haut débit', 'High-speed Wi-Fi'),
  a('usb_charging', 'Ports de charge USB', 'USB charging ports'),
  a('family_friendly', 'Adapté aux familles', 'Family-friendly'),
  a('kids_club', 'Airelles Summer Camp', 'Airelles Summer Camp'),
  a('summer_camp', 'Summer Camp (enfants)', 'Summer Camp (children)'),
  a('babysitting', 'Service de baby-sitting', 'Babysitting service'),
  a('cribs_available', 'Lits bébé disponibles', 'Cribs available'),
  a('pet_friendly', 'Animaux acceptés sur demande', 'Pets allowed on request'),
  a('connecting_rooms', 'Chambres communicantes', 'Connecting rooms'),
  a('business_center', 'Centre d’affaires', 'Business centre'),
  a('meeting_rooms', 'Cinq salles de séminaire', 'Five seminar rooms'),
  a('seminar_av', 'Équipement audiovisuel', 'Audiovisual equipment'),
  a('private_events', 'Événements privés', 'Private events'),
  a('wedding_services', 'Mariages et réceptions', 'Weddings and receptions'),
  a(
    'step_free_access',
    'Accès de plain-pied (parties communes)',
    'Step-free access (public areas)',
  ),
  a('accessible_rooms', 'Chambres accessibles', 'Accessible rooms'),
  a('elevator', 'Ascenseur', 'Elevator'),
  a('electric_charging', 'Borne de recharge électrique', 'EV charging station'),
  a('garden', 'Jardins suspendus', 'Hanging gardens'),
  a('hanging_gardens', 'Jardins suspendus panoramiques', 'Panoramic hanging gardens'),
  a('private_parking', 'Parking privé', 'Private parking'),
  a('non_smoking', 'Établissement non-fumeur', 'Non-smoking property'),
  a('tennis_court', 'Court de tennis', 'Tennis court'),
  a('e_bike_rental', 'Vélos électriques', 'E-bike rental'),
  a('outdoor_cinema', 'Cinéma en plein air', 'Open-air cinema'),
  a('excursion_desk', 'Excursions Luberon', 'Luberon excursions'),
] as const;
