/**
 * Factual amenities for Le Bristol Paris — CDC §2.6 (≥ 80).
 * Sourced from Oetker Collection / hotel-bristol.com (palace Faubourg Saint-Honoré).
 */

export interface LeBristolParisAmenityRecord {
  readonly key: string;
  readonly label_fr: string;
  readonly label_en: string;
}

function a(key: string, label_fr: string, label_en: string): LeBristolParisAmenityRecord {
  return { key, label_fr, label_en };
}

/** 80 curated amenities — Epicure 3★ and 114 Faubourg 1★ listed separately from generic dining. */
export const LE_BRISTOL_PARIS_AMENITIES: readonly LeBristolParisAmenityRecord[] = [
  a('concierge_24h', 'Conciergerie Les Clefs d’Or 24h/24', '24-hour Les Clefs d’Or concierge'),
  a('reception_24h', 'Réception 24h/24', '24-hour front desk'),
  a('daily_housekeeping', 'Service de chambre quotidien', 'Daily housekeeping'),
  a('turndown_service', 'Service de couverture', 'Turndown service'),
  a('luggage_storage', 'Consigne à bagages', 'Luggage storage'),
  a('laundry', 'Blanchisserie', 'Laundry service'),
  a('dry_cleaning', 'Nettoyage à sec', 'Dry cleaning'),
  a('valet', 'Voiturier', 'Valet parking'),
  a('limousine_service', 'Service de limousine', 'Limousine service'),
  a('car_rental', 'Location de voiture', 'Car rental desk'),
  a('wake_up_service', 'Service de réveil', 'Wake-up service'),
  a('currency_exchange', 'Change de devises', 'Currency exchange'),
  a('multilingual_staff', 'Personnel multilingue', 'Multilingual staff'),
  a('tour_desk', 'Bureau d’excursions', 'Tour desk'),
  a('florist', 'Fleuriste', 'Florist'),
  a('shoe_shine', 'Cirage de chaussures', 'Shoeshine service'),
  a('press_service', 'Presse quotidienne', 'Daily newspaper service'),
  a('oetker_collection', 'Oetker Collection', 'Oetker Collection'),
  a('palace_atout_france', 'Palace Atout France (depuis 2011)', 'Palace Atout France (since 2011)'),
  a('interior_garden', 'Jardin intérieur de 1 200 m²', '1,200 sq m interior garden'),
  a('rooftop_pool', 'Piscine couverte 6e étage — vue Paris', '6th-floor indoor pool — Paris views'),
  a(
    'epicure_restaurant',
    'Restaurant Epicure (3 étoiles MICHELIN)',
    'Epicure restaurant (3 MICHELIN Stars)',
  ),
  a('114_faubourg', '114 Faubourg (1 étoile MICHELIN)', '114 Faubourg (1 MICHELIN Star)'),
  a('cafe_antonia', 'Café Antonia', 'Café Antonia'),
  a('le_jardin_francais', 'Le Jardin Français', 'Le Jardin Français'),
  a('bar_du_bristol', 'Le Bar du Bristol', 'Le Bar du Bristol'),
  a('fine_dining', 'Table gastronomique Epicure', 'Epicure fine dining'),
  a('brasserie', 'Brasserie 114 Faubourg', '114 Faubourg brasserie'),
  a('afternoon_tea', 'Afternoon tea (Le Jardin Français)', 'Afternoon tea (Le Jardin Français)'),
  a('breakfast', 'Petit-déjeuner', 'Breakfast'),
  a('room_service_24h', 'Room service 24h/24', '24-hour room service'),
  a('private_dining', 'Dîners privatifs', 'Private dining'),
  a('spa_la_mer', 'Spa Le Bristol by La Mer', 'Spa Le Bristol by La Mer'),
  a('hammam', 'Hammam', 'Hammam'),
  a('sauna', 'Sauna', 'Sauna'),
  a('fitness', 'Centre de fitness', 'Fitness centre'),
  a('spa_treatments', 'Soins spa sur rendez-vous', 'Spa treatments by appointment'),
  a('personal_trainer', 'Coach personnel (sur demande)', 'Personal trainer (on request)'),
  a('air_conditioning', 'Climatisation', 'Air conditioning'),
  a('minibar', 'Minibar', 'Minibar'),
  a('in_room_safe', 'Coffre-fort en chambre', 'In-room safe'),
  a('flat_screen_tv', 'Télévision écran plat', 'Flat-screen TV'),
  a('bathrobes_slippers', 'Peignoirs et chaussons', 'Bathrobes and slippers'),
  a('luxury_toiletries', 'Produits d’accueil haut de gamme', 'Luxury toiletries'),
  a('complimentary_water', 'Eau minérale offerte', 'Complimentary mineral water'),
  a('pillow_menu', 'Carte des oreillers', 'Pillow menu'),
  a('blackout_curtains', 'Rideaux occultants', 'Blackout curtains'),
  a('soundproofing', 'Insonorisation', 'Soundproofing'),
  a('walk_in_shower', 'Douche à l’italienne', 'Walk-in shower'),
  a('bathtub', 'Baignoire', 'Bathtub'),
  a('marble_bathroom', 'Salle de bain en marbre', 'Marble bathroom'),
  a('louis_xv_decor', 'Mobilier d’époque Louis XV / XVI', 'Louis XV / XVI period furniture'),
  a('garden_view', 'Vue sur le jardin intérieur', 'Interior garden view'),
  a('city_view', 'Vue sur les toits de Paris', 'Paris rooftop view'),
  a('terrace', 'Terrasse privative (suites)', 'Private terrace (suites)'),
  a('wifi', 'Wi-Fi gratuit', 'Free Wi-Fi'),
  a('wifi_premium', 'Wi-Fi haut débit', 'High-speed Wi-Fi'),
  a('usb_charging', 'Ports de charge USB', 'USB charging ports'),
  a('king_bed', 'Lit king size', 'King-size bed'),
  a('connecting_rooms', 'Chambres communicantes', 'Connecting rooms'),
  a('family_friendly', 'Adapté aux familles', 'Family-friendly'),
  a('cribs_available', 'Lits bébé disponibles', 'Cribs available'),
  a('extra_beds', 'Lits supplémentaires (sur demande)', 'Extra beds (on request)'),
  a('pets_allowed', 'Animaux acceptés (conditions)', 'Pets allowed (conditions apply)'),
  a('business_center', 'Centre d’affaires', 'Business centre'),
  a('meeting_rooms', 'Salles de réunion', 'Meeting rooms'),
  a('seminar_av', 'Équipement audiovisuel', 'Audiovisual equipment'),
  a('private_events', 'Événements privés', 'Private events'),
  a('wedding_services', 'Mariages et réceptions', 'Weddings and receptions'),
  a('mice_capable', 'Capacité MICE', 'MICE capability'),
  a(
    'step_free_access',
    'Accès de plain-pied (parties communes)',
    'Step-free access (public areas)',
  ),
  a('accessible_rooms', 'Chambres accessibles', 'Accessible rooms'),
  a('elevator', 'Ascenseur', 'Elevator'),
  a('non_smoking', 'Établissement non-fumeur', 'Non-smoking property'),
  a('smoke_free_rooms', 'Chambres non-fumeur', 'Smoke-free rooms'),
  a('valet_parking', 'Parking avec voiturier', 'Valet parking'),
  a('nearby_parking', 'Parking à proximité', 'Nearby parking'),
  a('electric_charging', 'Borne de recharge électrique', 'EV charging station'),
  a('faubourg_saint_honore', 'Rue du Faubourg Saint-Honoré', 'Rue du Faubourg Saint-Honoré'),
  a('elysee_proximity', 'À 300 m du Palais de l’Élysée', '300 m from the Élysée Palace'),
  a('madeleine_metro', 'Proche métro Madeleine', 'Near Madeleine metro'),
  a('butler_service', 'Service de majordome (suites)', 'Butler service (suites)'),
  a('art_collection', 'Collection d’art en demeure', 'In-residence art collection'),
] as const;
