/**
 * Factual amenities for Les Airelles Courchevel — CDC §2.6 (≥ 80).
 * Sourced from airelles.com (informations pratiques, spa, restaurants, ski services).
 */

export interface LesAirellesCourchevelAmenityRecord {
  readonly key: string;
  readonly label_fr: string;
  readonly label_en: string;
}

function a(key: string, label_fr: string, label_en: string): LesAirellesCourchevelAmenityRecord {
  return { key, label_fr, label_en };
}

/** 80 curated amenities — alpine palace, ski-in/ski-out, Spa Airelles by La Mer. */
export const LES_AIRELLES_COURCHEVEL_AMENITIES: readonly LesAirellesCourchevelAmenityRecord[] = [
  a('concierge_24h', 'Conciergerie 24h/24', '24-hour concierge'),
  a('reception_24h', 'Réception 24h/24', '24-hour front desk'),
  a('daily_housekeeping', 'Service de chambre quotidien', 'Daily housekeeping'),
  a('turndown_service', 'Service de couverture', 'Turndown service'),
  a('luggage_storage', 'Consigne à bagages', 'Luggage storage'),
  a('laundry', 'Blanchisserie', 'Laundry service'),
  a('dry_cleaning', 'Nettoyage à sec', 'Dry cleaning'),
  a('valet', 'Voiturier', 'Valet parking'),
  a('ski_valet', 'Ski valet (Bernard Orcel)', 'Ski valet (Bernard Orcel)'),
  a('ski_room', 'Salle de ski chauffée', 'Heated ski room'),
  a('ski_in_ski_out', 'Ski-in / ski-out', 'Ski-in / ski-out access'),
  a('limousine_service', 'Service de limousine', 'Limousine service'),
  a('helicopter_transfer', 'Transfert hélicoptère (altiport)', 'Helicopter transfer (altiport)'),
  a('airport_shuttle', 'Transfert aéroport', 'Airport transfer'),
  a('car_rental', 'Location de voiture', 'Car rental desk'),
  a('multilingual_staff', 'Personnel multilingue', 'Multilingual staff'),
  a('tour_desk', 'Bureau d’excursions', 'Tour desk'),
  a('florist', 'Fleuriste', 'Florist'),
  a('wake_up_service', 'Service de réveil', 'Wake-up service'),
  a('currency_exchange', 'Change de devises', 'Currency exchange'),
  a('spa', 'Spa Airelles by La Mer', 'Airelles Spa by La Mer'),
  a('spa_lba', 'Soins LBA (Laboratoires Botanique Avancée)', 'LBA treatments'),
  a('indoor_pool', 'Piscine intérieure du spa', 'Spa indoor pool'),
  a('kids_pool', 'Piscine enfants au spa', 'Children’s spa pool'),
  a('jacuzzi', 'Jacuzzi 40 °C', '40 °C jacuzzi'),
  a('hammam', 'Hammam', 'Hammam'),
  a('snow_cave', 'Grotte de neige sensorielle', 'Sensory snow cave'),
  a('cryotherapy', 'Cryothérapie', 'Cryotherapy'),
  a('fitness', 'Salle de fitness Technogym', 'Technogym fitness room'),
  a('personal_trainer', 'Coach personnel (sur demande)', 'Personal trainer (on request)'),
  a('hair_salon', 'Salon coiffure', 'Hair salon'),
  a('nail_salon', 'Salon manucure', 'Nail salon'),
  a('massage', 'Massages et soins La Mer', 'La Mer massages and treatments'),
  a('restaurant', 'Six restaurants sur place', 'Six on-site restaurants'),
  a(
    'michelin_table',
    'La Table des Airelles (1 étoile MICHELIN)',
    'La Table des Airelles (1 MICHELIN Star)',
  ),
  a('matsuhisa', 'Matsuhisa Courchevel (Nobu)', 'Matsuhisa Courchevel (Nobu)'),
  a('palladio', 'Palladio (cuisine italienne)', 'Palladio (Italian cuisine)'),
  a('savoyard_table', 'Le Coin Savoyard', 'Le Coin Savoyard'),
  a('chalet_pierres', 'Le Chalet de Pierres (pistes)', 'Le Chalet de Pierres (on slopes)'),
  a('folie_douce', 'La Folie Douce · La Fruitière', 'La Folie Douce · La Fruitière'),
  a('bar', 'Bar et fumoir', 'Bar and smoking lounge'),
  a('breakfast', 'Petit-déjeuner buffet', 'Buffet breakfast'),
  a('half_board', 'Demi-pension disponible', 'Half-board available'),
  a('room_service', 'Room service', 'Room service'),
  a('private_dining', 'Dîners privatifs', 'Private dining'),
  a('kids_club', 'Winter Camp & Kids Club', 'Winter Camp & Kids Club'),
  a('teen_room', 'Teenage Room', 'Teenage Room'),
  a('cinema', 'Cinéma privé', 'Private cinema'),
  a('ice_rink', 'Patinoire', 'Ice rink'),
  a('boutique', 'Boutique Vanille & Lilas', 'Vanille & Lilas boutique'),
  a('air_conditioning', 'Climatisation', 'Air conditioning'),
  a('minibar', 'Minibar (produits bio offerts)', 'Minibar (complimentary organic treats)'),
  a('in_room_safe', 'Coffre-fort en chambre', 'In-room safe'),
  a('nespresso_machine', 'Machine Nespresso', 'Nespresso machine'),
  a('flat_screen_tv', 'Télévision écran plat', 'Flat-screen TV'),
  a('bathrobes_slippers', 'Peignoirs et chaussons', 'Bathrobes and slippers'),
  a('premium_toiletries', 'Produits d’accueil de luxe', 'Premium toiletries'),
  a('pillow_menu', 'Carte des oreillers', 'Pillow menu'),
  a('blackout_curtains', 'Rideaux occultants', 'Blackout curtains'),
  a('soundproofing', 'Insonorisation', 'Soundproofing'),
  a('walk_in_shower', 'Douche à l’italienne', 'Walk-in shower'),
  a('hammam_shower', 'Douche hammam (suites)', 'Hammam shower (suites)'),
  a('bathtub', 'Baignoire', 'Bathtub'),
  a('fireplace', 'Cheminée (salons et suites)', 'Fireplace (lounges and suites)'),
  a('balcony', 'Balcon (chambres et suites)', 'Balcony (rooms and suites)'),
  a('terrace', 'Terrasse privative (suites)', 'Private terrace (suites)'),
  a('mountain_view', 'Vue montagne', 'Mountain view'),
  a('wifi', 'Wi-Fi gratuit', 'Free Wi-Fi'),
  a('wifi_premium', 'Wi-Fi haut débit', 'High-speed Wi-Fi'),
  a('family_friendly', 'Adapté aux familles', 'Family-friendly'),
  a('babysitting', 'Service de baby-sitting', 'Babysitting service'),
  a('cribs_available', 'Lits bébé disponibles', 'Cribs available'),
  a('pet_friendly', 'Animaux acceptés (accueil VIP)', 'Pets welcome (VIP welcome)'),
  a('connecting_rooms', 'Chambres communicantes', 'Connecting rooms'),
  a('private_chalets', 'Chalets privés (Ormello, 1908)', 'Private chalets (Ormello, 1908)'),
  a('butler_service', 'Service de majordome (suites)', 'Butler service (suites)'),
  a('meeting_rooms', 'Salons de réception', 'Meeting salons'),
  a('private_events', 'Événements privés', 'Private events'),
  a('wedding_services', 'Mariages et réceptions', 'Weddings and receptions'),
  a('step_free_access', 'Accès PMR (établissement)', 'Step-free access (property)'),
  a('elevator', 'Ascenseur', 'Elevator'),
  a('non_smoking', 'Établissement non-fumeur', 'Non-smoking property'),
  a('palace_label', 'Palace Atout France', 'Atout France Palace'),
  a('airelles_collection', 'Maison Airelles', 'Airelles maison'),
  a(
    'three_valleys',
    'Domaine des 3 Vallées (600 km de pistes)',
    'Three Valleys ski area (600 km of slopes)',
  ),
  a('courchevel_1850', 'Courchevel 1850 · Jardin Alpin', 'Courchevel 1850 · Jardin Alpin'),
];
